### ISSUE TITLE
Bug in Chrome: fonts don't show

### ISSUE THREAD

**Issue by kaelig** [algolia/docsearch#100]
Steps to reproduce:

1. Go to https://www.lightningdesignsystem.com/components/badges/
2. Perform a search
3. Part of the text simply doesn't show

![screenshot 2016-05-26 17 50 43](https://cloud.githubusercontent.com/assets/85783/15594464/7affc982-236a-11e6-8202-730f4608f4fd.png)

I'm blaming Chrome, but I wonder if you had any idea where that could come from and if there was a fix.

**Comment by pixelastic** [comment]
That's really weird, I never had that before.

I tested on `Chrome Version 51.0.2704.63 (64-bit)` and `Chromium Version 44.0.2403.89 Ubuntu 15.04 (64-bit)` and it worked as expected

**Comment by redox** [comment]
Oh wow, I also manage to reproduce it :/ @Shipow @LukyVj can you help?

**Comment by redox** [comment]
If I copy the page content locally (`file://`), I cannot reproduce it anymore :/ The only difference I think about is that locally the fonts are not loaded (because I didn't update the underlying font URLs).

Definitely something weird around that.

**Comment by Shipow** [comment]
I've sent a DM on slack. Will post the final solution here, I think it's just an error (from the reset script) in the stack that prevent fastdom to init the correctly.

**Comment by kaelig** [comment]
We have just fixed the error and it still happens. I wonder if it's related to this https://bugs.chromium.org/p/chromium/issues/detail?id=336476 and if it could be the same issue as this one: http://stackoverflow.com/questions/35582497/font-face-not-rendered-on-chrome-version-48-0-2564-116

**Comment by vvo** [comment]
I just had the bug but on the whole website, when loaded in the background. Was not able to reproduce.

**Comment by LukyVj** [comment]
I can check, it can be FOIT ( aka flash of invisible text )

**Comment by kaelig** [comment]
Thanks! AFAIK, FOIT is a different issue but it's worth investigating. I'll also ping people from the Chrome team since that only seems to happen in Chrome.

**Comment by aputinski** [comment]
So after some digging, I've found the cause of the problem. The pages that have the font issue contain `<iframe>` tags that load in the same stylesheet as the parent (which use `@font-face` rules). When I remove the `@font-face` from the CSS in the `<iframe>`, the search works as expected. Unfortunately, we need the custom font inside the `<iframe>`, so that won't be a valid fix for us.

**Comment by kaelig** [comment]
Good catch! Could we load the fonts using an alternative method and see what it does? Maybe using JavaScript (+ localstorage?) instead or inlining the @font-face declaration in the document. I'm also curious to know what the cache headers impact is because we don't cache fonts efficiently at the moment.

**Comment by kaelig** [comment]
Note that loading the fonts from a CDN (`$static-font-path: 'https://www2.sfdcstatic.com/system/shared/common/assets/fonts/SalesforceSans';`) somehow fixes the issue. Could be a domain sharding-related thing.

**Comment by kaelig** [comment]
We've re-activated DocSearch on https://www.lightningdesignsystem.com/, and we now load fonts using our CDN, which seems to have solved the problem!

I must admit this is one of the weirdest bugs I've seen in my career!
