### ISSUE TITLE
[Config question]DocSearch for multiple builds in the application

### ISSUE THREAD

**Issue by Tulean** [algolia/docsearch#1006]
Hello Algolia Devs,

I am working now on a website that uses Docusaurus v1. Due to some limitations, we are not able to use Docusaurus versioning system; therefore, we are currently generating separated build per version. My question is, if it is possible to integrate algolia search without constantly updating the config file in the docsearch for each version. Is it possible to have some kind of wildcard that will consider links. For example `https://example.com/documentation/v8.00/`, instead of `v8.00` we could use `*` and the crawler will automatically search all of the builds?

```
ex. of the app structure

-v1Build (docusaurus build)
-v2Build  (docusaurus build)
-v3Build
index.html which serves as a bridge between versions
```

Thank you

**Comment by shortcuts** [comment]
Hi @Tulean,

Beside the versioning, you can use variables in your `start_urls`, the variables can either be set manually or with some inlined js.
- [config file with inline js](https://github.com/algolia/docsearch-configs/blob/master/configs/ignite.json)
- [config with hardcoded version variables](https://github.com/algolia/docsearch-configs/blob/master/configs/vuejs.json)

Hope this answers your question!

**Comment by Tulean** [comment]
Hello @shortcuts, 
thank you for answering. I will try it out and create a PR for the config changes. In the meantime, I will keep this issue open.

Thank you
