### ISSUE TITLE
Question - Is it possible to have docsearch use multiple indices?

### ISSUE THREAD

**Issue by tjperry07** [algolia/docsearch#1007]
I am working on a project where there are two indices
- Main documentation
- API reference

Is it possible to have the docsearch UI pull from both indices? They are part of the same app. I've got the data indexed, I just can't figure out how to add in two indices based on the run your own docs.

```js
  var search = instantsearch({
    appId: 'app-id',
    apiKey: 'api-key',
    indexName: 'docs',
    routing: true
  });
...
```

**Comment by shortcuts** [comment]
Hi @tjperry07,

For now, it is not possible to retrieve both indices from the DocSearch instance.

However, you can use the [custom selectors](https://docsearch.algolia.com/docs/config-file/#using-custom-selectors-per-page) to have both endpoints under the same index, and then use [custom tags](https://docsearch.algolia.com/docs/config-file/#using-custom-tags) to filter your search.

Here's a live example with the [bootstrap config](https://github.com/algolia/docsearch-configs/blob/master/configs/bootstrap.json)
