### ISSUE TITLE
Image text on webpage is misspelled

### ISSUE THREAD

**Issue by jhaynie** [algolia/docsearch#1013]
![image](https://user-images.githubusercontent.com/6027/122609373-7fc5fc80-d043-11eb-9272-ba905d5f0050.png)

`environment` is spelled wrong in the search box image 👾

**Comment by Haroenv** [comment]
As you closed this, I guess you're aware, but for anyone else, that's on purpose to highlight the fact that searching still works when there's typos in the query!
