### ISSUE TITLE
Problems implementing docsearch

### ISSUE THREAD

**Issue by AngeloCG97** [algolia/docsearch#1017]
## Problems implementing docsearch

 I am implementing docsearch manually in a project in docusaurus, I am using the configuration file they recommend in their documentation , I only edited the proper values ​​of my project (urls), but when running the file it throws me that there are 0 records, they have reports of some reason why this could happen other than because of the configuration file since it is fine, because I tried it with another project and if it works.

**Live reproduction:**

https://eosio.lacchain.net/

## Environment

- OS: [ Linux]
- DocSearch version: [last]

**Comment by AngeloCG97** [comment]
If I am using just that configuration file, here you can see it.

```

{
    "index_name": "lacchain_eosio",
    "start_urls": [
      "https://eosio.lacchain.net/"
    ],
    "sitemap_urls": [
      "https://eosio.lacchain.net/sitemap.xml"
    ],
    "sitemap_alternate_links": true,
    "stop_urls": [],
    "selectors": {
      "lvl0": {
        "selector": "(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]",
        "type": "xpath",
        "global": true,
        "default_value": "Documentation"
      },
      "lvl1": "header h1",
      "lvl2": "article h2",
      "lvl3": "article h3",
      "lvl4": "article h4",
      "lvl5": "article h5, article td:first-child",
      "lvl6": "article h6",
      "text": "article p, article li, article td:last-child"
    },
    "strip_chars": " .,;:#",
    "custom_settings": {
      "separatorsToIndex": "_",
      "attributesForFaceting": [
        "language",
        "version",
        "type",
        "docusaurus_tag"
      ],
      "attributesToRetrieve": [
        "hierarchy",
        "content",
        "anchor",
        "url",
        "url_without_anchor",
        "type"
      ]
    }
}
```

**Comment by shortcuts** [comment]
Do you have client-side rendered content? If so, you can try adding `js_render: true`

**Comment by AngeloCG97** [comment]
I add this in the configuration file?

**Comment by shortcuts** [comment]
Yes, sorry I forgot to add the documentation, see https://docsearch.algolia.com/docs/config-file/#js_render-optional

**Comment by AngeloCG97** [comment]
It worked, thank you so much for your help.
