### ISSUE TITLE
Send search request to Algolia with some delay

### ISSUE THREAD

**Issue by Markeli** [algolia/docsearch#1018]
## Describe the problem

Now a new search request is sending to Aloglia on each query change. I want to reduce the number of requests to Aloglia. It would be nice if Aloglia client will have some delay option in config. If the delay is set, the request will be sent if the user is not printing. Without delay in the config, the search behavior will be the same as now.

## Describe the solution

Add new option to Algolia search plugin config. If the delay is set search query will be sent only after a user stops inputting the query. I assume that desired behavior can be easily achieved by React hooks. There is an example on StackOverflow: https://stackoverflow.com/questions/53071774/reactjs-delay-onchange-while-typing

**Comment by Haroenv** [comment]
Could you explain why you want to limit the number of requests?

**Comment by Markeli** [comment]
There are two reasons:
- to improve the search experience for users with a slow Internet connection
- to reduce costs of Algolia search. 

For example, a user wants to find articles with the word `project`. With the current solution, there are will be 7 separate search requests (for `p`/`pr`/`pro`/`proj`/`proje`/`projec`/`project`).

**Comment by Markeli** [comment]
In other words, we want to disable something like `searchAsYouType` option. 

By the way, this option has already existed in `instantSeacrh.js`.
![image](https://user-images.githubusercontent.com/5919274/125783042-9ae42cb7-c58a-44f6-8fca-81b554816ace.png)

**Comment by Haroenv** [comment]
Because docsearch is mainly meant for implementations for which we cover the cost, there so far hasn't been a reason to debounce the search

**Comment by Haroenv** [comment]
With the PR that was just merged (once that's released), you can debounce like this:


```ts
type Func = (...args: any[]) => any;

type DebouncedFunction<TFunction extends Func> = (
  this: ThisParameterType<TFunction>,
  ...args: Parameters<TFunction>
) => Promise<ReturnType<TFunction>>;

// Debounce a function call to the trailing edge.
// The debounced function returns a promise.
export function debounce<TFunction extends Func>(
  func: TFunction,
  wait: number
): DebouncedFunction<TFunction> {
  let lastTimeout: ReturnType<typeof setTimeout> | null = null;
  return function (...args) {
    // @ts-ignore-next-line
    const that = this;
    return new Promise((resolve, reject) => {
      if (lastTimeout) {
        clearTimeout(lastTimeout);
      }
      lastTimeout = setTimeout(() => {
        lastTimeout = null;
        Promise.resolve(func.apply(that, args)).then(resolve).catch(reject);
      }, wait);
    });
  };
}

const searchClient = algoliasearch(
  'xxx',
  'yyy'
);
const originalSearch = searchClient.search;
searchClient.search = debounce(originalSearch, 10);
```

**Comment by shortcuts** [comment]
Thanks for the snippet @Haroenv, I forgot to add it to the issue. I've also added [a sandbox](https://codesandbox.io/s/docsearch-v3-debounced-search-gnx87) to make it work with DocSearch in the body of the PR.

@Markeli note that for now, it's not possible to debounce the search via the Docusaurus config file since the JavaScript will be serialized to a JSON object and therefore ignored. I'll see with the Docusaurus team if we can find a good alternative.

**Comment by Markeli** [comment]
Great! Thanks for this fix)
