### ISSUE TITLE
can't receive api-key email for long time

### ISSUE THREAD

**Issue by Lockeysama** [algolia/docsearch#1035]
Hi,

I have apply for the search api-key, but i can't receive the email when i apply for the website(https://docsearch.algolia.com/apply/) long time.
Can anybody help me?
My website is https://help.xzytdcs.com/ and email is develop@entertech.cn .

Thank you

**Comment by Haroenv** [comment]
Looks like you don't have any content on that page yet, what are you planning to add to the page?

**Comment by Lockeysama** [comment]
Thank for your answer. 
We will add a document, something about a device using tDCS technology and how to use this device. And, we planning edit content over this week, it's will be completed within a few days.

**Comment by shortcuts** [comment]
Hey @Lockeysama,

We refused your application (around 6 days ago) because your website was in building stage. Once the content has been added, feel free to re-apply!

**Comment by Lockeysama** [comment]
@shortcuts 
Ok, thank you!

**Comment by Lockeysama** [comment]
@shortcuts Sorry excuse, we has been finished the documents, and resend the apply email again. Could you pass for us?

**Comment by shortcuts** [comment]
Hey @Lockeysama, we will check your application ASAP. As we receive a lot everyday, please give it a few days :D

**Comment by Lockeysama** [comment]
@shortcuts 👌🏻，thank you very much!
