### ISSUE TITLE
Can't receive API key email

### ISSUE THREAD

**Issue by ilyamerman** [algolia/docsearch#1037]
Hey guys :)

We applied to the Algolia Docsearch through https://docsearch.algolia.com/apply/
It's been 6 days without any confirmation, API key or any response to the mail we've specified
We didn't see anywhere else to write about asking for the application status, can you please check?
Our website is: https://stoic-almeida-1eda82.netlify.app/
And the email through which I've applied is ilya@unit.co

Thanks!

**Comment by shortcuts** [comment]
Hey there,

The full process can take up to two weeks, I'll make sure to deploy some configs in the afternoon

Have a nice day :D
