### ISSUE TITLE
"cannot read property value of undefined"

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#1041]
## Description

Hello,

On [this website](https://projects.pixelastic.com/reddinx/), for most of the keywords no results are showing and I have the following error in the console:
![image](https://user-images.githubusercontent.com/283419/130332442-d1e83d5c-fc3a-430b-b5d0-8404ce517aea.png)
Some other keywords seem to work fine.

## Steps to reproduce

1. Go to https://projects.pixelastic.com/reddinx/
2. Click on the top search bar
3. Search for `local` => errors displayed in the console
4. Search for `indexed` => seems to work as expected

**Live reproduction:**

https://projects.pixelastic.com/reddinx/

## Expected behavior

I have DocSearch enabled on a handful of other websites, using the same HTML theme ([firost](https://projects.pixelastic.com/firost/), [norska](https://projects.pixelastic.com/norska/), [imoen](https://projects.pixelastic.com/imoen/)) and everything is working correctly. This makes me wonder if this is an issue with the js library, or the indexed data/config?

## Environment

- OS: Linux
- Browser: Chrome
- DocSearch version: alpha

PS: #trust #candor #care #grit #humility :heart:

**Comment by shortcuts** [comment]
Hey Tim!

I've fixed this issue in https://github.com/algolia/docsearch/pull/1039 and will release the new version Monday!

This is related to the indexing (as far as I've seen in previous occurences of this bug), with an `undefined` `lvl0`.

**Comment by pixelastic** [comment]
Thanks!

By the way, is there an ETA for the official release of the v3? Or is using `@alpha` still the way to go to have the awesome new full screen UI?

**Comment by shortcuts** [comment]
Hey Tim,

It's now released in the `3.0.0-alpha.40`: https://github.com/algolia/docsearch/pull/1042

Yes, using the `@alpha` is still the best option for now, we don't have an ETA as we are first revamping the infrastructure of DocSearch, but then we will fully focus on providing a stable v3 :D

**Comment by pixelastic** [comment]
@shortcuts Thanks, it's no longer displaying errors.

But I have irrelevant results returned now. Duplicate entries that redirect to pages that do not match my query (except in the sidebar)

![image](https://user-images.githubusercontent.com/283419/130695953-debf01f4-cdb7-40b2-bc72-3906c029efc7.png)

I don't think it is related to my markup, as I'm using the same theme on other websites. Would you want me to create a new issue for that?

**Comment by shortcuts** [comment]
Hey @pixelastic, it seems that you config wasn't using the same template as the other websites, I've pushed an update here: https://github.com/algolia/docsearch-configs/pull/4524 so let me know if it solves it!
