### ISSUE TITLE
Cannot receive docsearch email

### ISSUE THREAD

**Issue by Poorunga** [algolia/docsearch#1044]
## Description

Two days ago, I applied my website on https://docsearch.algolia.com/apply/, but I still haven't received any email from docsearch until today. Could you tell me where I did something wrong?

## Steps to reproduce

1. Go to `https://docsearch.algolia.com/`
2. Click on `JOIN IN THE PROGRAM`
3. Fill in my `DOCUMENTATION URL` and `EMAIL`
4. Check `I'M THE OWNER OF THE WEBSITE AND I HAVE READ THE CHECKLIST`
5. Click on `JOIN IN THE PROGRAM`

**Live reproduction:**

https://codesandbox.io/s/github/algolia/docsearch/tree/next/examples/js

## Expected behavior

I hope to receive the mail and use docsearch.

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android] Windows 
- Browser: [e.g. Chrome, Safari] Chrome
- DocSearch version: [e.g. 3.0.0] Unknown

**Comment by shortcuts** [comment]
Hi,

We need to manually check your website before confirming/refusing your application. Note that we receive hundreds of new requests everyday, so it can take a bit of time!

Hope you understand,
Have a nice day!

**Comment by Poorunga** [comment]
OK
