### ISSUE TITLE
Don't include `process` in build

### ISSUE THREAD

**Issue by kai687** [algolia/docsearch#1046]
## Description

I struggled to use DocSearch@alpha via CDN. 
It's because the built versions contain references to `process`, which isn't defined in a browser environment.

With a build tool, you can replace it, as @Haroenv mentioned in #980, but if I use it via CDN, 
I have to include another code snippet:

```js
const process = {
  env: {
    NODE_ENV: "production"
  }
}
```

## Steps to reproduce

Here's a minimal example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Testing DocSearch 3.0 alpha from CDN</title>
  <script src="https://cdn.jsdelivr.net/npm/@docsearch/js@alpha"></script>
</head>
<body>
  <div id="container"></div>
  <script>
    /* const process = {
      env: {
        NODE_ENV: "production"
      }
    } */
    docsearch({
      container: '#container',
      apiKey: '25626fae796133dc1e734c6bcaaeac3c',
      indexName: 'docsearch',
      debug: true,
    })
  </script>
  
</body>
</html>
```

uncomment the `const process ...` part and it should work.

## Expected behavior

It would be nice to just be able to use this version of Docsearch without having to mock `process`. 

## Environment

- DocSearch version: 3.0.0-alpha-40

**Comment by shortcuts** [comment]
Thanks for the detailed issue @kai687!

I've provided a fix in https://github.com/algolia/docsearch/pull/1047 and will let you know once the new version has been released!

**Comment by imageslr** [comment]
Encountered the same issue. Thanks for your solution.
