### ISSUE TITLE
Using v3.0.0-alpha.40, Uncaught TypeError: t is undefined

### ISSUE THREAD

**Issue by faunaee** [algolia/docsearch#1049]
## Description

When I use the alpha 40, I get the following error in my browser console, and no searching occurs:

```
Uncaught TypeError: t is undefined
    ke https://cdn.jsdelivr.net/npm/@docsearch/js@alpha:6
    <anonymous> https://cdn.jsdelivr.net/npm/@docsearch/js@alpha:6
    <anonymous> http://127.0.0.1:8080/path/to/page.html:1858
```

## Steps to reproduce

Per the README, I added the following line to my HTML:

```
<script src="https://cdn.jsdelivr.net/npm/@docsearch/js@alpha"></script>
```

And then I initialize docsearch with:

```
<script>
var algoliaSearch = docsearch({
  appId: '{{config.algolia-app-id}}',
  apiKey: '{{config.algolia-api-key}}',
  indexName: '{{config.algolia-idx-name}}',
  inputSelector: '#algolia-input',
  autocompleteOptions: { hint: false, keyboardShortcuts: ['s'] },
  algoliaOptions: { hitsPerPage: 10 },
  debug: false
}).autocomplete
algoliaSearch.on('autocomplete:closed', function () { algoliaSearch.autocomplete.setVal() })
</script>
```

Then I the affected page in my browser. That's when the error appears in the console.

When I fetch the version 2 of docsearch, using the following line, no error occurs:

```
<script src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
```

**Live reproduction:**

https://codesandbox.io/s/admiring-surf-1dwqk?file=/index.html

Unfortunately, codesandbox clears the console very shortly after the error is emitted.

## Expected behavior

The docsearch alpha should work: I should be able to search my index without a showstopping error.

## Environment

- OS: macOS
- Browser: Chrome & Firefox
- DocSearch version: 3.0.0-alpha.40

**Comment by shortcuts** [comment]
Hey @faunaee!

> And then I initialize docsearch with:

This code snippet will only work with DocSearch v2 (docsearch.js@2), which is on the `master` branch of this repository: https://github.com/algolia/docsearch/tree/master, and documented on https://docsearch.algolia.com/

> Per the README, I added the following line to my HTML:

This is the import for DocSearch v3, which is on the `next` branch of this repository: https://github.com/algolia/docsearch and soon documented! You can see the progress on this PR: https://github.com/algolia/docsearch/pull/1048

To make DocSearch v3 work, you can check our [examples](https://github.com/algolia/docsearch/tree/next/examples), those [React](https://codesandbox.io/s/docsearch-js-v3-playground-z9oxj) and [JavaScript](https://codesandbox.io/s/docsearch-js-v3-playground-z9oxj) codesandboxes or browse the preview of the new documentation on the PR above.

Hope this solves your issue :D

**Comment by faunaee** [comment]
Thanks for pointing me in the right direction, and apologies for the noise.
