### ISSUE TITLE
Set lighter default grayscale colors

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#11]
![image](https://cloud.githubusercontent.com/assets/283419/11811907/a07f8e48-a338-11e5-8e94-a6cad4bba8f2.png)
The current default colors are too dark and aggressive.
https://github.com/algolia/docsearch.js/blob/develop/src/styles/_variables.scss

cc @shipow

**Comment by redox** [comment]
What about something gray/blue like:

<img width="531" alt="screen shot 2015-12-16 at 19 14 41" src="https://cloud.githubusercontent.com/assets/29529/11849667/46fc3c3a-a429-11e5-82c4-eff71822c4c1.png">
