### ISSUE TITLE
Allow to override empty template

### ISSUE THREAD

**Issue by maxiloc** [algolia/docsearch#115]

**Comment by rayrutjes** [comment]
Any update on this one? Would love to be able to override it.

**Comment by vvo** [comment]
Is this a complex thing to do? Are we talking about the autocomplete.js empty template?

**Comment by pixelastic** [comment]
@rayrutjes @maxiloc Are you talking about the "Sorry, no results found" template or is it about setting a template to an empty string?

**Comment by s-pace** [comment]
Might be doable thanks to the v3 (beta so far)

**Comment by ghominejad** [comment]
I didn't find any option to override the templates yet!

**Comment by Shipow** [comment]
@ghominejad  We are currently working on a new version that will allow that. It's actively developed right now! Stay plugged.
