### ISSUE TITLE
Have multiple language in docusaurus give 404 error

### ISSUE THREAD

**Issue by code-masala** [algolia/docsearch#1160]

**Comment by shortcuts** [comment]
Hey @code-masala, could you please provide more informations on this issue?
- Which Docusaurus version
- What is the website URL
- What is the DocSearch index

Also, if the issue is related to Docusaurus only, please open this issue on https://github.com/facebook/docusaurus

**Comment by code-masala** [comment]
Hi @shortcuts  how can i send the data of "https://domain.com/faq/private-profile/1/" 
and avoid sending this data
 "https://domain.com/rn/faq/private-profile/1/"

**Comment by shortcuts** [comment]
I'm not sure I get your question, but this seems to be related to some Docusaurus routing: https://docusaurus.io/docs/next/creating-pages#routing

I'd suggest you to ask your question directly on the Docusaurus repository https://github.com/facebook/docusaurus. DocSearch is not related to Docusaurus, we only provide the search to their website.
