### ISSUE TITLE
Open a document in the new page when click hit

### ISSUE THREAD

**Issue by mantou132** [algolia/docsearch#1168]
## Describe the problem

Avoid destroying the current work of the user

## Describe the solution

Add an option when initialization

**Comment by shortcuts** [comment]
Hey, here's how to do it from the `hitComponent` props: [sandbox](https://codesandbox.io/s/docsearch-v3-open-in-new-tab-nk088?file=/src/App.js), you can also take a look at the [`navigator` option](https://docsearch.algolia.com/docs/api#navigator)

**Comment by mantou132** [comment]
`navigator` option seems to be a behavior for controlling keyboard navigation.

In addition, my project is not a React project. I am using @docsearch/js library, so i can't use `hitComponent` option

**Comment by shortcuts** [comment]
Hey, you can also do so in JavaScript, and without JSX: [sandbox](https://codesandbox.io/s/docsearch-v3-hit-component-without-jsx-wktxw?file=/src/index.js)
