### ISSUE TITLE
`hitComponent` option no longer accepts an object

### ISSUE THREAD

**Issue by posva** [algolia/docsearch#1169]
## Description

Upgrading from 1.0.0-alpha.28 to alpha.41 doesn't render anything when searching for results.

## Steps to reproduce

We were using this option:

```js
    hitComponentee: ({
        hit,
        children
      }: {
        hit: DocSearchHit
        children: any
      }) => {
        const relativeHit = hit.url.startsWith('http')
          ? getRelativePath(hit.url as string)
          : hit.url

        return {
          type: 'a',
          ref: undefined,
          constructor: undefined,
          key: undefined,
          props: {
            href: hit.url,
            onClick: (event: MouseEvent) => {
              // this is the important part for us
              if (isLocalNavigation(relativeHit)) router.go(relativeHit)
            },
            children
          }
        }
      }
```

But it no longer renders anything and we need override the `onClick()` prop. How do we do this now without JSX?

(the demo sandbox is empty so I couldn't create a sample)

## Expected behavior

To see the `<a>` elements like before.

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- DocSearch version: [e.g. 3.0.0]

**Comment by shortcuts** [comment]
Hey @posva,

Glad to see you doing the migration to the latest version, please don't hesitate to let us know if there's any issue!

> To see the <a> elements like before.

I believe there was a few other default parameters required in the in-between updates, I managed to make it work here [on this sandbox](https://codesandbox.io/s/docsearch-v3-hit-component-without-jsx-wktxw?file=/src/index.js). We also have the `navigator` props forwarded to Autocomplete which might also work for your routing implementation: https://docsearch.algolia.com/docs/api#navigator 

> (the demo sandbox is empty so I couldn't create a sample)

Oops, fixed here: https://github.com/algolia/docsearch/commit/891fd88d1bd3670533fc4a8b41d21678a6f6b832

**Comment by posva** [comment]
Sorry, I completely forgot to followup on this! That sample is all I needed, thanks!
