### ISSUE TITLE
Uncaught (in promise) Error: [groupBy]: Object has no key

### ISSUE THREAD

**Issue by fnurl** [algolia/docsearch#119]
I am trying to use docsearch with an index I have on algolia (i.e. not crawled by algolia). However, I am getting a `Uncaught (in promise) Error: [groupBy]: Object has no key` error in my console.

I tried setting the `Attribute for distinct` to one of my attributes (page ID) and tried setting `Distinct` to `true` and the numerical values, but I still get the `groupBy` error.

I see some references to properties named `lvl0`, `lvl1` ... `lvl6`. Are these automatically generated or do I have to add these properties to my index?

**Comment by maxiloc** [comment]
Yes you need to have the same record structure. This is why docsearch is a separate project.

Here what it looks like:

```
{
  "content": null,
  "url": "http://vuejs.org/guide/index.html#Hello-World",
  "weight": {
    "position": 4,
    "level": 70,
    "page_rank": 0
  },
  "tags": [],
  "hierarchy": {
    "lvl2": null,
    "lvl3": "Hello World",
    "lvl0": "Guide",
    "lvl1": "Getting Started",
    "lvl6": null,
    "lvl4": null,
    "lvl5": null
  },
  "hierarchy_radio": {
    "lvl2": null,
    "lvl3": "Hello World",
    "lvl0": null,
    "lvl1": null,
    "lvl6": null,
    "lvl4": null,
    "lvl5": null
  },
  "hierarchy_complete": {
    "lvl2": null,
    "lvl3": "Guide > Getting Started > Hello World",
    "lvl0": "Guide",
    "lvl1": "Guide > Getting Started",
    "lvl6": null,
    "lvl4": null,
    "lvl5": null
  },
  "type": "lvl3",
  "anchor": "Hello-World",
  "objectID": "1547703490"
}
```

**Comment by xiaoDC** [comment]
@maxiloc I have the same problem! But i do not find the config about 'lv' in documents. Could you give me some config example? Thanks!
