### ISSUE TITLE
Translations does not work

### ISSUE THREAD

**Issue by AndersBrohus** [algolia/docsearch#1199]
## Description

When we are trying to translate the DocSearch in our Vue component it does not work even through the documentation is followed.

## Steps to reproduce

1. Copy the example code in the documentation on this page, https://docsearch.algolia.com/docs/api#translations-1 and insert in Vue
2. Setting the translations option to the const
3. See it does not work.

**Live reproduction:**

https://codesandbox.io/s/serene-surf-o07tu

## Expected behavior

Expected the DocSearch component to be translated.

## Environment

- OS: Windows - Node V16 - VueJS 
- Browser: Latest Chrome
- DocSearch version: 3.0.0-alpha.41

**Comment by shortcuts** [comment]
Hey @AndersBrohus,

Sorry to have published the documentation early, but this version of DocSearch has not been released yet.

We were in production freeze during Black Friday etc. I'll release a new version tomorrow afternoon (Paris time), so this option will be available in the `3.0.0-alpha.42` version

**Comment by AndersBrohus** [comment]
Hi @shortcuts,

Thanks alot, for the quick answer 😀
I was starting thinking it was just me that did something strange 🤣

Looking forward till tomorrow for the new package 😀
