### ISSUE TITLE
Cannot apply for docsearch program (website error)

### ISSUE THREAD

**Issue by softmarshmallow** [algolia/docsearch#1232]
![image](https://user-images.githubusercontent.com/16307013/146965638-f4d852cf-66cb-4d93-9e20-97cc7c513424.png)

Last tested at `4:35 PM Tuesday, December 21, 2021 Coordinated Universal Time (UTC)`

Tested on Chrome, Safari.

I'm not able to make a application for docsearch program. Can you confirm the website error or guide me through this case?

Thanks!

**Comment by johnnyreilly** [comment]
> Access to fetch at 'https://docsearch-hub.herokuapp.com/form/inbound' from origin 'https://docsearch.algolia.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Also seeing this!

**Comment by shortcuts** [comment]
Hey, we had a long maintenance this afternoon, I'm restarting the server right now so you can apply! :D

**Comment by johnnyreilly** [comment]
![image](https://user-images.githubusercontent.com/1010525/146970299-4470d889-9fbb-497a-b207-39c22c769f54.png)

Success! Thanks!

**Comment by softmarshmallow** [comment]
Confirmed. working now :)
![image](https://user-images.githubusercontent.com/16307013/146976582-fd238837-82b8-4449-9cc3-59f64585232c.png)
