### ISSUE TITLE
Esc doesn't close the modal window in Firefox

### ISSUE THREAD

**Issue by axilleas** [algolia/docsearch#1247]
## Description

<kbd>Esc</kbd> doesn't close the modal window in Firefox.

## Steps to reproduce

1. Open firefox and go to https://docsearch.algolia.com/
2. Click on search
3. Type something
4. Hit <kbd>Esc</kbd>

## Expected behavior

<kbd>Esc</kbd> dismisses the search modal.

## Environment

- OS: Linux
- Browser: Firefox 95.0.1
- DocSearch version: tested at https://docsearch.algolia.com/ and https://docusaurus.io/

**Comment by shortcuts** [comment]
Hey there,

I'm not able to reproduce, do you have any extensions activated that could interact with keyboard events?

**Comment by axilleas** [comment]
@shortcuts ha! Yeah, you were right, seems Tridactyl was the culprit :/ Thanks for investigating 🙂
