### ISSUE TITLE
can't resign

### ISSUE THREAD

**Issue by xiaozhangQAQ** [algolia/docsearch#1257]
## Describe the problem

![1641893954(1)](https://user-images.githubusercontent.com/24986789/148918298-c5db0396-3aba-4882-9ae3-c99f919b4471.png)

**Comment by shortcuts** [comment]
Hey,

What is the error saying in the console? I just tried and was able to submit a new application.

An other user had a similar issue and was able to submit after retrying https://github.com/algolia/docsearch/issues/1161

**Comment by xiaozhangQAQ** [comment]
![1641894256(1)](https://user-images.githubusercontent.com/24986789/148919260-60912fd6-8e2c-45ae-a38a-643e04b17615.png)
cant submit

**Comment by shortcuts** [comment]
Our service is hosted on Heroku, it might be possible that it is not accessible where you live
