### ISSUE TITLE
A scroll bar appears as a rectangle in every search result in macOS

### ISSUE THREAD

**Issue by axilleas** [algolia/docsearch#1258]
## Description

This happens in macOS in almost every browser. It seems a scroll bar is added in the results before the rightmost icons. We found about this bug in the MR where we migrate GitLab Docs to v3 https://gitlab.com/gitlab-org/gitlab-docs/-/merge_requests/2321.

## Steps to reproduce

1. On a macOS machine, go to http://axil-algolia-docsearch-v3.178.62.207.141.nip.io/
2. Click on Search
3. Type `dast`
4. See that small rectangles appear in each result

For more info, you can follow the discussion in https://gitlab.com/gitlab-org/gitlab-docs/-/merge_requests/2321/diffs#note_805169476.

![](https://gitlab.com/gitlab-org/gitlab-docs/uploads/1fcae51734010736f4bcea31e4541f7d/image.png)

## Expected behavior

No scroll bar inside the results.

## Environment

- OS: macOS
- Browser: Chrome, Safari
- DocSearch version: https://cdn.jsdelivr.net/npm/@docsearch/js@alpha

**Comment by shortcuts** [comment]
Hey @axilleas,

Since I can't reproduce on other websites, I guess there is some CSS interacting with the DocSearch styles, especially with the `DocSearch-Hit-content-wrapper` class.

Do you have some `line-height` override or something similar in your codebase?

**Comment by axilleas** [comment]
@shortcuts very good question! We might have something like this. It didn't occur to me to check some other websites to verify :/ I'll get back to you when I know more, thanks!
