### ISSUE TITLE
Search results not formatting well.

### ISSUE THREAD

**Issue by blee1170** [algolia/docsearch#127]
I am using docsearch scrapper to write my indexs, but for the search side I can not get it to format correctly. When I use the example, all of the results are listed with only the width of my search box. Its totally un-readable.

css and javascript is not my realm of knowledge, so I am sure I am missing something. 

Here is my javascript:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />
<script type="text/javascript" src="js/docsearch.min.js"></script>
        <script type="text/javascript">
          docsearch({
                    apiKey: '27d0176XXXXXXXX,
                    indexName: 'git_hub_pages',
                    inputSelector: '#search-input'
                });

        </script>
```

My search box looks like this:
```
<div class="navbar-form navbar-left hidden-xs hidden-sm">
                      <input id="search-input" type="text" class="form-control" placeholder="Search...">
                  </div>
```

Let me know if you need more info or have a idea to try.  Thanks!

**Comment by maxiloc** [comment]
Not sure if it's related but you probably need to specify the `appId`, otherwise it looks ok

**Comment by maxiloc** [comment]
Other thing to check is that `js/docsearch.min.js` is version 2.* and not 1.*

**Comment by blee1170** [comment]
Just as you posted I was zooming in on the issue of not using the correct mix of docsearch 1/2 with the correct css. I got it working now. Thanks yet again for the awesome support.
