### ISSUE TITLE
docsearch dropdown width

### ISSUE THREAD

**Issue by LukyVj** [algolia/docsearch#128]
![](https://files.slack.com/files-pri/T026AN50K-F1U802BH7/pasted_image_at_2016_07_22_15_16.png)

**Comment by LukyVj** [comment]
Seems like the https://github.com/algolia/docsearch/pull/129 didn't fixed it ? cc @redox

**Comment by vvo** [comment]
It's just not released @LukyVj, anyone listed here: https://www.npmjs.com/package/docsearch.js can do a release. I can add you too. What's your npm user name?

**Comment by LukyVj** [comment]
It's okay, I'll let you guys release the change, but it was a change related to the UI of community.algolia.com/docsearch
