### ISSUE TITLE
Upgrading from v2 to v3 doesn't work

### ISSUE THREAD

**Issue by bbatsov** [algolia/docsearch#1280]
## Description

I've tried to unsuccessfully upgrade from Docsearch v2 to v3 and I have a feeling that something's missing in the instructions.
I've been using v2 in a static site for a couple of years now, but the steps for v3 don't work in my usecase. 

## Steps to reproduce

I've done the update in https://github.com/clojure-emacs/docs.cider.mx/commit/604a4a33dddd7f11e199c848144504df0a604a70, following the instructions here https://docsearch.algolia.com/docs/DocSearch-v3#without-package-manager-1

However, it seems that the imports in the docs only work at the top-level, and even without them I get an error:

![image](https://user-images.githubusercontent.com/103882/150668955-52576792-1ab2-402e-87d1-e18a69929d67.png)

**Live reproduction:**

https://docs.cider.mx

## Expected behavior

It should work. :-)

## Environment

- OS: Windows 11
- Browser: [Firefox,, Chrome]
- DocSearch version: [3.0.0]

**Comment by bodinsamuel** [comment]
Hello,

the api has changed, inputSelector is no longer correct as docsearch will create an input for you.
If you create an empty div `<div id="docsearch"></div>` and apply this snippet it should work
```js
docsearch({
  container: '#docsearch',
  appId: 'YOUR_APP_ID',
  indexName: 'YOUR_INDEX_NAME',
  apiKey: 'YOUR_SEARCH_API_KEY',
});
```

**Comment by bbatsov** [comment]
I'm an idiot! 🤦‍♂️ Thanks for the quick response! It works great now!

**Comment by bodinsamuel** [comment]
No worries, glad it works now 🙌🏻
