### ISSUE TITLE
Search results showing up "behind" other div

### ISSUE THREAD

**Issue by blee1170** [algolia/docsearch#130]
I added the search input to a template that has a navbar setup. When I use the search, the results a cut off because its being rendered behind another element. I cant for the life of me figure out how to change the z-index of the search box to send it to the front. Is there any way that I can do that?

<img width="321" alt="screen shot 2016-07-26 at 8 45 02 am" src="https://cloud.githubusercontent.com/assets/6674849/17140234/5af4c66a-530d-11e6-9b42-0a8c29e7c91e.png">

This is the template I am using with couscous.io: [https://github.com/CouscousPHP/Template-ReadTheDocs](https://github.com/CouscousPHP/Template-ReadTheDocs)

Any help would be wonderful.

**Comment by LukyVj** [comment]
Hi @blee1170 :) 
Is your code available somewhere ? That way, I can look into it. 
Otherwise, I advise you to look for `.ds-dropdown-menu:before`, and change the z-index on it. 

Hope it will help.

**Comment by blee1170** [comment]
Here is my template. [https://github.com/blee1170/Template-ReadTheDocs](https://github.com/blee1170/Template-ReadTheDocs). tried changing the ```.algolia-autocomplete .ds-dropdown-menu:before``` But to no effect.

**Comment by LukyVj** [comment]
I'm on it 👍

**Comment by LukyVj** [comment]
Ok, found the issue. 
There was a bug on `.algolia-autocomplete .ds-dropdown-menu [class^=ds-dataset-]` ( on `docsearch.min.css`, line `223` ). 

It seems that both `.algolia-autocomplete .ds-dropdown-menu [class^=ds-dataset-]` and `.ds-dropdown-menu:before` got the same css line : `z-index: 1000 !important`.

To fix it, just keep the `z-index` rule on the `:before` element, and either reduce or remove the one from `[class^=ds-dataset-]`. 

I just double checked, to see if the error was from our side, and it seems it's a modification you made, so removing it shouldn't impact anything else 🙂

Let me know if it helped you!

**Comment by blee1170** [comment]
I made that change, no difference. Nothing I seem to do changes the style for that element.

<img width="360" alt="screen shot 2016-07-26 at 9 23 44 am" src="https://cloud.githubusercontent.com/assets/6674849/17141717/dc3c15c0-5312-11e6-9e54-0caf98ab1809.png">

It always has the z-index of 100. I have never been able to touch it.

**Comment by LukyVj** [comment]
I can get the expected result, if I clean those lines from `/Template-ReadTheDocs/css/docsearch.min.css`: 
```
    z-index: 1000 !important; // Line 230
    z-index: 1000 !important; // Line 234
```

The result would be the following : 
![](https://puu.sh/qf4TI/ca9bb6c94f.png)

**Comment by blee1170** [comment]
I made those changes. The only z-index is in the line 195 block. It still is "behind" the element on the right. The first part of the results show, but the full text is cut off, just like in your example.

<img width="321" alt="screen shot 2016-07-26 at 9 34 47 am" src="https://cloud.githubusercontent.com/assets/6674849/17142086/692a3c7c-5314-11e6-90e6-05d57ac87441.png">

**Comment by LukyVj** [comment]
My bad, I didn't understood your first request, I'm checking :)

**Comment by blee1170** [comment]
No problem. I appreciate your help. CSS is not my thing at all.

**Comment by LukyVj** [comment]
Okay, potential fix : 
Either you remove the `overflow: hidden` of `.wy-nav-side` located in `/Template-ReadTheDocs/css/theme.css`
Or instead, you can add :  `.wy-nav-side { overflow: inherit; }`  in `/Template-ReadTheDocs/css/theme-fixes.css`.

That being said, I would do the N°2 :)

**Comment by blee1170** [comment]
HOT DAMN! That was it. I will fix it in the upstream couscous repo. 

Yet again, your teams support has been awesome.

**Comment by LukyVj** [comment]
No problem!
I assume that this `overflow: hidden;` may be useful at some point, for couscous.
But I tried several things, adding items in it, shrinking the window & else, and it seems useless on your case. 

Thank you for the sweet words ✨
