### ISSUE TITLE
Stable release of v3

### ISSUE THREAD

**Issue by jshah4517** [algolia/docsearch#1303]
Sorry if this has been asked, but I couldn't find it at a quick glance.

When is a stable release of v3 planned? We don't like to use pre-stable releases on production websites, it looks like there have been a large number of alpha releases now.

**Comment by shortcuts** [comment]
Hey, thanks for asking! 

We are actually looking at open issues to see if we encounter any blockers for the stable v3 release. The next release ideally be the stable one!

**Comment by shortcuts** [comment]
Hey there, v3 stable has been released just now :) https://github.com/algolia/docsearch/releases/tag/v3.0.0

**Comment by jshah4517** [comment]
Thanks!
