### ISSUE TITLE
When typing Japanese, pressing the Enter key to confirm completion selects the document.

### ISSUE THREAD

**Issue by hisaichi5518** [algolia/docsearch#1304]
## Description

Pressing Enter when the text input is not finalized will take you to the document.

## Steps to reproduce

1. Type Japanese using Google Japanese Input.
2. Press the Enter key to confirm your input.
3. redirect to the document.

**Live reproduction:**
- https://jestjs.io/ja/

![Untitled](https://user-images.githubusercontent.com/248093/154092258-026859a1-e458-4a8f-a37f-c8f1bd96c157.gif)

## Expected behavior
1. Input Japanese using Google Japanese Input.
2. Press the Enter key to confirm your input.
3. The input is confirmed.

## Environment
- OS: macOS 11.6.2
- Browser: Google Chrome
- DocSearch version: 3.0.0

**Comment by axilleas** [comment]
AFAIK, this is the default behavior, not sure if there's a way to change that.

**Comment by shortcuts** [comment]
Hey,

> AFAIK, this is the default behavior, not sure if there's a way to change that.

Indeed here two of the input sources are focused, so pressing enter will submit both form. 

Using the mouse to select the Japanese text shouldn't trigger the search (which is expected), but I don't think there's a fix to that 🤔

**Comment by hisaichi5518** [comment]
Thank you for your reply.

> Using the mouse to select the Japanese text shouldn't trigger the search (which is expected), but I don't think there's a fix to that 🤔

Yes, if I select the Japanese text with the mouse the search will not be executed.

We can use `KeyboardEvent.isComposing` to change it so that pressing enter will not search when the input is not confirmed.

The `KeyboardEvent.isComposing` returns true when the input is not finalized.
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing

**Comment by Haroenv** [comment]
I think we could check isComposing here: https://github.com/algolia/autocomplete/blob/next/packages/autocomplete-core/src/onKeyDown.ts#L108

**Comment by shortcuts** [comment]
I did not know about this option! It indeed looks like it should be fixed at the AC level, good catch

**Comment by brc-dd** [comment]
This is no longer reproducible in DocSearch v4. Although, the queries are still sent for intermediate input. Allowing some option to pass `ignoreCompositionEvents` would fix that but it was noticed in the implementation that Android keyboards don't behave smoothly with that enabled.
