### ISSUE TITLE
Certain pages return 0 records when indexed

### ISSUE THREAD

**Issue by axilleas** [algolia/docsearch#1305]
## Description

Certain pages return 0 records when indexed. I have found this with https://docs.gitlab.com/ee/administration/docs_self_host.html, but I'm not sure if there other pages as well.

![screenshot-crawler algolia com-2022 02 17-13_35_18](https://user-images.githubusercontent.com/340023/154483097-4e5173ad-6a2f-4c91-a3b3-9a08e225e790.png)

## Steps to reproduce

1. Go to https://docs.gitlab.com/
2. Search for `host the GitLab product documentation`
3. See that the page in question is not in the results https://docs.gitlab.com/ee/administration/docs_self_host.html

## Expected behavior

https://docs.gitlab.com/ee/administration/docs_self_host.html should appear under the search results. 

## Environment

Environment shouldn't matter as this is about the crawler.

**Comment by shortcuts** [comment]
Hey,

Looking at your crawler config, it seems to be related to this part we've added to stop crawling content L29

```
        const toCheck = [
          "This document was moved to",
          "This section is now merged into",
          "404 Not Found",
        ];
        const shouldStop = toCheck.some((text) => body.includes(text));
        if (shouldStop) {
          return [];
        }
```

It was parsed from out legacy but if it's not relevant anymore, feel free to edit it

**Comment by shortcuts** [comment]
Oh there's a `The version dropdown displays additional versions that don’t exist. Selecting these versions displays a 404 Not Found page.` in the DOM 😶‍🌫️
