### ISSUE TITLE
Search Result only showing one title

### ISSUE THREAD

**Issue by blee1170** [algolia/docsearch#131]
My search results only show one webpage title, if at all. I am using the stock CSS and js files but I can not get it to look like your example. 

Could it be a bug with the docsearch-scraper not indexing the page title as well? What do you need to help trouble shoot?

**Comment by maxiloc** [comment]
You can send an email to maxime at algolia dot com, with your APP_ID, I'll have a look

**Comment by blee1170** [comment]
I re-indexed my site and it seems to have fixed itself. I have been doing a lot of experimenting and figuring out how the indexing works, so I must have hit something caused the problem and was fixed now that I have it more understood.
