### ISSUE TITLE
Docsearch Integration with Community Algolia is buggy.

### ISSUE THREAD

**Issue by chriscalip** [algolia/docsearch#132]
At page https://community.algolia.com/instantsearch.js/ doing a search would yield 404 Page not found!
Screenshots attached.

![algolia-community-search](https://cloud.githubusercontent.com/assets/479454/17379666/08cef202-5989-11e6-908e-b72bc501af0f.png)
![algolia-community-search-error](https://cloud.githubusercontent.com/assets/479454/17379668/0d42cac0-5989-11e6-9358-26b9ec0d2201.png)

**Comment by maxiloc** [comment]
@chriscalip I don't manage to reproduce, you would mind to send a gif on how to reproduce

**Comment by chriscalip** [comment]
@maxiloc Key Event is pressing enter on the searchbox. The searchbox assumes people typing into the searchbox.. but i've been copying and pasting into the searchbox. Afterwards pressing the enter key you that error message.

Please check if you can reproduce .. ill do a screen grab to gif if you cant.

**Comment by maxiloc** [comment]
Ok I managed to reproduce, thanks for reporting

**Comment by maxiloc** [comment]
The instantsearch website is not using the docsearch frontend but a custom implem, I am closing this. An issue is open about this on the instantsearch.js repo
