### ISSUE TITLE
Cannot Prioritize Search Results via Configurations

### ISSUE THREAD

**Issue by praneesha** [algolia/docsearch#1336]
## Description

Even though the `lib.ballerina.io` is prioritized in the configurations as shown below,

```
 startUrls: [
    "https://lib.ballerina.io/",
    "https://ballerina.io/",
    "https://blog.ballerina.io/",
    "https://central.ballerina.io/",
  ],
```

they do not appear at all in the search results as shown below.

<img width="562" alt="Screen Shot 2022-03-24 at 8 13 35 PM" src="https://user-images.githubusercontent.com/11707273/159941870-f95a8183-af9e-4955-9cda-a9119ab2230c.png">

The `http` keyword is available in `lib.ballerina.io` in https://lib.ballerina.io/ballerina/http/2.2.1 and need to be prioritized in the search results. @shortcuts - Can you kindly help?

## Steps to reproduce

1. Go to `...`
2. Click on `...`
3. Scroll down to `...`

**Live reproduction:**

- JavaScript: https://codesandbox.io/s/github/algolia/docsearch/tree/next/examples/js-demo
- React: https://codesandbox.io/s/github/algolia/docsearch/tree/next/examples/demo

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- DocSearch version: [e.g. 3.0.0]

**Comment by shortcuts** [comment]
Hey, you can boost results for a paths using the `pageRank` option: https://docsearch.algolia.com/docs/record-extractor#boost-search-results-with-pagerank

**Comment by praneesha** [comment]
@shortcuts - Added an index as follows with the `pageRank` 1:

```
    {
      indexName: "ballerina api docs",
      pathsToMatch: ["https://lib.ballerina.io"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".content h1",
            content: ".content p, .content li",
            lvl0: {
              selectors: "",
              defaultValue: "api-docs",
            },
            lvl2: ".content h2",
            lvl3: ".content h3",
            lvl4: ".content h4",
            lvl5: ".content h5,.content h6",
            site: {
              defaultValue: ["ballerina_api_docs_grpc"],
            },
            tags: {
              defaultValue: ["ballerina_api_docs_grpc"],
            },
            pageRank: "1",
          },
          indexHeadings: true,
        });
      },
    },
```

But still the `lib.ballerina.io` results are not appearing in the search results.

But still, the `lib.ballerina.io`

**Comment by shortcuts** [comment]
> But still the lib.ballerina.io results are not appearing in the search results.

`pathsToMatch: ["https://lib.ballerina.io"]` will only match the `https://lib.ballerina.io` URL, if you want to also match sub ones, you need to add globs like `pathsToMatch: ["https://lib.ballerina.io/**"],`

> What is an index

It's where your Algolia records are stored, yours should be `ballerina`

> how many indexes can we have in the configuration?

As much as you want, but you can only query one from a single DocSearch instance. If you want to search all those URLs from a single DocSearch instance, I'd suggest you to implement a filtered search: 

1. Index content to use as filter (`tags` or `site` in your example) https://docsearch.algolia.com/docs/record-extractor#indexing-content-for-faceting 
2. Reflect it in your frontend: https://docsearch.algolia.com/docs/DocSearch-v3#filtering-your-search

**Comment by udda1996** [comment]
Hi, we have included globs in URLs. But still lib.ballerina.io results not getting appended  in the search results. 
```
{
      indexName: "ballerina api docs",
      pathsToMatch: ["https://lib.ballerina.io**/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".content h2",
            content: ".content p, .content li",
            lvl0: {
              selectors: "",
              defaultValue: "api-docs",
            },
            lvl2: ".content h3",
            lvl3: ".content h4",
            lvl4: ".content h5",
            lvl5: ".content h6,.content h7",
            site: {
              defaultValue: ["ballerina_api_docs"],
            },
            tags: {
              defaultValue: ["ballerina_api_docs"],
            },
            pageRank: "1",
          },
          indexHeadings: true,
        });
      },
    }```

But for test runs in URL tester in Algolia crawler, we get matching records for the URL https://lib.ballerina.io/

<img width="595" alt="Screenshot 2022-04-19 at 14 07 28" src="https://user-images.githubusercontent.com/66210480/163961537-0a31f676-121a-498c-bf2a-a9f6cfe5a98d.png">

**Comment by shortcuts** [comment]
Hey, if your frontend searches in the index `ballerina`, you also need to fix it on the config side (here you have `ballerina api docs`).

**Comment by udda1996** [comment]
> Hey, if your frontend searches in the index `ballerina`, you also need to fix it on the config side (here you have `ballerina api docs`).

This worked for me. Thanks a lot for the guidance.

**Comment by praneesha** [comment]
We have the config below.

  ```
  {
      indexName: "ballerina",
      pathsToMatch: ["https://lib.ballerina.io**/ballerinax/**/latest/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".content h1",
            content: ".content p, .content li",
            lvl0: {
              selectors: "",
              defaultValue: "API Docs",
            },
            lvl2: ".content h2",
            lvl3: ".content h3",
            lvl4: ".content h4",
            lvl5: ".content h5,.content h6",
            site: {
              defaultValue: ["ballerinax_api_docs"],
            },
            tags: {
              defaultValue: ["ballerinax_api_docs"],
            },
            pageRank: "2",
          },
          indexHeadings: true,
        });
      },
    },
```

Some URLs of this config work fine in the URL tester but don't appear on the website search.

@shortcuts - What could be the reason? Appreciate your kind help on this, please.

**Comment by praneesha** [comment]
@shortcuts - Any help on the above, please?
