### ISSUE TITLE
error: apply algolia cors

### ISSUE THREAD

**Issue by MShineRay** [algolia/docsearch#1343]
## Description
https://docsearch.algolia.com/apply/

error: 
Access to fetch at 'https://docsearch-hub.herokuapp.com/form/inbound' from origin 'https://docsearch.algolia.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
7018353f.5facab56.js:50          POST https://docsearch-hub.herokuapp.com/form/inbound net::ERR_FAILED

**Comment by shortcuts** [comment]
Hey, we are doing maintenance work on our server so it is indeed not reachable for now, I'll ping here once it's finished

**Comment by shortcuts** [comment]
Maintenance done!

**Comment by markmcsong** [comment]
I met this problem again 😂 @shortcuts

**Comment by shortcuts** [comment]
@levimichael @dylantientcheu was there any maintenance ongoing on the docsearch hub? 🥶
