### ISSUE TITLE
[question] Crawler: the status is idle

### ISSUE THREAD

**Issue by leedom92** [algolia/docsearch#1348]
## Description

**the status is idle and there is no any record, it just notices `Waiting for the next scheduled crawl...`**
**what should I do? just wait for the next scheduled crawl?**

![algolia2](https://user-images.githubusercontent.com/30711792/161413700-807e6dcd-278b-4eb3-bf0b-cb25cee04b73.png)

![algolia](https://user-images.githubusercontent.com/30711792/161413439-97e96814-e95a-4691-9955-6ad29d2a89b6.png)

**Comment by bodinsamuel** [comment]
Hello,
you have the control over the extraction. If there is no record that means the crawler did not find anything based on your configuration.
You can go to https://crawler.algolia.com/admin/crawlers/00cd3512-bd0e-4f79-9682-17a7f43d38ea/configuration/edit and test URLs.
In your case it seems the class `.content__default` does not exists so nothing matches.

Hope this helps,
Best regards

**Comment by leedom92** [comment]
@bodinsamuel 
Thanks for your tips, I have resolved the problem. 
BTW, there is a new problem that I can find results in Crawler's Editor with Search Preview, but there's no result in my website. And there's a notification in  Search Preview.
`Your index settings have changed since last crawl, you should delete your index before starting a new crawl. Go to the Overview page to start a new crawl.`

![algolia3](https://user-images.githubusercontent.com/30711792/161466795-3bb96f35-a5e9-4d92-8379-555bb44870f8.png)

How can I solve this problem? Please give me a hand, thank you very much!

![algolia4](https://user-images.githubusercontent.com/30711792/161466788-b2b0ce7a-e958-4fae-957d-25a8c77653f8.png)

![algolia5](https://user-images.githubusercontent.com/30711792/161466787-e7d20681-d03c-4c3e-be4f-caad8582d185.png)

**Comment by shortcuts** [comment]
Hey @leedom92

> And there's a notification in Search Preview.

`index settings` are set are index creation time (the first time we crawl your website), you need to either:
- delete your index [from this page](https://www.algolia.com/apps/ALTS7M1QY7/explorer/browse/leedom) and start a new crawl
- manually set the `attributesForFaceting` of your config [here](https://www.algolia.com/apps/ALTS7M1QY7/explorer/configuration/leedom/facets)

(1 should be easiest :D)

Have a great day!

**Comment by leedom92** [comment]
@shortcuts thank u so much!!! It works!!!
