### ISSUE TITLE
Possibility to share @algolia/ui-library typescript sources

### ISSUE THREAD

**Issue by Emanuel-Allely** [algolia/docsearch#1350]
Hi there! We really love DocSearch and DocSearch website! It is open-source (thanks) but we can't really use it in production because we just have access to compiled style library. Is it possible to have the typescript sources of @algolia/ui-library ? Without it we have to redesign everything from MUI 😢 It could be really helpful 🙏

**Comment by shortcuts** [comment]
Hey, `@algolia/ui-library` is only used for our documentation website, but not for the DocSearch component.

Do you have more information on the issue you are encountering?

**Comment by Emanuel-Allely** [comment]
Thanks for your answer. Yes, we get inspiration from your documentation website and would like to use the same styles as Docsearch docs. We are building docs on Docusaurus too, and we saw your open-source website in the Docusaurus Showcase. I know it's not an issue related to the core technology of Docsearch but, it would be so helpful to get sources of @algolia/ui-library.

**Comment by shortcuts** [comment]
Hey, the package is available publicly on NPM https://www.npmjs.com/package/@algolia/ui-library and a Storybook if you need some doc. However, the repository is indeed private, sorry!
