### ISSUE TITLE
Custom html for button search

### ISSUE THREAD

**Issue by green-cats** [algolia/docsearch#1351]
## Describe the problem
Can I render custom html for search button?

## Describe the solution
it would be cool if there was a render function returning custom html

**Comment by jxxe** [comment]
It doesn't appear that this is possible. What I resorted to is using CSS to hide the button that Algolia creates and adding my own. You can call the `.click()` method on their HTML element to open the modal.

```js
document.querySelector('.DocSearch-Button').click();
```
