### ISSUE TITLE
The Algolia Crawler is blocked and we are unable to view the related details

### ISSUE THREAD

**Issue by RukshiW** [algolia/docsearch#1352]
## Description

The  crawler of the application `TYOC0645HN` is currently blocked with this description.

"Too many missing records
The new index generated by this crawl is missing too many records to replace the production index automatically"

We are currently unable to find the reason for this because none of the members are able to view the current plan we are using or the billing information associated with the account/plan.

Can you please help us to find the reason this crawler is blocked and what is required to reactivate it?

**Comment by shortcuts** [comment]
Hey

You can click the `replace production index` button with the new records to apply the changes.

We are receiving 403 errors when crawling your website, you probably need to add the crawler UA to your robots.txt: `Algolia Crawler`

**Comment by shortcuts** [comment]
> And I looked for robots.txt files in both TYOC0645HN and N331AC1IYR (Index name(s) wso2 & wso2_choreo) and we haven't published a robots.txt in our doc spaces

Indeed, robots.txt looks good. Do you have a rate limit in place? It seems that we've hit it which blocked our Crawler IP.

**Comment by tmkasun** [comment]
Hi @shortcuts ,

Thanks, We will check the Cloudflare configs from our side.

**Comment by tmkasun** [comment]
Hi @shortcuts ,

Can you please give me the IP range or DNS  pattern that Algolia crawlers use ? so that I can check the proxy logs and set the relevant proxy rules?

**Comment by bodinsamuel** [comment]
Hello @tmkasun 

We are supposedly already allowlisted by Cloudflare, I'm reaching out to them to confirm.
Our IPs are listed there. https://crawler.algolia.com/ips.txt

**Comment by tmkasun** [comment]
Hi @bodinsamuel & @shortcuts 

Thanks all for your help, We were able to resolve the crawling issue after reviewing and modifying our Cloudflare configs.

Thanks
~Kasun
