### ISSUE TITLE
Extractors returned too many records or exceeded memory limit

### ISSUE THREAD

**Issue by axilleas** [algolia/docsearch#1357]
## Description

:wave: we have some big pages that Algolia fails to index. In the crawler's page, I see:

Returned too many records:

- https://docs.gitlab.com/ee/api/projects.html
- https://docs.gitlab.com/charts/charts/globals.html
- https://docs.gitlab.com/ee/api/integrations.html
- https://docs.gitlab.com/charts/installation/version_mappings.html
- https://docs.gitlab.com/ee/user/feature_flags.html
- https://docs.gitlab.com/ee/ci/yaml/

Exceeded memory limit:

- https://docs.gitlab.com/ee/api/graphql/reference/

---

Is there anything we can do apart from making those pages smaller? Thanks!

**Comment by axilleas** [comment]
And as I submitted this, I found https://docsearch.algolia.com/docs/record-extractor#reduce-the-number-records! This must have been added recently.

**Comment by axilleas** [comment]
I tried adding `aggregateContent: true,`, but the issue persists.

**Comment by bodinsamuel** [comment]
Thanks for the thorough report.
As you probably already guess, your pages are quite big, even from an UX perspective it's not easy to navigate in those. 

I'll try to look at possible improvements, especially with table rows that do not needs to be indexed separately. 
In the meantime I have increased your limit to 1000 records per URL.

**Comment by axilleas** [comment]
Thank you! Let's close this one. We will track this in our issue tracker https://gitlab.com/gitlab-org/gitlab-docs/-/issues/1137

**Comment by bodinsamuel** [comment]
NB: we have deployed a fix to improve memory usage on big pages, you should not see the `exceeded memory limit` error. 

However it does not fix the number of records.
In possible improvements:
```js
recordProps: {
            lvl1: ".article-content h1",
            content:
              ".article-content p",
            lvl0: {
              selectors: ".article-content h1",
              defaultValue: "Documentation",
            },
            lvl2: ".article-content h2",
            lvl3: ".article-content h3",
            lvl4: ".article-content h4",
            lvl5: ".article-content h5",
            product: {
              defaultValue: "GitLab",
            },
            tags: {
              defaultValue: ["gitlab"],
            },
          },
```

This version removes most of the "superfluous" content and is below 4k records. Still quite big but we could allow it temporarily while you find a solution ☺️

**Comment by axilleas** [comment]
@bodinsamuel thanks! This means we'll be giving up `.article-content li`, `.article-content td:last-child`, `.article-content pre.highlight code`. As far as I can tell, we use those classes to tell Algolia to index lists, tables, and code. Is that right?
