### ISSUE TITLE
Facetfilter not working

### ISSUE THREAD

**Issue by isharailanga** [algolia/docsearch#1358]
## Description

`Facetfilters` are configured in the Crawler but they are not shown in the search preview tab.

## Steps to reproduce

I have configured the facet filters for my crawler as follows:

```
      recordExtractor: ({ helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ["header h1", "article h1", "main h1", "h1", "head > title"],
            content: ["article p, article li", "main p, main li", "p, li"],
            lvl0: {
              selectors: "",
              defaultValue: "Documentation",
            },
            lvl2: ["article h2", "main h2", "h2"],
            lvl3: ["article h3", "main h3", "h3"],
            lvl4: ["article h4", "main h4", "h4"],
            lvl5: ["article h5", "main h5", "h5"],
            lvl6: ["article h6", "main h6", "h6"],
            language: {
              defaultValue: "en",
            },
            version: {
              defaultValue: ["latest", "1.0.0"],
            },
          },
        });
      },
```

But in the Crawler preview, they are not available.
<img width="1340" alt="Screenshot 2022-04-15 at 12 49 08" src="https://user-images.githubusercontent.com/14251853/163538409-0efb8b45-506a-4740-bdfd-5abeb3bab92b.png">

I followed your documentation at https://docsearch.algolia.com/docs/record-extractor/#with-custom-variables.
Am I missing something?

**Live reproduction:**

- https://crawler.algolia.com/admin/crawlers/e2d05113-0207-4e6a-b72a-c8f43a769b4d/configuration/edit

**Comment by shortcuts** [comment]
Hey, the index settings are set at index creation time to avoid overriding the dashboard ones. If you'd like to apply them from the config, you can delete your index and start a new crawl.

**Comment by isharailanga** [comment]
Hllo, thanks for getting back. You mean I need to create a new crawler? Or rerun the existing crawler?

**Comment by shortcuts** [comment]
The crawler only retrieve data from your website to put it in an Algolia index, here you need to delete the index: `berlin-ob-docs-wso2` from this page: https://www.algolia.com/apps/N184S8JQLZ/explorer/browse/berlin-ob-docs-wso2

**Comment by isharailanga** [comment]
should I request algolia to create a new index for me? or can I do that using the editor?

**Comment by shortcuts** [comment]
1. You delete the index from this page https://www.algolia.com/apps/N184S8JQLZ/explorer/browse/berlin-ob-docs-wso2
2. You start a new crawl from this page https://crawler.algolia.com/admin/crawlers/e2d05113-0207-4e6a-b72a-c8f43a769b4d/overview

And the search will work as expected :)
