### ISSUE TITLE
UI improvement of the "used by" homepage's section

### ISSUE THREAD

**Issue by seafoox** [algolia/docsearch#136]
A suggestion of UI that improves the way how "popular website using DocSearch" are featured.

![docsearch](https://cloud.githubusercontent.com/assets/1101220/17886735/79d53a7a-6923-11e6-85fc-43fc42074f61.png)

Additionally to the new layout, I suggest we should also update the wording.

**Comment by s-pace** [comment]
Updated thanks to  #192
