### ISSUE TITLE
Algolia Crawler shows zero records

### ISSUE THREAD

**Issue by RumeelHussainbnb** [algolia/docsearch#1366]
Hi,
I added the search bar configurations as specified on the [Docusaurus official page.](https://docusaurus.io/docs/search#connecting-algolia) I have also added the CSS and JavaScript snippets provided by the Algolia team in the index.html file. However, no search records are displayed when the search bar is used for searching content on the website. Also, the crawlers result in no records, i.e. no data records are being fetched. PFA screenshot of the same. Please let me know if any additional settings are required other than the ones specified on the Docusaurus page.

 **URL of website:** https://docs.bnbchain.world/
![image](https://user-images.githubusercontent.com/93580180/163773889-dc914740-2fd6-4f2f-8ae5-009a28fa2031.png)
![image](https://user-images.githubusercontent.com/93580180/163773922-5237d872-b31d-4408-8715-49e5d6bea9f2.png)

**Comment by shortcuts** [comment]
Is your config matching the DocSearch one?

**Comment by RumeelHussainbnb** [comment]
Below is the auto generated crawler for the docusearch app.


new Crawler({
  rateLimit: 8,
  startUrls: ["https://docs.bnbchain.world/"],
  renderJavaScript: false,
  sitemaps: [
    "https://docs.bnbchain.world/sitemap.xml",
    "https://docs.bnbchain.world//sitemap.xml",
  ],
  ignoreCanonicalTo: true,
  discoveryPatterns: ["https://docs.bnbchain.world/**"],
  schedule: "at 1:17 PM on Friday",
  actions: [
    {
      indexName: "bnbchain",
      pathsToMatch: ["https://docs.bnbchain.world/**"],
      recordExtractor: ({ $, helpers }) => {
        // priority order: deepest active sub list header -> navbar active item -> 'Documentation'
        const lvl0 =
          $(
            ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
          )
            .last()
            .text() || "Documentation";
        return helpers.docsearch({
          recordProps: {
            lvl0: {
              selectors: "",
              defaultValue: lvl0,
            },
            lvl1: "header h1",
            lvl2: "article h2",
            lvl3: "article h3",
            lvl4: "article h4",
            lvl5: "article h5, article td:first-child",
            lvl6: "article h6",
            content: "article p, article li, article td:last-child",
          },
          aggregateContent: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    bnbchain: {
      attributesForFaceting: [
        "type",
        "lang",
        "language",
        "version",
        "docusaurus_tag",
      ],
      attributesToRetrieve: [
        "hierarchy",
        "content",
        "anchor",
        "url",
        "url_without_anchor",
        "type",
      ],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
  appId: "REMOVED  FOR CONFIDENTIALITY ",
  apiKey: " REMOVED FOR CONFIDENTIALITY ",
});

**Comment by RumeelHussainbnb** [comment]
Also every time I test run the crawler I get the same "No records Extracted" message. 
![image](https://user-images.githubusercontent.com/93580180/163796680-dd9d1ded-88e3-413c-8d8a-b8916c00a8d7.png)

**Comment by shortcuts** [comment]
Hey, the config indeed look good and the docusaurus options too.

I've added the `https://docs.bnbchain.world/docs/bnbIntro` link to your `startUrls` to give a small hint to the crawler and restarted a crawled, which fixed your issue.

> Also every time I test run the crawler I get the same "No records Extracted" message.

We don't extract records on sitemaps URLs, but you can try with `https://docs.bnbchain.world/docs/bnbIntro`

Enjoy :)
