### ISSUE TITLE
Document how to use resultsFooterComponent

### ISSUE THREAD

**Issue by sarahg** [algolia/docsearch#1368]
We're attempting to add a results count footer link, like Docusaurus:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/667501/164754398-27e4298c-76c3-491c-bb28-b47fa10edbf4.png">

I see a `resultsFooterComponent` was added to docsearch here: https://github.com/algolia/docsearch/commit/9eaf18a81ffff04b7fb8d8389463b56d823f7e9d

Unfortunately I'm having a hard time figuring out how to utilize this on a vanilla JS docsearch implementation. These come close, but not quite:

https://codesandbox.io/s/resultsfooter1-v0yryx?file=/src/index.js (HTML is escaped, breaking the link)
https://codesandbox.io/s/resultsfooter2-vofbfk?file=/src/index.js (we have HTML for the link! but how do we get text in there?) 

We'd like to include the result count in the link as well. 

Can anyone clarify how to use this? Thank you!

**Comment by shortcuts** [comment]
Hey! Oops it should indeed be documented. I've made those sandboxes in the meantime.

[`resultsFooterComponent`](https://github.com/algolia/docsearch/blob/next/packages/docsearch-react/src/DocSearch.tsx#L37-L39) provides the current `state` ([type definition](https://github.com/algolia/autocomplete/blob/next/packages/autocomplete-core/src/types/AutocompleteState.ts)) and wants a `JSX.Element` in return. 

For React (or JSX), you can simple do something like this: ([sandbox](https://codesandbox.io/s/docsearch-v3-resultsfootercomponent-wzie9y))

```jsx
<DocSearch
  // ...
  resultsFooterComponent={({ state }) => {
    return <h1>{state.context.nbHits} hits found</h1>;
  }}
/>
```

Or in Vanilla JS (without using the `createElement` API, or JSX): ([sandbox](https://codesandbox.io/s/docsearch-v3-resultsfootercomponent-without-jsx-jperd5))

```js
docsearch({
  // ...
  resultsFooterComponent({ state }) {
    return {
      // The HTML `tag`
      type: "a",
      ref: undefined,
      constructor: undefined,
      key: undefined,
      // Its props
      props: {
        href: "https://docsearch.algolia.com/apply",
        target: "_blank",
        onClick: (event) => {
          console.log(event);
        },
        // Raw text rendered in the HTML element
        children: `${state.context.nbHits} hits found!`
      },
      __v: null
    };
  }
});
```

**Comment by sarahg** [comment]
This works great! The only thing I changed for our non-React implementation was to set the `key` property with `state.query` as the value so that the component will refresh as the search query changes. I created a [PR](https://github.com/algolia/docsearch/pull/1379) to add these examples to the DocSearch docs. Thanks for your help!

**Comment by shortcuts** [comment]
Thanks for letting us know :D Enjoy!

**Comment by wilhelmer** [comment]
I tried this yesterday and also had a hard time implementing it.

First of all, since you typically want to send the search query over to the search results page, the `href` entry in the example should demonstrate how to do that. Something like this:

```js
docsearch({
  // ...
  resultsFooterComponent({ state }) {
    return {
      // The HTML `tag`
      type: "a",
      ref: undefined,
      constructor: undefined,
      key: state.query,
      // Its props
      props: {
        href: `/search.html?q=${state.query}`,
        target: "_blank",
        onClick: (event) => {
          console.log(event);
        },
        // Raw text rendered in the HTML element
        children: `${state.context.nbHits} hits found!`
      },
      __v: null
    };
  }
});
```

Then, of course, you have to build a search results page, which is completely undocumented. I guess that if you are using Docusaurus, you get this more or less out of the box? Anyway, I'm not using Docusaurus, so I had to start from scratch here.

I managed to build a search results page using InstantSearch components, but that felt kinda weird / non-intuitive since you have to deal with a totally different product that's not advertised as a part of Docsearch. 

I think there should at least be a hint in the docs that you need a search results page and that it's okay to use Algolia's InstantSearch components for that.

**Comment by wilhelmer** [comment]
For what it's worth, here's my sample implementation:

**JavaScript integration**

```js
init() {
    // Init DocSearch
    const appId = "XXX";
    const apiKey = "12345abc";
    docsearch({
        container: "#mycontainer",
        appId,
        indexName: "myindex",
        apiKey,
        resultsFooterComponent({ state }) {
            return {
                type: "a",
                ref: undefined,
                constructor: undefined,
                key: state.query,
                props: {
                    href: `/search.html?q=${state.query}`,
                    children: `See all ${state.context.nbHits} results`
                },
                __v: null
            };
        }
    });
    // Also init Algolia InstantSearch, if available (for search results page)
    if (typeof algoliasearch != "undefined" && typeof instantsearch != "undefined") {
        const { algoliasearch, instantsearch } = window;

        const searchClient = algoliasearch(appId, apiKey);
        const indexName = "myindex";

        const search = instantsearch({
            searchClient,
            indexName,
            routing: {
                stateMapping: {
                    stateToRoute(uiState) {
                        const indexUiState = uiState[indexName];
                        return {
                            q: indexUiState.query,
                        }
                    },
                    routeToState({q}) {
                        return {
                            [indexName]: {
                                query: q,
                            },
                        };
                    },
                },
            }
        });

        search.addWidgets([
            instantsearch.widgets.searchBox({
                container: '#searchbox',
            }),
            instantsearch.widgets.hits({
                container: '#hits',
                templates: {
                    item(hit, { html, components, sendEvent }) {
                        return html`
                <div>
                    <p class="ais-Heading"><a href="${hit.url}">${hit.hierarchy.lvl2 ? hit.hierarchy.lvl2 : hit.hierarchy.lvl1}</a></p>
                    <p>${components.Highlight({ hit, attribute: 'content' })}</p>
                    <p class="ais-Breadcrumbs">${hit.hierarchy.lvl0}: ${hit.hierarchy.lvl1} ${hit.hierarchy.lvl2 ? "> " + hit.hierarchy.lvl2 : ""}</p>
                </div>
                `;
                    },
                },
            }),
            instantsearch.widgets.configure({
                hitsPerPage: 8,
                facetFilters: [`lang:${currentLang}`],
                queryLanguages: [currentLang]
            }),
            instantsearch.widgets.pagination({
                container: '#pagination',
            }),
        ]);

        search.start();
    }
}
```

**Search results page**

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@7.4.5/themes/satellite-min.css">

<div class="ais-InstantSearch">
  <div class="right-panel">
    <div id="searchbox"></div>
    <div id="hits"></div>
    <div id="pagination"></div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4.14.2/dist/algoliasearch-lite.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4.49.1/dist/instantsearch.production.min.js"></script>
```
