### ISSUE TITLE
Class name ".searchbox" is too generic

### ISSUE THREAD

**Issue by alexandremeunier** [algolia/docsearch#137]
Currently the generated styles use a `.searchbox` class name. This is very generic and can (does, actually) lead to conflicts with existing styles.

Would it be possible to namespace it ? For instance, `.docsearch-searchbox`.

**Comment by LukyVj** [comment]
Agree, but I would setup a short namespace : 
from `.docsearch-searchbox` to `.ds-searchbox`

WDYT
