### ISSUE TITLE
Add a autocomplete.js source compliancy

### ISSUE THREAD

**Issue by redox** [algolia/docsearch#138]
In order to embed the DocSearch results in a more-advanced autocomplete.js implementation.

**Comment by pixelastic** [comment]
@redox Would you remember what you meant by "autocomplete.js source compliancy". Sorry it took us so long to acknowledge this issue!

**Comment by s-pace** [comment]
I think he meant to be able to search through other DocSearch indices from one UI.

It is something we wanted to avoid since the relevancy might be a bit intricate. We wanted to advocate for using one index with facets / specifics `selectors_key` instead.

**Comment by pixelastic** [comment]
> Long story short: how to build a autocompletion dropdown menu with both the DocSearch content & some other content coming from other indices.

I like this idea. I would lean toward re-using what we already have in InstantSearch and the multi index search for that though. Maybe a dropdown IS widget that could wrap some hits widget?

**Comment by Shipow** [comment]
Solved with autocomplete V1. We'll introduce guides on DocSearch documentation.
