### ISSUE TITLE
Recent Searches is always empty on laravelshopper.dev

### ISSUE THREAD

**Issue by mckenziearts** [algolia/docsearch#1382]
## Description

We are using the latest alpha version of @docsearch/js and recent searches are never updated. I had an older version of the doc available in another domain name. Now I changed the domain but the index results remain the same. And yet the old version is no longer available

## Steps to reproduce

1- Go to https://laravelshopper.dev/
2- Search for anything
3- Search as many more times as you want and you'll never see anything in the Recent Searches modal.

## Expected behavior

Like other sites using the same version (TailwindCSS.com for example), I'd expect to see that list update.

## Environment

- OS: All
- Browser: All
- DocSearch version: 3
- Project Repo: https://github.com/shopperlabs/laravelshopper.dev
- Implementation: https://github.com/shopperlabs/laravelshopper.dev/blob/main/resources/js/app.js#L19-L36

**Comment by shortcuts** [comment]
Hey, it seems to be related to https://github.com/algolia/docsearch/issues/1223

I did not found the issue at first but your environment looks similar, do you use the cache elsewhere?

**Comment by shortcuts** [comment]
I'm closing to avoid multiple discussions, if you think it's a different issue feel free to re-open
