### ISSUE TITLE
Search results show unexpected behavior 

### ISSUE THREAD

**Issue by udda1996** [algolia/docsearch#1383]
## Description

Following are the configs that we have used in the crawler. 

```
{
    indexName: "ballerina",
    pathsToMatch: ["https://lib.ballerina.io**/ballerinax/**/latest/**"],
    recordExtractor: ({ $, helpers }) => {
      return helpers.docsearch({
        recordProps: {
          lvl1: ".content h1",
          content: ".content p, .content li",
          lvl0: {
            selectors: "",
            defaultValue: "API Docs",
          },
          lvl2: ".content h2",
          lvl3: ".content h3",
          lvl4: ".content h4",
          lvl5: ".content h5,.content h6",
          site: {
            defaultValue: ["ballerinax_api_docs"],
          },
          tags: {
            defaultValue: ["ballerinax_api_docs"],
          },
          pageRank: "2",
        },
        indexHeadings: true,
      });
    },
  },
 ```

After crawling some URLs hits records as expected in the URL Tester (e.g., `https://lib.ballerina.io/ballerinax/rabbitmq/latest `) but results do not show up at the web search. 

![image](https://user-images.githubusercontent.com/66210480/165912062-6c48b0a4-3754-4631-a4d9-9b44d51a97dc.png)

## Steps to reproduce

1. Go to https://ballerina.io/
2. Search for `rabbitmq` in the search bar. 
3. Here you don't get to see any search result under `BallerinaX API docs`
4. Then search for `mssql` in the search bar and we can see results under `BallerinaX API docs`

**Comment by shortcuts** [comment]
Hey, looking at your index I can see a few reasons why this could happen

**Index side**
Considering the number of records of your index (+50k), it can be hard to find single word search results. I've added the [`aggregateContent`](https://docsearch.algolia.com/docs/record-extractor/#aggregatecontent) option to remove a bit of noise in the results, which reduced the total records to ~8k.

**More precise selectors**
Your `lvl1` (`h1`) selector also retrieves the `listbox` with all versions, so the record contains `ballerinax/rabbitmq2.2.12.2.12.2.02.1.02.0.12.0.01.1.0-beta.21.1.0-beta.11.1.0-alpha9.1`, you could add something like `$('[role="listbox"]').remove();` at the beginning of your `action`s to only retrieve the `ballerinax/rabbitmq` content.

**Comment by udda1996** [comment]
Hi @shortcuts, thank you for the explainatin. Removing the `listbox` was successful, but still we have an issue regarding search results. For example we have 2 different https://lib.ballerina.io pages with two h1 s as [ballerinax/rabbitmq](https://lib.ballerina.io/ballerinax/rabbitmq/latest#main) and [ballerinax/kafka](https://lib.ballerina.io/ballerinax/kafka/latest#main). When we search with the keywords [1] `rabbitmq` and [2] `kafka`, we get following results. 

[1]
<img width="585" alt="Screenshot 2022-04-29 at 21 25 13" src="https://user-images.githubusercontent.com/66210480/165981708-8909a947-0ef7-4996-b6aa-b85b80684f34.png">

[2]
<img width="580" alt="Screenshot 2022-04-29 at 21 27 25" src="https://user-images.githubusercontent.com/66210480/165981769-aae8f03b-72a9-47db-a528-f8d51054eee4.png">

Here in [1] we get `BallerinaX API docs` results at the top whereas [2] we don't get any `BallerinaX API docs` results. Any idea what causes this?

**Comment by shortcuts** [comment]
Closing at the error seems resolved, enjoy :)
