### ISSUE TITLE
Unable to create a new index

### ISSUE THREAD

**Issue by axilleas** [algolia/docsearch#1392]
:wave: 🙂 I tried creating a [new index](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/how-to/importing-from-the-dashboard/#creating-a-new-index), because we want to try some things out without affecting our production environment, but it failed with the message "Failed to create index.".

Is this a limitation to the free DocSearch service, or is this a bug? I guess I wouldn't be able to access the dialog to create the index in the first place if this was a limitation :thinking: 

Thanks!

**Comment by sarahg** [comment]
HelIo Algolia team, I work on the same project as @axilleas and ran into a similar permissions issue when trying to use the UI Demo feature:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/667501/170501837-8570ff51-3b86-4361-b105-a498e00eeb4d.png">

Same question here -- is this a limitation of our DocSearch service, or a bug? 

Ultimately what we're trying to do here is implement a version-specific search via facets, but we'd like to be able to test/experiment without possibly disrupting our production site. Thanks!

**Comment by shortcuts** [comment]
Hey @sarahg, @axilleas!

> Is this a limitation to the free DocSearch service, or is this a bug?

It is indeed a limitation of the DocSearch program, we require the indexing to be done via the Crawler directly. We should however indeed improve the error message/add a small doc about it.

You are still allowed to create new indices, directly from the Crawler UI by either:
- Creating a new Crawler
- Adding an object to the `actions` element of your current Crawler config, that targets an other `indexName` (it will be automatically created after a successful crawl)

We however restrict API keys to the initially submit index but add a wildcard to it (e.g. `gitlab` is allowed to create index matching the `gitlab*` pattern, `gitlab_demo`, `gitlab_staging`, etc.) 

> Ultimately what we're trying to do here is implement a version-specific search via facets

It's definitely possible via the Crawler itself, and will be closer to what you'd like to achieve ultimately, let me know if you need help with it!

**Comment by bodinsamuel** [comment]
The UI issues are a bit unrelated to DocSearch. You simply don't have the permissions to execute those actions and the dashboard should be clearer on this. Maybe some buttons should be in locked state or error messages a bit more explicit cc @alexandremeunier 

--- 

> Ultimately what we're trying to do here is implement a version-specific search via facets, but we'd like to be able to test/experiment without possibly disrupting our production site. Thanks!

I would recommend creating a second crawler (copy pasting the config) with a different index name to achieve this. 
NB: we have an issue right now that prevents creating a second crawler, you just need to copy paste the ApiKey from the main crawler into the advanced fields (in the creation form)

**Comment by axilleas** [comment]
Thanks @shortcuts and @bodinsamuel! I was able to create a new crawler!
