### ISSUE TITLE
Expected server HTML to contain a matching <kbd> in <span>

### ISSUE THREAD

**Issue by IanVS** [algolia/docsearch#1398]
## Description

I'm seeing a dev console warning that seems to be related to https://github.com/algolia/docsearch/pull/1335:

```
Warning: Expected server HTML to contain a matching <kbd> in <span>.
    at kbd
    at span
    at button
    at http://localhost:3000/node_modules/.vite/deps/@docsearch_react.js?v=db2f8ae7:109:32
    at DocSearch (http://localhost:3000/node_modules/.vite/deps/@docsearch_react.js?v=db2f8ae7:4512:48)
```

I'm using Astro, which does SSR, which is what this warning seems to be about.

## Steps to reproduce

I'll try to work on a reproduction, but it might take a bit.

## Expected behavior

I expect not to see a warning message.

## Environment

- OS: macOS
- Browser: All
- DocSearch version: 3.1.0

**Comment by colinking** [comment]
We're also hitting this issue. FWIW, this appears to be the same issue as https://github.com/algolia/docsearch/issues/1242. You get the error message from that thread if you try this with v3.0.0.

**Comment by shortcuts** [comment]
This should be fixed by https://github.com/algolia/docsearch/pull/1384 for production build at least
