### ISSUE TITLE
How do you upgrade from v1 to v2?

### ISSUE THREAD

**Issue by vishr** [algolia/docsearch#140]
I have searched repo and docs but could not find any information.

**Comment by s-pace** [comment]
Do you want to update your configuration?

**Comment by redox** [comment]
> Do you want to update your configuration?

I think @vishr is asking about to procedure to move from `/1/docsearch.min.{css,js}` to `/2/docsearch.min.{css,js}`, right?

**Comment by s-pace** [comment]
This is what makes more sense but I want to avoid any confusion.

@vishr Let us know how we could help you solving this issue.

**Comment by vishr** [comment]
It has been a year I raised this issue but probably `/1` to `/2` as @redox mentioned.
