### ISSUE TITLE
[QUESTION] All page has been ignored.

### ISSUE THREAD

**Issue by 3lang3** [algolia/docsearch#1410]
Hi~

My open source project applied for doc search, but the page was not retrieved (ignored). I provided the sitemap.xml file.

The website is deployed using gh-pages services, in order to make react router work properly, I make 404.html and index.html file content consistent, I think it may be the problem? But I have seen other websites use the same strategy and doc search work properly (eg: https://mobile.ant.design/zh).

How can I solve this situation?

my site: https://react-vant.3lang.dev/

- DocSearch version: v3

**Comment by 3lang3** [comment]
![企业微信20220609-133051](https://user-images.githubusercontent.com/7098719/172780781-0c50ea1d-5294-4567-842b-4cb4271a06ae.png)

**Comment by shortcuts** [comment]
Hey, from what I've tried it seems to come from your website, I've been able to reproduce from the browser.

If you navigate to https://react-vant.3lang.dev/guide/quickstart for example, the page will return `404` on load, while displaying correctly. As we follow those status code in our crawler, we will ignore the fact that it renders and throw the error.

**Comment by 3lang3** [comment]
> Hey, from what I've tried it seems to come from your website, I've been able to reproduce from the browser.
> 
> If you navigate to https://react-vant.3lang.dev/guide/quickstart for example, the page will return `404` on load, while displaying correctly. As we follow those status code in our crawler, we will ignore the fact that it renders and throw the error.

What should I do? 😢

**Comment by 3lang3** [comment]
https://docsearch.algolia.com/docs/integrations/#our-great-integrations

I think my site make up like dumi

**Comment by bodinsamuel** [comment]
Please contact Dumi support to solve this issue, we'll be happy to answer your DocSearch related question ☺️ 
<img width="794" alt="Screenshot 2022-06-09 at 11 23 31" src="https://user-images.githubusercontent.com/1637651/172813733-0504173a-2975-4360-a45d-80807ef1cdf9.png">
