### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [algolia/docsearch#142]
Hello @redox
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I want to confirm with you about the main file need to be grab on [npm](https://www.npmjs.com/package/docsearch.js).
I found that there is a `dist/` folder.
But are all of files under `dist/` needed to be grab?
I think all the main files are under `dist/cdn/`.
What about the files under `dist/npm/`?
Please help me confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8297

**Comment by vvo** [comment]
Hi @kennynaoh, you only need dist/cdn/* see http://www.jsdelivr.com/projects/docsearch.js for the file list.

**Comment by kennynaoh** [comment]
Thanks @vvo
