### ISSUE TITLE
Uncaught TypeError: t is null

### ISSUE THREAD

**Issue by tdb-alcorn** [algolia/docsearch#1420]
## Description

I followed the steps to install Algolia on my website but search is not working. I'm seeing an error in the JS console

```
Uncaught TypeError: t is null
    De https://cdn.jsdelivr.net/npm/@docsearch/js@3:8
    <anonymous> https://cdn.jsdelivr.net/npm/@docsearch/js@3:8
    <anonymous> http://localhost:1313/search/?q=test:249
```

It looks like something is going wrong in the docsearch script. Can someone help me understand what might be happening?

## Steps to reproduce

1. Go to [https://deploy-preview-21--tensil.netlify.app/search/?q=test]()
2. Open JS console

## Expected behavior

Search to work

## Environment

- OS: Linux
- Browser: Firefox
- DocSearch version: 3

**Comment by shortcuts** [comment]
Hey, could you please share your implementation?

**Comment by shortcuts** [comment]
A `container` is required for DocSearch to populate your DOM with our components: https://docsearch.algolia.com/docs/api/#container, I don't see a div with the ID `docsearch` but it's how you initialized it: https://github.com/tensil-ai/tensil-landing/pull/21/files#diff-2f05f24fe742de53e65f8c2363c9eda519591ab733dc118d6cf2a4c541071002R7

**Comment by shortcuts** [comment]
Closing this issue as answered, feel free to re-open if it occurs again with the answer above.

**Comment by siduck** [comment]
hi @shortcuts im facing the same issue :(

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/221065199-2462bde0-1ac4-4509-a330-20a31636d069.png)

I did import the necessary tags too
