### ISSUE TITLE
Extraneous HTML comments displayed in search results.

### ISSUE THREAD

**Issue by FezVrasta** [algolia/docsearch#1422]
## Description

Hi, we are seeing HTML comments returned together with the search results text. See the attached screenshot.

![image](https://user-images.githubusercontent.com/5382443/176655978-651e2e4e-87db-4ca7-88ed-f260a47fd0b7.png)

## Steps to reproduce

1. See this branch https://github.com/floating-ui/floating-ui/pull/1637

## Expected behavior

No HTML comments should be displayed.

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android] any
- Browser: [e.g. Chrome, Safari] any
- DocSearch version: [e.g. 3.0.0] latest

**Comment by shortcuts** [comment]
Hey! It indeed seems that those comment are present in the DOM elements we crawl (see https://floating-ui.com/docs/shift for `p` tags) and therefore treated as pure text.

```
<p>These are the options you can pass to <!-- --><span data-rehype-pretty-code-fragment=""><code data-language="js" data-theme="default"><span class="line"><span style="color:#65BCFF">shift</span><span style="color:#B4C2F0">()</span></span></code></span>.<!-- --></p>
```

I'd personally advise you to remove those comments from your production build, but we also provide [a cheerio instance](https://docsearch.algolia.com/docs/record-extractor/#manipulate-the-dom-with-cheerio) so you could try to remove them from here.

**Comment by FezVrasta** [comment]
Thanks, it seems to be a React 18 thing with whitespaces inserted using `{' '}`, making the whole title a single variable fixed the issue. Thanks.
