### ISSUE TITLE
Unable to create new index.

### ISSUE THREAD

**Issue by razonyang** [algolia/docsearch#1428]
## Description

Hi, I want to create new indices for my site(DocSearch), in order to split docs from multiple versions.

It works fine that create a new Crawler under the same application(`QJSHIZ7V63`), but the new Crawler indices are not show up on Algolia dashboard, is there any way to check the usage of new Crawler indices?

Thanks.

## Steps to reproduce

1. Go to `https://crawler.algolia.com/`
2. Click on `Editor`
3. Append new index into `actions` and `initialIndexSettings`.

```
Error: {"name":"ApiError","message":"Index not allowed with this API key","status":403,"transporterStackTrace":[{"request":{"headers":{"x-algolia-api-key":"*****","x-algolia-application-id":"QJSHIZ7V63","content-type":"application/x-www-form-urlencoded"},"method":"DELETE","url":"https://QJSHIZ7V63.algolia.net/1/indexes/v1.tmp?x-algolia-agent=Algolia%20for%20JavaScript%20(4.13.1)%3B%20Node.js%20(16.14.2)%3B%20Algolia%20crawler%20(v2.332.3)","connectTimeout":2,"responseTimeout":30},"response":{"status":403,"content":"{\"message\":\"Index not allowed with this API key\",\"status\":403}","isTimedOut":false},"host":{"protocol":"https","url":"QJSHIZ7V63.algolia.net","accept":2},"triesLeft":3}]}
```

## Expected behavior

Able to create index.

## Environment

- DocSearch version: `3.0.0`

**Comment by shortcuts** [comment]
Hey, the index needs to start with the name of your application (same name as your crawler name), e.g. if application is `myapplication`, allowed indices are `myapplication*`

**Comment by razonyang** [comment]
@shortcuts Thank you very much, didn't know that.
