### ISSUE TITLE
Unclear how to use hitsPerPage

### ISSUE THREAD

**Issue by remcokalf** [algolia/docsearch#1429]
Not sure if this is a documentation issue or a bug.

I want to increase the amount of results shown. It is now 5.

The docs point to:
[https://docsearch.algolia.com/docs/api#searchparameters](url)

and from there to:
[https://www.algolia.com/doc/api-reference/search-api-parameters/](url)

Reading the above, the code below should increase number of results from 5 to 10. 
But it does not work.

`docsearch({
                container: '#docsearch',
                appId: 'xxx,
                apiKey: 'xxx',
                indexName: 'xxx',
                translations: {
                    button: {
                        buttonText: 'Click to search ...'
                    }
                },
                searchParameters: {
                    hitsPerPage: 10
                }
            });`

What am I missing?
How to get hitsPerPage working?
Could this be improved in the docs?

**Comment by remcokalf** [comment]
Ah, ok. We have only one section: https://d.pr/i/pFC7SE. We have 1 help center that is getting searched.
If I understand correctly we'd have to add sections..split results from the help center up in sections somehow. Not sure if that would help or confuse our users, but will look into it.
It would be nice if we could influence the maximum of 5.

**Comment by shortcuts** [comment]
Closing as answered, feel free to re-open if needed.
