### ISSUE TITLE
Unexpected behavior when pressing enter on the webpage search field

### ISSUE THREAD

**Issue by seafoox** [algolia/docsearch#143]
When typing an unknown word in the top right search field at https://community.algolia.com/docsearch/, and then pressing "Enter" key links to a 404 github page.

**Comment by dzello** [comment]
There is also a CSS issue when there are no results, the text is almost underneath the header. Thoughts @LukyVj @maxiloc?

**Comment by s-pace** [comment]
Solved with the new version of DocSearch
