### ISSUE TITLE
Docker Compose file

### ISSUE THREAD

**Issue by deepfriedbrain** [algolia/docsearch#1438]
I'm trying to create a docker compose file to run the Docsearch scraper container but I'm not able to get it to work correctly. I keep getting an error : raise AlgoliaUnreachableHostException("Unreachable hosts")

What host is giving an error. My site that needs to be scraped is up and running.

Here's my docker-compose file:

    version: '3'
    services:
    docsearch:
      image: algolia/docsearch-scraper
      env_file:
        ./docsearch.env
      environment:
        - CONFIG=<hard code JSON>
        # - CONFIG=$$(cat ./docsearch-config.json | jq -r tostring)
        
For CONFIG, if I use $$(cat ./docsearch-config.json | jq -r tostring), I get "ValueError: CONFIG is not a valid JSON". So, I've hard-coded the JSON, but still running into the Unreachable hosts error.

`docsearch.env` contains my APPLICATION_ID and (admin) API_KEY.

Can someone help me create a proper docker compose file?

**Comment by shortcuts** [comment]
Hey, issues related to the scraper should be on the [docsearch-scraper](https://github.com/algolia/docsearch-scraper) repository, thanks!
