### ISSUE TITLE
[docsearch-css] Breakpoint is to be customizable

### ISSUE THREAD

**Issue by tnir** [algolia/docsearch#1439]
## Describe the problem

Breakpoints are now fixed and not customizable to align with other library, framework, or design systems.

https://github.com/algolia/docsearch/blob/83abe4c120bb7f5ae5bbd6e0faf229873546d768/packages/docsearch-css/src/button.css#L66
https://github.com/algolia/docsearch/blob/83abe4c120bb7f5ae5bbd6e0faf229873546d768/packages/docsearch-css/src/modal.css#L559

## Describe the solution

Use CSS custom properties to set all breakpoint(s) in docsearch-css.

## Alternatives you've considered

As per Apples's products i.e. iPad, we can directly change that with 768px without a custom property.

**Comment by shortcuts** [comment]
Discussed solution in https://github.com/algolia/docsearch/pull/1442

If you come up with a working solution feel free to submit it here @tnir so we can link the issue later! :D

**Comment by tnir** [comment]
@shortcuts Thank you for updating this issue. Could you mind setting this issue as **not planned** instead of **completed**? 🙏
