### ISSUE TITLE
How to refresh the index quickly through APIID

### ISSUE THREAD

**Issue by Beacontownfc** [algolia/docsearch#1440]
This is from Apache Linkis, our website address is [https://linkis.apache.org](https://linkis.apache.org). Algolia service we applied for by email. Since the documents of our website often need to be update, we hope Algolia can update the index quickly, but we don't know how to make the index update faster.

**Comment by shortcuts** [comment]
Hey, by faster do you mean more often or improving the time to crawl the website?

**Comment by Beacontownfc** [comment]
> Hey, by faster do you mean more often or improving the time to crawl the website?

Yes, we only have APIID and no registered account.

**Comment by shortcuts** [comment]
There was no schedule set in your config, I've added it to run every Monday, you can change its value by [following our documentation](https://www.algolia.com/doc/tools/crawler/apis/configuration/schedule/).

We also offer a GitHub action for you to trigger crawls on your own conditions, see https://github.com/algolia/algoliasearch-crawler-github-actions

**Comment by Beacontownfc** [comment]
> There was no schedule set in your config, I've added it to run every Monday, you can change its value by [following our documentation](https://www.algolia.com/doc/tools/crawler/apis/configuration/schedule/).
> 
> We also offer a GitHub action for you to trigger crawls on your own conditions, see https://github.com/algolia/algoliasearch-crawler-github-actions

Thank you !!!
