### ISSUE TITLE
crawler："No records extracted"

### ISSUE THREAD

**Issue by Huihuawk** [algolia/docsearch#1441]
## Description

Hi.
I configured the V3 version of algolia search. But the crawler could not get the HTML information correctly, resulting in "No records extracted". I don't know if there is any configuration missing that is causing the problem. The V2 version is fine.
Here is the test screenshot:
![image](https://user-images.githubusercontent.com/24917797/179707005-fd1ecd76-b2a3-4e89-b86f-44d75020187b.png)
![image](https://user-images.githubusercontent.com/24917797/179707022-9dcf2510-9176-4946-a727-1ee33e70bb2e.png)

Visit the webpage normally:
![image](https://user-images.githubusercontent.com/24917797/179707066-aa3f46d0-2899-4a37-8f48-18d7297995f4.png)

doc site: https://open.hand-china.com/choerodon-ui/zh/procmp/data-entry/password
now , doc use v2

**Comment by shortcuts** [comment]
Hey, are the elements we try to crawl from the config present in your DOM? Is your website client-side rendered?

**Comment by Huihuawk** [comment]
> 

hi. The V2 version can be crawled, it is server-side rendering, using GATSBY.

The above doc site still uses v2, and search is available. But the site information needs to be updated. So need to migrate to v3

**Comment by shortcuts** [comment]
Hey, you can see the `html` tab of the URL tester that shows how you page is rendered.

Testing with https://open.hand-china.com/choerodon-ui/zh/mds/guide, even from the browser, you can see hard refresh not rendering the page (white page).

I believe there's a routing/redirecting issue on your side, as we can observe the URL (https://open.hand-china.com/choerodon-ui/zh/mds/guide) redirecting to https://open.hand-china.com/choerodon-ui/zh/mds/guide/ which redirects to https://open.hand-china.com/choerodon-ui/zh/mds/guide again.

On my side I've tried with all of those options in your config:

```
  ignoreNoFollowTo: true,
  ignoreNoIndex: true,
  ignoreRobotsTxtRules: true,
  ignoreCanonicalTo: true,
  renderJavaScript: true
```

This does not seem to be something that needs to be fixed on our side so I'm closing the issue.
