### ISSUE TITLE
Rename the default branch from next to something better

### ISSUE THREAD

**Issue by tnir** [algolia/docsearch#1448]
Almost half a year ago, 3.0 reached GA in #1311.

The default branch can be changed from `next` to something better. `master` is not master-ish any more.

**Comment by shortcuts** [comment]
> Almost half a year ago

It's almost 6 months 😆 We will indeed move `master` to something like `v2` and set `next` as the `main` branch. Thanks for the reminder :D

**Comment by tnir** [comment]
Cool!
