### ISSUE TITLE
The email does not inform the relevant configuration information

### ISSUE THREAD

**Issue by Linkontoask** [algolia/docsearch#1492]
I applied for document search support using https://docsearch.algolia.com/apply/, but in the email reply it says that my program has been accepted, but I can't find any information about it under my account, and there is no reply to the email, what can I do to get the information? Thank you.

- link https://support.algolia.com/hc/en-us/requests/509207
- My email linkorgs@163.com

**Comment by Linkontoask** [comment]
I don't see any search information about this site and I don't find a corresponding solution in the documentation, so what should I do to get the relevant information for the search?
I have also submitted a question about this on github and so far there has been no reply. Could this be some kind of bug in the process.
I don't have any application information under my account and the screenshot is below.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/26475695/184098949-eb2c4484-5a24-442e-84dc-5cebbcaa33c7.png">

**Comment by shortcuts** [comment]
Hey

> but in the email reply it says that my program has been accepted, but I can't find any information about it under my account

Indeed we could try to give more context when encountering duplicate application, I've noted that and will iterate on it!

In your case, we have a deployed app (from July) for https://gyron.netlify.app/, which should cover all domains of this website. If you don't have access to this app, please re-apply, I'll deploy it before end of week.

**Comment by Linkontoask** [comment]
> Hey
> 
> > but in the email reply it says that my program has been accepted, but I can't find any information about it under my account
> 
> Indeed we could try to give more context when encountering duplicate application, I've noted that and will iterate on it!
> 
> In your case, we have a deployed app (from July) for https://gyron.netlify.app/, which should cover all domains of this website. If you don't have access to this app, please re-apply, I'll deploy it before end of week.

Thank you for your reply. You are right, maybe I accidentally deleted it when I deleted the application before.

Great, then I'll wait for you to deploy it before plugging algolia into my site.

**Comment by shortcuts** [comment]
Closing this ticket as it should be resolved via the apply process.

Please re-apply and I'll follow with a new app!

**Comment by Linkontoask** [comment]
I have reapplied and am awaiting a response
