### ISSUE TITLE
No Records Extracted

### ISSUE THREAD

**Issue by Alpsli** [algolia/docsearch#1497]
## Description

After receiving the email, I recovered and found that there was No data after access, and the crawler showed 'No Records extracted'

![image](https://user-images.githubusercontent.com/52439609/183929629-ba45fb66-664d-4a3c-8c42-bde314d3e693.png)
![image](https://user-images.githubusercontent.com/52439609/183930164-5b6cdcf6-278c-4930-9413-3ec4ddec2775.png)

- Browser: [Chrome]
- DocSearch version: [3.0.0]

**Comment by shortcuts** [comment]
Hey, is there any routing/redirecting logic on your side? You can use the [url tester](https://docsearch.algolia.com/docs/manage-your-crawls/#url-tester) and see 404s returned from your website

![Screenshot 2022-08-10 at 16 44 10](https://user-images.githubusercontent.com/20689156/183931468-8bfab8a4-93bd-46a0-934c-6811b1dc1fda.png)

**Comment by bodinsamuel** [comment]
The website is not served using SSR, you can:
- use `renderJavaScript`
- fix your website **(recommended)**

**Comment by Alpsli** [comment]
ok，I will try to open dumi ssr to resolve this problem

**Comment by shortcuts** [comment]
Closing the issue, feel free to re-open if needed.

**Comment by Alpsli** [comment]
I have open ssr on my site built by dumi，and ssr is ok，but Crawler still can work correctly.
![image](https://user-images.githubusercontent.com/52439609/184419481-ed26600b-d594-4f65-ac0c-084f9559b55c.png)
![image](https://user-images.githubusercontent.com/52439609/184419783-f6c283ec-0742-4286-b103-d06485aa8a53.png)
and the config like this
![image](https://user-images.githubusercontent.com/52439609/184419891-5894fcb4-ba2e-4f92-abc6-998823b96a9b.png)

**Comment by chrisarnott86** [comment]
I'm having a similar issue with my site (VuePress 1). My account with Algolia is confirmed, the crawler has run but no records entered in to the index.

![image](https://user-images.githubusercontent.com/5929303/198849541-1cc84445-62ea-4424-9f3d-10c5eb35fa3d.png)
