### ISSUE TITLE
Crawler doesn't work correctly

### ISSUE THREAD

**Issue by Alpsli** [algolia/docsearch#1500]
## Description

I have open ssr on my site built by dumi，and ssr is ok，but Crawler still can't work correctly.
![image](https://user-images.githubusercontent.com/52439609/184419481-ed26600b-d594-4f65-ac0c-084f9559b55c.png)
![image](https://user-images.githubusercontent.com/52439609/184419783-f6c283ec-0742-4286-b103-d06485aa8a53.png)
![image](https://user-images.githubusercontent.com/52439609/184420068-3fd293eb-9c8d-4032-970e-feeb9fda862a.png)

**and the config like this**

![image](https://user-images.githubusercontent.com/52439609/184419891-5894fcb4-ba2e-4f92-abc6-998823b96a9b.png)

**Comment by shortcuts** [comment]
Hey, it looks like its working looking at your 2nd screenshot. I've just started a new crawl and your index is now populated.

Please, make sure read the docs before opening issues.
