### ISSUE TITLE
Docsearch website improvement when submitting a request

### ISSUE THREAD

**Issue by maxiloc** [algolia/docsearch#151]
There should probably be 1) a more obvious UI indication that the form has been submited), perhaps by 2) giving them somewhere to go next, like showing them a few articles from our blog about DocSearch —> https://blog.algolia.com/how-to-build-a-helpful-search-for-technical-documentation-the-laravel-example/

**Comment by s-pace** [comment]
![image](https://user-images.githubusercontent.com/32097720/35829030-d8547f98-0ac1-11e8-8bc1-988ec9c279c4.png)
Solved
