### ISSUE TITLE
website image broken

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#152]
https://community.algolia.com/docsearch/documentation/

![2016-10-22-011857_772x429_scrot](https://cloud.githubusercontent.com/assets/123822/19614443/93760184-97f5-11e6-82b0-3dec2936cfcc.png)

**Comment by dzello** [comment]
@vvo @maxiloc thoughts?

**Comment by vvo** [comment]
Thx @Jerskouille for handling that chore!
