### ISSUE TITLE
how to ignore style for searchbox

### ISSUE THREAD

**Issue by sabgaby** [algolia/docsearch#158]
Hello! Is there any simple way to ignore all the styling for the searchbox? I am using Semantic UI and therefore don't want to add any additional styling to override the styling imposed by Docsearch. It mainly messes up with the width (set to fluid), and does not respect the icon on the left. 
![screen shot 2016-11-17 at 11 35 06](https://cloud.githubusercontent.com/assets/5911330/20385987/e88847d0-acb9-11e6-9ba8-92e71bc591c1.png)

I am not a programmer so I am thankful for any help on this!
Cheers!

**Comment by LukyVj** [comment]
Hello, 

thanks for opening the issue. 

I think you can specify it in css like this : 

```
selector {
  all: initial
}
```

**Comment by LukyVj** [comment]
Hi @sabgaby, did the fix worked ?

**Comment by sabgaby** [comment]
@LukyVj tbh I didn't quite get your suggestion 😖 . I basically just copied your suggestion to my CSS and hoped for the best, but it didn't work. I was waiting for my coding partner @cube5 to see if he would get it.

**Comment by LukyVj** [comment]
Hello @sabgaby, 

So, my suggestion is to reset the CSS into the searchbox, by using `all: initial`. 
If you still struggle, maybe I can have a quick chat with your friend @cube5 to explain him :) ?

**Comment by cube5** [comment]
Hi! Thanks @LukyVj, @sabgaby told me about the issue and I added the css you suggested, but also some padding to align things properly.

First (using only `all: initial`):
![captura de pantalla de 2016-11-21 15 04 00](https://cloud.githubusercontent.com/assets/12036916/20500638/e5865ff0-affb-11e6-946a-128cd20a0796.png)

Then adding some padding to the input itself and to the icon, everything looks better now.
![captura de pantalla de 2016-11-21 15 08 52](https://cloud.githubusercontent.com/assets/12036916/20500785/8825306a-affc-11e6-9d7a-adbcf53034d5.png)


Thanks a lot!

**Comment by LukyVj** [comment]
Yey! Well done! 
Glad to have been able to help!

**Comment by sabgaby** [comment]
Hey @LukyVj, I know this issue was closed, but I have been recoding every single search component  on CSS because algolia keeps messing my intended layout. We coded:
```
div[role="search"] {
  all: initial !important;
}
```
And it didn't work, which led us to recoding. But as the design evolves and we make changes, we have to do the individual changes to each component. Do you have another suggestion? Thanks!
