### ISSUE TITLE
Opening autocomplete results in new browser tabs

### ISSUE THREAD

**Issue by vlakoff** [algolia/docsearch#159]
(resubmit of https://github.com/algolia/instantsearch.js/issues/1608 to the proper repository)

Like many people, I'm a heavy user of middle click or ctrl+click to open links in new browser tabs.
Very sadly, this doesn't work for Algolia autocomplete suggestions…

1. Go to one of these websites: https://community.algolia.com/instantsearch.js/ – https://community.algolia.com/docsearch/ – https://laravel.com/
2. In the search box at top of the page, type some characters. Suggestions should be displayed below the box.
3. Middle click on a suggestion: nothing happens.
4. Ctrl+click on a suggestion: opens in the same browser tab.

Expected: both middle click and ctrl+click should open links in new browser tabs.

Tested on Firefox and Chrome.

**Comment by vvo** [comment]
This can be done, relevant code:
- templates are using div https://github.com/algolia/docsearch/blob/af22087add2778226de33f565c579eb81c1f8017/src/lib/templates.js#L7
- docsearch uses autocomplete handle selected: https://github.com/algolia/docsearch/blob/bfec481e85f6784af2ed9dddc34e2763ed83422a/src/lib/DocSearch.js#L263

We should:
- use <a href in templates with the right url
- avoid setting the location via window.location.href

And avoid breaking too much :)

**Comment by vlakoff** [comment]
Ah, it would have been such an usability improvement...

**Comment by s-pace** [comment]
@vlakoff 

You are right, let's add it into our next requirements

**Comment by s-pace** [comment]
@vlakoff 
We have solved these issues:
> - I don't see the url before clicking on the link
> - I cannot open the results in a new tab

The [new release is solving it](I don't see the url before clicking on the link
I cannot open the results in a new tab). This is a huge feature now.
