### ISSUE TITLE
Display error when no results in autocomplete on docs

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#160]
When searching for query with no results (eg. `analy`), the results seems truncated. We should add some padding and borders

![image](https://cloud.githubusercontent.com/assets/283419/21616892/b41a3522-d1e3-11e6-8e3b-66d789fd3da4.png)

**Comment by s-pace** [comment]
![image](https://user-images.githubusercontent.com/32097720/35829081-06ad0c98-0ac2-11e8-9668-4a700daa6d60.png)

Solved
