### ISSUE TITLE
[ request ] closeOnScroll

### ISSUE THREAD

**Issue by LukyVj** [algolia/docsearch#163]
I had a customer who wanted to be able to use the Docsearch on mobile.
One of his issue was that the dropdown was taking 80% of the screen, and to close it, the only way he found was to empty the input.

Even when scrolling the page, on mobile, the dropdown was still present on the page. 

So, I suggested him to use something like this : 

```javascript
$(window).scroll(function() {
    if ( $(window).width() < 768 ) { // If window size is less than 768 ( or any value your want ) 
      search.autocomplete.autocomplete.close(); // remove the dropdown
      search.autocomplete.autocomplete.setVal(''); // clear the input
    }
});
``` 

But then, after a discussion with @pixelastic, we thought it would be a good idea to ask for a "closeOnScroll" implementation.

It would be useful to be able to write it with a simple option like that : 

```javascript
 var search = docsearch({
    apiKey: 'API_KEY',
    indexName: 'INDEX_NAME',
    inputSelector: '#search',
    debug: false,
    closeOnScroll: true // False by default
  });
```

WDYT ?

**Comment by pixelastic** [comment]
I'm wondering if that shouldn't even be an option by default, but considering that we didn't really get many complains about it I think it's safer to add the option as an opt-in instead of an opt-out.

Other solution would be to document the solution in the readme.

Any thoughts on that @maxiloc @ElPicador?

**Comment by maxiloc** [comment]
Could you make a demo of this ? I don't see how that could look like.
How do you see the last result if when you scroll the dropdown closes ?

**Comment by LukyVj** [comment]
http://codepen.io/team/algolia/pen/409a77cc6e963951c15248c6108cf1f9

**Comment by LukyVj** [comment]
I sent you the demo in DM @maxiloc and on the solution I gave to the customer. I add the ability to scroll inside the dropdown if the screen height is too small. So if you scroll in the dropdown, it wont close the dropdown. 

If you scroll the page, it will.

**Comment by pixelastic** [comment]
That might be a behavior we want to set as a default in the v3. Tagging the issue to keep it in mind.

**Comment by shortcuts** [comment]
Closing v2 issue
