### ISSUE TITLE
process.env is in esm bundle

### ISSUE THREAD

**Issue by halkeye** [algolia/docsearch#1679]
## Description

When not using own bundler/transpiler, error of is thrown
```
process.env is in esm build output
```

## Steps to reproduce

1) load module dynamically (no transpiler)
```import('@docsearch/js').then(({default: docsearch}) => {```
2) click search button
3) console log with `Uncaught (in promise) ReferenceError: process is not defined`

**Live reproduction:**

https://codesandbox.io/s/restless-meadow-osexlj?from-embed=&file=/index.html

(til, you can import() from a url)

## Expected behavior

code works

## Environment

- OS: Linux
- Browser: Chrome
- DocSearch version: 3.3.0

**Comment by halkeye** [comment]
I think it might come from https://github.com/algolia/autocomplete/blob/e81c31fbc89ad72229ed84b0318873d442ceb19b/packages/autocomplete-shared/src/warn.ts but I can't really find process.env anywhere

**Comment by millotp** [comment]
Hello, this is no longer the case in the latest version (3.6.3)
