### ISSUE TITLE
Config Send Algolia Analytics in Docusaurus Project

### ISSUE THREAD

**Issue by will-nguyenpham** [algolia/docsearch#1688]
## Description

I'm developing a website using Docusaurus integrates with Algolia. At present, I want to track events when users use this search bar (using [default configs](https://docusaurus.io/docs/search#connecting-algolia) following Docusaurus)
<img width="280" alt="Screenshot 2022-12-01 at 13 40 20" src="https://user-images.githubusercontent.com/93693381/204983307-ca41181d-0839-4b40-bb14-fecb6dbc8202.png">

I add some configs in **docusaurus.config.js** but it does not send events to Algolia in the Debugger Settings View

`algolia: {
        appId: "...",
        indexName: "...",
        apiKey: "...",
        contextualSearch: true,
        searchParameters: {
            hitsPerPage: 20,
            clickAnalytics: true,
            analytics: true,
            advancedSyntax: true,
        },
        searchPagePath: 'search',
        selector: 'div#',
      },`
<img width="1112" alt="Screenshot 2022-12-01 at 13 48 23" src="https://user-images.githubusercontent.com/93693381/204984725-f72cf88c-907b-4fbd-967e-3fcee72a954e.png">

Please help me with it!

**Comment by randombeeper** [comment]
@will-nguyenpham I realize quite some time has passed but we could still help you with this if needed, however, we are preferring to interact with support type questions on Discord. Please see us there if you have current questions about this. https://alg.li/discord
