### ISSUE TITLE
import '@docsearch/css' not working in Next.js 13 appDir

### ISSUE THREAD

**Issue by trevorpfiz** [algolia/docsearch#1696]
## Description

I am importing `@docsearch/css` in a `layout.tsx` file in the `/app` directory. The CSS is not being loaded.

## Steps to reproduce

1. `npm i @docsearch/react`
2. `import '@docsearch/css'` in `layout.tsx`
3. `import { DocSearch } from '@docsearch/react'` in `page.tsx`

## Expected behavior

I would expect it to work the same as in `_app.tsx` in the `/pages` directory.

## Environment

- OS: Windows
- Browser: Chrome
- DocSearch version: 3.3.0

**Comment by ElektrikSpark** [comment]
My temporary fix is to duplicate the `style.css` file from `@docsearch/css` and `import '#/styles/style.css'` in `layout.tsx`.

**Comment by 8bittitan** [comment]
Hi @trevorpfiz are you still seeing this issue by chance?

**Comment by 807573212** [comment]
This may help. npm install @docsearch/js @docsearch/css

**Comment by levimichael** [comment]
Closing -- a fresh install of Next.js and Docsearch shows this working as expected. Feel free to open a new issue if this persists.
