### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by Sun-ZhenXing** [algolia/docsearch#1703]
## Description

<https://docsearch.algolia.com/apply>, after click `Apply`, console got:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at e (main.8aac519e.js:2:44935)
e @ main.8aac519e.js:2

POST https://docsearch-hub.herokuapp.com/form/inbound net::ERR_TIMED_OUT
```

`ipconfig /flushdns` also not working.

Tested many ip's (including Singapore, Hong Kong, Japan, etc.) and found that they all have the same error, which may be caused by the server.

## Environment

- OS: Windows
- Browser: Edge / Chrome

**Comment by TheCornerOfTheWorld** [comment]
解决了吗

**Comment by TheCornerOfTheWorld** [comment]
遇到同一个问题

**Comment by Sun-ZhenXing** [comment]
@TheCornerOfTheWorld Now it has been solved. I have successfully applied and received an acceptance email.

**Comment by TheCornerOfTheWorld** [comment]
![image](https://user-images.githubusercontent.com/37139987/222885251-7136ff70-094b-4ac8-a6ed-909e29106b46.png)
![image](https://user-images.githubusercontent.com/37139987/222885255-53e5c5a9-1d7f-44d1-b5cd-c2a5cba624b4.png)
How did you solve it?Is it because of different regions?

**Comment by Sun-ZhenXing** [comment]
This may be caused by a different network environment, and it is recommended to change the network environment. The search function responds in most network environments, so this is nothing to worry about. So it only needs to be done once.

The problem I pointed out (`Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')`) above is not related to this and does not cause the inability to Apply.
