### ISSUE TITLE
TypeError:  newCollection[key].push is not a function

### ISSUE THREAD

**Issue by atian25** [algolia/docsearch#171]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

https://eggjs.org/zh-cn/tutorials/index.html

![untitled](https://cloud.githubusercontent.com/assets/227713/23839235/8aea37c2-07d7-11e7-809f-b7dfbc3c5cf1.gif)

**Comment by ElPicador** [comment]
I'm sorry but I do not reproduce this error. I tried on Chrome & Firefox. 
On what browser, version, OS are you experiencing this issue?

**Comment by atian25** [comment]
mac sierra 10.12.2 (16C67)，chrome Version 56.0.2924.87 (64-bit) 

maybe with a chinese IME?  the `keydown` is trigger but input value is still empty

**Comment by vvo** [comment]
I can reproduce it by typing "asd" on a fresh page. Unfortunately I am not getting the right sourcemap because of bad comment source map in the dist file.

**Comment by vvo** [comment]
There's something trying to group result by level I guess and it's not working because the result set have null inside it maybe? See here: https://github.com/algolia/docsearch/blob/6dac0b31a009a3f3752cb630a97be3ea7e6f3798/src/lib/DocSearch.js#L187-L193

Failing algolia result:

<details>
<summary>click to show failing result</summary>

```json
{"results":[{"hits":[{"hierarchy":{"lvl2":null,"lvl3":null,"lvl0":"使用 async function 开发应用","lvl1":null,"lvl6":null,"lvl4":null,"lvl5":null},"url":"https://eggjs.org/zh-cn/tutorials/async-function.html#container","content":null,"anchor":"container","objectID":"1884745812","_highlightResult":{"hierarchy":{"lvl0":{"value":"使用 <span class=\"algolia-docsearch-suggestion--highlight\">asy</span>nc function 开发应用","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]}},"hierarchy_camel":{"lvl0":{"value":"使用 <span class=\"algolia-docsearch-suggestion--highlight\">asy</span>nc function 开发应用","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]}}}},{"hierarchy":{"lvl2":"# async function","lvl3":null,"lvl0":"egg 与 koa","lvl1":"# 异步编程模型","lvl6":null,"lvl4":null,"lvl5":null},"url":"https://eggjs.org/zh-cn/intro/egg-and-koa.html#async-function","content":null,"anchor":"async-function","objectID":"1884755042","_highlightResult":{"hierarchy":{"lvl2":{"value":"# <span class=\"algolia-docsearch-suggestion--highlight\">asy</span>nc function","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"egg 与 koa","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"# 异步编程模型","matchLevel":"none","matchedWords":[]}},"hierarchy_camel":{"lvl2":{"value":"#  <span class=\"algolia-docsearch-suggestion--highlight\">asy</span>nc function","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"egg 与 koa","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"#  异步编程模型","matchLevel":"none","matchedWords":[]}}}},{"hierarchy":{"lvl2":"# data⁣As⁣Query⁣String: Boolean","lvl3":null,"lvl0":"Http⁣Client","lvl1":"# options 参数详解","lvl6":null,"lvl4":null,"lvl5":null},"url":"https://eggjs.org/zh-cn/core/httpclient.html#dataasquerystring-boolean","content":null,"anchor":"dataasquerystring-boolean","objectID":"1884729492","_highlightResult":{"hierarchy":{"lvl2":{"value":"# data⁣<span class=\"algolia-docsearch-suggestion--highlight\">As</span>⁣Query⁣String: Boolean","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"Http⁣Client","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"# options 参数详解","matchLevel":"none","matchedWords":[]}},"hierarchy_camel":{"lvl2":{"value":"#   dataAsQueryString: Boolean","matchLevel":"none","matchedWords":[]},"lvl0":{"value":"HttpClient","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"#  options 参数详解","matchLevel":"none","matchedWords":[]}}}},{"hierarchy":{"lvl2":"Methods","lvl3":"add⁣Singleton (name, create)","lvl0":"Agent","lvl1":"Constructor","lvl6":null,"lvl4":null,"lvl5":null},"url":"https://eggjs.org/api/Agent.html#addSingleton","content":null,"anchor":"addSingleton","objectID":"1884763752","_highlightResult":{"hierarchy":{"lvl2":{"value":"Methods","matchLevel":"none","matchedWords":[]},"lvl3":{"value":"<span class=\"algolia-docsearch-suggestion--highlight\">add</span>⁣Singleton (name, create)","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"Agent","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"Constructor","matchLevel":"none","matchedWords":[]}},"hierarchy_camel":{"lvl2":{"value":"Methods","matchLevel":"none","matchedWords":[]},"lvl3":{"value":"<span class=\"algolia-docsearch-suggestion--highlight\">add</span>Singleton (name, create)","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"Agent","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"Constructor","matchLevel":"none","matchedWords":[]}}}},{"hierarchy":{"lvl2":"Methods","lvl3":"add⁣Singleton (name, create)","lvl0":"Application","lvl1":"Constructor","lvl6":null,"lvl4":null,"lvl5":null},"url":"https://eggjs.org/api/Application.html#addSingleton","content":null,"anchor":"addSingleton","objectID":"1884765742","_highlightResult":{"hierarchy":{"lvl2":{"value":"Methods","matchLevel":"none","matchedWords":[]},"lvl3":{"value":"<span class=\"algolia-docsearch-suggestion--highlight\">add</span>⁣Singleton (name, create)","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"Application","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"Constructor","matchLevel":"none","matchedWords":[]}},"hierarchy_camel":{"lvl2":{"value":"Methods","matchLevel":"none","matchedWords":[]},"lvl3":{"value":"<span class=\"algolia-docsearch-suggestion--highlight\">add</span>Singleton (name, create)","matchLevel":"full","fullyHighlighted":false,"matchedWords":["asd"]},"lvl0":{"value":"Application","matchLevel":"none","matchedWords":[]},"lvl1":{"value":"Constructor","matchLevel":"none","matchedWords":[]}}}}],"nbHits":124,"page":0,"nbPages":25,"hitsPerPage":5,"processingTimeMS":1,"exhaustiveNbHits":true,"query":"asd","params":"query=asd&hitsPerPage=5","index":"eggjs"}]}
```
</details>

**Comment by monkindey** [comment]
Thanks to awesome algolia project which make a lot of developer find out the API quickly and conveniently. I have figure out the problem just now, Because the hit collections have the `Constuctor` keyword, and then the logic will go at [utils.js#L67-L82](https://github.com/algolia/docsearch/blob/6dac0b31a009a3f3752cb630a97be3ea7e6f3798/src/lib/utils.js#L67-L82).

But unfortunately, the newCollection variable is the Object type, and it have the Constructor keyword, and then will not go the line [L77-L79](https://github.com/algolia/docsearch/blob/6dac0b31a009a3f3752cb630a97be3ea7e6f3798/src/lib/utils.js#L77-L79), so the newCollection[constructor] is not a array and doesn't have push function.

Maybe we can make the [L77-L79](https://github.com/algolia/docsearch/blob/6dac0b31a009a3f3752cb630a97be3ea7e6f3798/src/lib/utils.js#L77-L79) better.

```js
if (!newCollection[key] || key in Object.prototype) {
     newCollection[key] = []
}
```
When we hit the `constructor` keyword and the other Object.prototype property, let it to be a array and make it work.

**Comment by vvo** [comment]
That's awesome debugging, weirdly in the dataset I put in the example, the value is "Constructor" thus it's not "constructor", maybe it's lowercased somewhere?

Other than that the debugging is valid and there's a bug here, I'll fix it.

**Comment by monkindey** [comment]
yes, it will be lowercased in [utils.js#L75](https://github.com/algolia/docsearch/blob/6dac0b31a009a3f3752cb630a97be3ea7e6f3798/src/lib/utils.js#L75)

**Comment by vvo** [comment]
You really 🤘  it! You found the exact issue.

The way to solve it would be to change the line you gave to switch to `!newCollection.hasOwnProperty(key)`. If you are up to it, submit a PR!

**Comment by monkindey** [comment]
wow, I love your neat solution, it is better than mine. 

But according to the [hasOwnProperty MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#Using_hasOwnProperty_as_a_property_name), we might avoid directly to call newCollection's hasOwnProperty.

How about this ?

```js
!({}).hasOwnProperty.call(newCollection, key)
```

Or

```js
!Object.prototype.hasOwnProperty.call(newCollection, key)
```

But I think your solution is better, because newCollection won't change the original hasOwnProperty, and the code is shorter.

I am very glad to submit a PR.

**More Information**
[#7853](https://github.com/facebook/react/pull/7853)

**Comment by vvo** [comment]
```
!Object.prototype.hasOwnProperty.call(newCollection, key)
```

With a comment saying that given the data type of docsearch hits (basically any dev documentation), it might happen that both hasOwnProperty and Constructor are properties of the docsearch hits so we need to do this check).

That way nobody will try to remove it thinking "AHAH! It's useless!" :)

PR welcomed, bravo!

**Comment by monkindey** [comment]
lol

I fixed it in [#172](https://github.com/algolia/docsearch/pull/172), the comment might no good. I am glad to have your suggestions.

**Comment by vvo** [comment]
Will do a new release next week, so I can follow it and act if any issue

**Comment by monkindey** [comment]
Thanks a lot, let me know if find a issue.

**Comment by vvo** [comment]
I wonder if we should maybe review it a bit more, did you try to run the `npm run dev` of the docsearch project then put your credentials leading to constructor data, does it works?

Let me know

**Comment by monkindey** [comment]
I try to copy the cdn docsearch into the egg project, and switch

```js
!newCollection[key]
```
 to 

```js
!Object.prototype.hasOwnProperty(newCollection, key)
```
and it works when I type the `3` value, which would throw error before.

Sorry I didn't write the test for it, my bad.

Any suggestions, please let me know. I try me best to do it better.

**Comment by vvo** [comment]
👌  will release soon

**Comment by monkindey** [comment]
Thanks for your awesome work.
