### ISSUE TITLE
Can't focus on the `clear` button with tab key

### ISSUE THREAD

**Issue by chenxsan** [algolia/docsearch#1731]
## Steps to reproduce

1. Go to https://docsearch.algolia.com/
2. Click on the search button
3. type any characters into the search box
4. Now you should see the `X` button, i.e., `clear` button.
5. Try `tab` key to move focus into that button - you can't

## Expected behavior

I should be able to `tab` into the `clear` button.

## Environment

I've tested it under macOS with Firefox/Edge/Safari, none of them work as I expected.

**Comment by shanpriyan** [comment]
Seems like the `clear (x)` button is getting focused but not visible to the user. When I pressed the `Enter` key after pressing `Tab` key from search box it cleared the search box.

**Comment by chenxsan** [comment]
> Seems like the `clear (x)` button is getting focused but not visible to the user. When I pressed the `Enter` key after pressing `Tab` key from search box it cleared the search box.

Exactly, the outline of `:focus` state was disabled https://github.com/algolia/docsearch/blob/main/packages/docsearch-css/src/modal.css#L161.

**Comment by shortcuts** [comment]
Hey, thanks both! released in 3.3.1
