### ISSUE TITLE
“search by” shows twice

### ISSUE THREAD

**Issue by Haroenv** [algolia/docsearch#174]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

<img width="546" alt="screen shot 2017-03-26 at 15 01 57" src="https://cloud.githubusercontent.com/assets/6270048/24331463/4aaa5c6a-1235-11e7-8eb7-d7cf83c7b88b.png">

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

https://deploy-preview-432--yarnpkg.netlify.com/en/docs/

**What is the expected behavior?**

<img width="546" alt="screen shot 2017-03-26 at 15 01 57" src="https://cloud.githubusercontent.com/assets/6270048/24331490/bb711542-1235-11e7-9545-e18a8ec8a8c9.png">

**Comment by maxiloc** [comment]
Not sure I understand the issue

**Comment by Haroenv** [comment]
Search by is both in text and in the svg

**Comment by maxiloc** [comment]
This does not seem like a css issue on docsearch but on the implem.

.![image](https://cloud.githubusercontent.com/assets/1689007/24331559/d18f1648-1236-11e7-989b-ecb73a0835ff.png)

Works fine on the playground and a few other doc (vuejs, middleman, ...)

**Comment by Haroenv** [comment]
I didn’t manually add it though, that’s weird... Seems to be there because of this template: https://github.com/algolia/docsearch/blob/3c98ea588280f02bae581af2f52b69b3f0b044d0/src/lib/templates.js#L70 Do vue and middleman override the template maybe?

Version seems to be 2.3.1 universally

**Comment by Haroenv** [comment]
Vue uses docsearch 1.5.0 (<https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js>)

**Comment by s-pace** [comment]
Not anymore actual

**Comment by Haroenv** [comment]
for the record, this was happening on Yarn because we accidentally used v1 for css and v2 for the JS
