### ISSUE TITLE
docearch is not a function

### ISSUE THREAD

**Issue by bdougie** [algolia/docsearch#175]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have the following loaded at the end of my body:

```js
  <script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>

``` 

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

You see this live on the [fix-header](https://github.com/netlify/netlify-cms-www/blob/fix-header/site/layouts/partials/footer.html#L13) branch on the [netlify/netlify-cms-www](https://github.com/netlify/netlify-cms-www) project.

I am getting the following error:

```
Uncaught TypeError: docsearch is not a function
```

**What is the expected behavior?**
This was working yesterday but now broken this morning, not sure if there were any changes in the last release (~6 hours). Today it does not work and I had this on master already.

**Comment by bdougie** [comment]
Here is a JSFiddle: https://jsfiddle.net/kmyLfjzh/

**Comment by bdougie** [comment]
Just noticed it was also broken on https://serverless.com/framework/docs/ while I was trying to do some unrelated searching.

**Comment by maxiloc** [comment]
Hi @bdougie.

We updated dependencies of docsearch.js, which resulted in a webpack issue.
​We are currently working on a fix and should be fix very soon.

**Comment by Haroenv** [comment]
<img width="298" alt="screen shot 2017-03-27 at 18 11 00" src="https://cloud.githubusercontent.com/assets/6270048/24366247/c9f7954e-1318-11e7-9d36-656a952a4896.png”>

seems that it changed from a commonjs to a es module, am I right?

**Comment by rdwatters** [comment]
Thanks for reporting this @bdougie I was getting the same issue on https://hugodocs.info

Glad to hear it's already being worked on. Awesome 👍

**Comment by vvo** [comment]
This is now fixed, hard reload your browser and you'll be good.
