### ISSUE TITLE
Can't customize the template to display search results

### ISSUE THREAD

**Issue by javiereguiluz** [algolia/docsearch#176]
I'm trying to customize the way search results are displayed [on symfony.com doc website](https://symfony.com/doc/current/index.html). I'm trying this with no luck:

```js
<script id="suggestion_template" type="text/template">
    // custom template here...
</script>


docsearch({
  // ...
  autocompleteOptions: {
    templates: {
      suggestion: '#suggestion_template'
    }
  }
});
```

The docs are not clear to me because templates are explained in two separated sections:

* https://github.com/algolia/autocomplete.js#options
* https://github.com/algolia/autocomplete.js#datasets

Thanks!

**Comment by javiereguiluz** [comment]
Anyone can given me a clue to solve this? It's even possible to customize these templates when using docsearch instead of autocomplete.js? Thanks!

**Comment by bobylito** [comment]
Hi @javiereguiluz, thanks for your patience. The templates needs to be either a mustache template or a function. A CSS selector won't work in this case.

The function or the template will receive a suggestion which is a matching record.

**Comment by javiereguiluz** [comment]
Thanks for your reply! Now I'm trying this:

```js
docsearch({
    apiKey: '...',
    indexName: '...',
    inputSelector: '...',
    algoliaOptions: { filters: 'version:current' },
    autocompleteOptions: {
        templates: {
            header: function() {
                return 'The header...';
            },
            suggestion: function(suggestion) {
                return 'The search result...';
            }
        }
    }
});
```

I can see the modified header template, but the suggestions don't change:

![custom-search-templates](https://cloud.githubusercontent.com/assets/73419/25485493/674cadae-2b5e-11e7-9af0-16eb4a2235fa.png)

**Comment by bobylito** [comment]
Do you have a live staging version that we can have a lookt at @javiereguiluz ?

**Comment by javiereguiluz** [comment]
I don't have a live staging version, but if you save the following HTML and open it in your browser, you can reproduce the issue. Thanks!

```html
<!DOCTYPE html>
<html>
<head><title>DocSearch</title></head>
<body>
    <form>
        <input type="text" id="algolia_doc_search_query">
    </form>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            docsearch({
                apiKey: '2dc08306c041cf56da924473947b5e27',
                indexName: 'symfony',
                inputSelector: '#algolia_doc_search_query',
                algoliaOptions: { filters: 'version:current' },
                autocompleteOptions: {
                    templates: {
                        header: function() {
                            return 'The header...';
                        },
                        suggestion: function(suggestion) {
                            return 'The search result...';
                        }
                    }
                }
            });
        }
    </script>
</body>
</html>
```

**Comment by vvo** [comment]
Looking here: https://github.com/algolia/docsearch/blob/a2d9f93cc3a397f45a1260dbbda4aca8942e9a98/src/lib/DocSearch.js#L90

It seems that we do pass autocompleteOptions but then the templates for the docsearch source cannot be overridden.

Two solutions:
1. You submit a PR that makes it possible to pass templates to the docsearch method that will then be used instead of our default ones.
2. You use only CSS to customize the look and feel

Let us know how it goes.

**Comment by javiereguiluz** [comment]
@vvo thanks for taking a look into this. I'm not sure we can use just CSS to do what we want ... so I'll try to follow your first proposal (although I'm not skilled at JavaScript). Thanks!

**Comment by s-pace** [comment]
No more follow up, is your issue solved @javiereguiluz ?

**Comment by javiereguiluz** [comment]
@s-pace I'm afraid I wasn't able to fix this issue. It's sad because I wanted to use Algolia much more ... but if this can't be customized, I won't be able to do that.

**Comment by s-pace** [comment]
👋 ,
Feel free to offer a PR if you have something in mind.

Otherwise you [can use any one of our search experience tool](https://community.algolia.com/instantsearch.js/) in order to implement DocSearch.

Last but not least you can fork this repo and [use your own template](https://github.com/algolia/docsearch/blob/master/src/lib/templates.js). It is pretty simple and you can have your custom search experience.

Hope it helps you, otherwise feel free to ping

**Comment by javiereguiluz** [comment]
I'm closing this issue because we no longer need this feature, so we won't be able to provide a solution for it. Thanks!
