### ISSUE TITLE
Duplicated search results

### ISSUE THREAD

**Issue by bdougie** [algolia/docsearch#178]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
Recently merge a [PR](https://github.com/netlify/netlify-cms-www/pull/19) to add docs search to one of my company's projects, but it seems like our search results are getting duplicated. My first assumption is that the docsearch api is scraping our nav menu in addition to the page titles.  

https://github.com/netlify/netlify-cms-www
https://www.netlifycms.org/docs/

![](https://cloud.githubusercontent.com/assets/1050/25159541/47c6f336-2465-11e7-9079-b7131cfd0810.png)

**What is the expected behavior?**
Is possible to exclude the nav menu in the scrape or at least suppress the duplicated search results?

**Comment by Haroenv** [comment]
docsearch config: https://github.com/algolia/docsearch-configs/blob/master/configs/netlifycms.json

**Comment by maxiloc** [comment]
I updated the config (https://github.com/algolia/docsearch-configs/commit/4de6e13286498ffbf2eb364510df5e5660a81ebe), and deployed it should be fixed in a couple minutes.

**Comment by bdougie** [comment]
Thanks for the quick response 🙌🏾
