### ISSUE TITLE
Remove superfluous `#page-content` anchor from URLs returned by Algolia

### ISSUE THREAD

**Issue by brillout** [algolia/docsearch#1801]
I'm trying following code snippet to remove `#page-content` from URLs but it doesn't seem to work.
```js
    <script type="text/javascript">
      const appId = 'MUXG1ZE9F6';
      const apiKey = '8d5986fca9ba9110bcbbfc51263de88b';
      const indexName = 'vite-pluginssr';
      const transformData = function(hits) {
        hits.map(hit => {
          if (hit.anchor === 'page-content') {
            hit.url = hit.url.replace('#'+ hit.anchor, '');
            hit.anchor = null;
           }
        });
        return hits;
      };
      docsearch({
        container: '#docsearch-desktop',
        appId, apiKey, indexName, transformData
      });
      docsearch({
        container: '#docsearch-mobile',
        appId, apiKey, indexName, transformData
      });
    </script>
```

You can see this code snippet is live in the HTML of https://vite-plugin-ssr.com but when you, for example, search for "pre-rendering" then Algolia returns the URL `https://vite-plugin-ssr.com/pre-rendering#page-content` and `#page-content` is still in the URL.

Am I doing something wrong?

This solution was suggested in:
 - https://discourse.algolia.com/t/how-to-avoid-hash-in-search-result-url/6486
 - https://discourse.algolia.com/t/docsearchs-transformdata-function-cannot-remove-hashes-from-result-urls/8487

**Comment by shaneafsar** [comment]
Hi @brillout , here's an example with what you might be looking for, let us know if this works: https://codesandbox.io/s/old-monad-do63zm

A couple things might've changed since those answers were posted.

The key piece is that the API is now "transformItems", and we can just use the URL property:
```
const transformItems = function(hits) {
    hits.map(hit => {
        if (hit.url.indexOf('#page-content') > 0) {
            hit.url = hit.url.replace('#page-content', '');
        }
    });
    return hits;
};
```

**Comment by brillout** [comment]
Thanks! I replied to your PM on Discourse.

**Comment by brillout** [comment]
Thanks! The updated following code snippet is live at https://vite-plugin-ssr.com/ &ndash; I'll report back whether it works.

```html
    <script type="text/javascript">
      const appId = 'MUXG1ZE9F6';
      const apiKey = '8d5986fca9ba9110bcbbfc51263de88b';
      const indexName = 'vite-pluginssr';
      const transformItems = function(hits) {
        hits.map(hit => {
          if (hit.url.indexOf('#page-content') > 0) {
            hit.url = hit.url.replace('#page-content', '');
          }
        });
        return hits;
      };
      docsearch({
        container: '#docsearch-desktop',
        appId, apiKey, indexName, transformItems
      });
      docsearch({
        container: '#docsearch-mobile',
        appId, apiKey, indexName, transformItems
      });
    </script>
  ```

**Comment by brillout** [comment]
> I'll report back whether it works.

I can confirm it works.
