### ISSUE TITLE
Posting to `discourse.algolia.com` returns `403 error`

### ISSUE THREAD

**Issue by brillout** [algolia/docsearch#1802]
My account's username is `brillout`.

The error:
![image](https://user-images.githubusercontent.com/1005638/219961647-20256afa-757a-4ff1-adea-77d81aa6ea40.png)

**Comment by chuckmeyer** [comment]
Hey brillout -- It looks like a WAF rule on our Cloudflare CDN blocked you. Is there any chance you are including a code snippet that might be considered malicious in your post? I notice you are using a dynamic IP address, so it could also be that particular address was deny-listed for previous activity. I'll reach out to you via DM on the forums and we can try to continue the conversation there.

**Comment by brillout** [comment]
Thanks! I replied to your PM on Discourse.
