### ISSUE TITLE
hitComponent

### ISSUE THREAD

**Issue by RayShineHub** [algolia/docsearch#1809]
https://github.com/algolia/docsearch/blob/d81016b110aa0818231b6e4b7b96d2007d345b05/packages/docsearch-react/src/Hit.tsx#L11

@Whitespace  
Can you implement receiving **custom jump events** here instead of  `<a>`

**Comment by shortcuts** [comment]
hey, you should be able to provide your own hit component so you can customize the behavior: https://docsearch.algolia.com/docs/api/#hitcomponent

**Comment by RayShineHub** [comment]
> 嘿，你应该能够提供自己的命中组件，这样你就可以自定义行为： https: [//docsearch.algolia.com/docs/api/#hitcomponent](https://docsearch.algolia.com/docs/api/#hitcomponent)

hey @shortcuts 
Can you provide an example of a custom hitcomponent based on a vue project

thank u

**Comment by randombeeper** [comment]
@RayShineHub I know it's obviously been a long time here since your issue was logged. We're not able to provide sample code in a vue project. However, if you still have Algolia related questions, you can begin to utilize our Discord at https://alg.li/discord.
