### ISSUE TITLE
Mobile unfriendly! Single column option?

### ISSUE THREAD

**Issue by codemonkey9000** [algolia/docsearch#181]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have implemented DocSearch on my documentation website but I went to go test it out on mobile and search displays off the screen.

<img width="337" alt="screen shot 2017-05-15 at 11 14 09 am" src="https://cloud.githubusercontent.com/assets/5640420/26072619/ff5ff67c-3960-11e7-85b4-45d8947b9f3a.png">

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

Not sure if this is useful but here is my WIP PR for DocSearch: https://github.com/BonsaiAI/bonsaiai.github.io/pull/70

**What is the expected behavior?**

In the documentation I found "/* For bigger screens, when displaying results in two columns */
@media (min-width: 768px)" so I would assume that there is an option for displaying results in one column somewhere? How do I do that?

**Comment by LukyVj** [comment]
Hi @codemonkey9000! 
Thanks for opening the issue. 

My name is Lucas, I'm working as a front/css guy at Algolia, and I'm here to help! 

First of all, I'm sorry to see that you encounter some issues regarding your docSearch implementation, but don't worry, we will fix it! 

We plan to rebuild docsearch with a proper mobile version in mind.
For now, all I can do for you, is to give you the CSS you need to make your DocSearch dropdown responsive! 

If you're familiar with SASS, here is the Scss version of the fix: 
```

// Since some values are added by Javascript, we have 
// To add the !important option to override these values
.algolia-autocomplete {
  
  // On a max-width of 768px
  @media (max-width: 768px) {
    .ds-dropdown-menu {
      max-width: calc(100vw - 32px) !important;
      min-width: calc(100vw - 32px) !important;      
      width: calc(100vw - 32px) !important;
      margin-left: 16px !important;
    }
    .algolia-docsearch-suggestion--content {
      width: 100% !important;
      padding-left: 0 !important;
    }
    .algolia-docsearch-suggestion--content:before  {
      display: none !important;
    }
    .algolia-docsearch-suggestion--subcategory-column {
      display: none !important;
    }
  }
}
```  

Or if you prefer a vanilla CSS version: 
```

@media (max-width: 768px) {
  .algolia-autocomplete .ds-dropdown-menu {
    max-width: calc(100vw - 32px) !important;
    min-width: calc(100vw - 32px) !important;
    width: calc(100vw - 32px) !important;
    margin-left: 16px !important;
  }
  .algolia-autocomplete .algolia-docsearch-suggestion--content {
    width: 100% !important;
    padding-left: 0 !important;
  }
  .algolia-autocomplete .algolia-docsearch-suggestion--content:before {
    display: none !important;
  }
  .algolia-autocomplete .algolia-docsearch-suggestion--subcategory-column {
    display: none !important;
  }
}
``` 

And you can find a working demo here, on Codepen.io: 
https://codepen.io/LukyVj/pen/bb88d74d2bb6769bc3dfc0894fc073ba

**Comment by codemonkey9000** [comment]
The SCSS version worked great! Is there a way for me to get into some kind of beta to give you feedback about designing docsearch for mobile? There are a few things I wish it did right now that this didn't fix, but none are major.

Thank you so much for your help! Everyone working on DocSearch has been fantastic!

**Comment by maxiloc** [comment]
We don't have a beta program yet. Feel free to give us your feedback on this issue and we'll make sure to address them while working on better mobile integration

**Comment by codemonkey9000** [comment]
When I was testing the mobile implimentation I noticed that the results looked like they were getting cut off (I think it was that the algolia link/logo at the bottom wasn't always rendering) but now in the deployed version it shows up after a second or two. That might not be your issue.

On an iPhone with the default keyboard if I hit the x to see all of the results displayed at once the search results go away.

**Comment by abi** [comment]
Thanks for the temporary CSS code, looking forward to the proper mobile version! We are using it for https://docs.expo.io/versions/v17.0.0/index.html

**Comment by s-pace** [comment]
Solved #197 
Feel free to re-open it if needed

**Comment by olivierbeaulieu** [comment]
I just added DocSearch to our documentation website, and this issue seems to still be alive and well. The confirmation email I received from Algolia says to add this CSS file:
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

It looks like it's the latest version, but I still need to add the CSS patch provided above to solve the issue. Has the fixed not bet released yet?

**Comment by s-pace** [comment]
👋 @olivierbeaulieu 

Could you share a screenshot or a link to your website please? I would like to give it a try.

We are currently working on revamping the DocSearch UI. This issue should be no longer present although this issue should have been already resolved.

**Comment by olivierbeaulieu** [comment]
Sure thing, I just deployed it to https://docs.dfuse.io, although this deployment includes the CSS fix provided above.

**Comment by s-pace** [comment]
Thanks for sharing. It seems that the breaking point was not correctly handled. I will reopen this issue to make sure we address it with the ongoing v3 development.

Glad to hear the patch worked.

**Comment by shortcuts** [comment]
Closing v2 issue
