### ISSUE TITLE
Nice-to-have: Clicking outside Algolia search results modal would close the modal

### ISSUE THREAD

**Issue by krisstern** [algolia/docsearch#1810]
## Describe the problem
Currently the only way to close a modal (aka dialog box) for the mobile version of the search is to click a button, which sometimes requires a bit more effort. 

## Describe the solution
Would be nice to have the common more modern behavior of modal closing if the user clicks outside of it. 

## Alternatives you've considered
N/A

**Comment by randombeeper** [comment]
Verified that this is how it works today - clicking outside the search dialog closes it. Closing this issue.
