### ISSUE TITLE
Why my doc search has show error (Cannot read properties of undefined (reading 'lvl1'))

### ISSUE THREAD

**Issue by Trandat2022** [algolia/docsearch#1822]

**Comment by loicsay** [comment]
Hello @Trandat2022,
Could you provide more infomation about the issue please? (console screenshot, context, codesanbox link or a production link)

Thanks!

**Comment by Trandat2022** [comment]
@loicsay  https://codesandbox.io/s/snowy-sun-zklo7m?file=/src/App.js this here , tks u

**Comment by loicsay** [comment]
Hi @Trandat2022 ,

I see that you're on a Free plan. It doesn't include all the features needed to work with DocSearch.
To use DocSearch, please apply here https://docsearch.algolia.com/apply/!

**Comment by ChetSocio** [comment]
Hello @loicsay 
Thank you dude, I literally wasted my whole day trying to integrate algolia into my platform. I thought to upgrade once I reach my limits as explained in pricing page but you literally have fuckin useless documentation.

> If this is not possible for you, you're free to [open your own Algolia account](https://www.algolia.com/pricing) and run [DocSearch on your own](https://docsearch.algolia.com/docs/legacy/run-your-own) without this limitation. In that case, though, depending on the size of your documentation, you might need a paid account (free accounts can hold as much as 10k records).

Please read what this paragraph says in your official website. It says we can use api key until we reach limits of 10k records if we are not open source but want to integrate docsearch into our website.  Either change your package logic to accept both paid and free accounts  or remove this paragraph from your website.
