### ISSUE TITLE
Object has no key lvl0

### ISSUE THREAD

**Issue by calcyu** [algolia/docsearch#184]
Uncaught (in promise) Error: [groupBy]: Object has no key lvl0
    at Object.<anonymous> (docsearch.min.js:4)
    at Function.t.exports.T.each (docsearch.min.js:2)
    at Object.groupBy (docsearch.min.js:4)
    at Function.value (docsearch.min.js:4)
    at docsearch.min.js:4

**Comment by vvo** [comment]
Hi @calcyu, can you give us more context about where this error happens? On which website? So we can reproduce it, thanks.

**Comment by alcalyn** [comment]
Maybe related to https://github.com/algolia/docsearch/issues/186
It seems that you have to generate your index using docsearch crawler

**Comment by Haroenv** [comment]
That's right @alcalyn, this could happen if you're using docsearch with an index not made with the crawler. If you made your index yourself without docsearch, you can use autocomplete.js or InstantSearch directly without using docsearch

**Comment by Haroenv** [comment]
but more info is needed, as @vvo  said

**Comment by s-pace** [comment]
Must be fixed. Feel free to re open it if needed

**Comment by s-marques** [comment]
Good afternoon, has anyone managed to solve the problem? I have the same problem as docsearch.min.js:5 Uncaught (in promise) Error: [groupBy]: Object has no key lvl0

**Comment by Haroenv** [comment]
Do you use the latest version of @s-marques? is there somewhere this can be reproduced?

**Comment by s-marques** [comment]
I'm using the Docusaurus version
1.14.7 and there is the website links.dev.br

Em seg., 13 de set. de 2021 às 04:43, Haroen Viaene <
***@***.***> escreveu:

**Comment by shortcuts** [comment]
Hey @s-marques, I can't find an index name for `links.dev.br`, but by the error, I assume the `lvl0` selector of your config file is incorrect. Would you mind sharing the config you are using?

**Comment by s-marques** [comment]
I'm not able to configure Algolia with my docusaurus project, I always get
this error Uncaught (in promise) Error: [groupBy]: Object has no key lvl0

On siteConfig, I just informed apiKey, indexName and appId, on Algolia's
website I sent the json that is attached


Em seg., 13 de set. de 2021 às 09:28, Clément Vannicatte <
***@***.***> escreveu:

**Comment by shortcuts** [comment]
Thanks @s-marques, could you please provide the `appId` and `indexName` so that we can investigate?

**Comment by s-marques** [comment]
*apiKey: "39a3d8c529d3c9fe77851e3ebfef2147",    indexName: "linksdev",
   appId:"WG1WM749V9",*


Em seg., 13 de set. de 2021 às 10:54, Clément Vannicatte <
***@***.***> escreveu:

**Comment by s-marques** [comment]
*I don't know if there's any more configuration missing to do in docusaurus*
My structure only has this

[image: image.png]

Em seg., 13 de set. de 2021 às 10:55, S Marques ***@***.***>
escreveu:

**Comment by s-marques** [comment]
I don't know if there's any more configuration missing to do in docusaurus

**Comment by shortcuts** [comment]
Thanks!

Looking at the search query response, it seems that your records doesn't follow the shape of a DocSearch record.

With DocSearch, we require the Algolia records to follow a specific shape. You can achieve this by running our custom scraper to index your website: https://docsearch.algolia.com/docs/run-your-own/

To do so, you'll need a configuration file and as you are running Docusaurus v1, you can take this one as a starter: https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus.json
