### ISSUE TITLE
Broken link to Algolia API options in README.md

### ISSUE THREAD

**Issue by wwalc** [algolia/docsearch#185]
**Do you want to request a *feature* or report a *bug*?**

bug 

**What is the current behavior?**

In README.md there is a link that points to https://www.algolia.com/doc/api-client/javascript/parameters/#overview which gives 404.
 
> You will find all Algolia API options in its own documentation.

**What is the expected behavior?**

It should point to a correct place. Maybe to https://www.algolia.com/doc/api-reference/api-parameters/ ? This is at least where I found `hitsPerPage` option.

**Comment by Haroenv** [comment]
You're right, that's the new link. We should change the one in the readme, as well as adding a redirect in the documentation

**Comment by Haroenv** [comment]
Fixed in 5123508d962feb6b9b0064686617319d29e0b643, thanks!
