### ISSUE TITLE
Empty search results after front-end implementation

### ISSUE THREAD

**Issue by liyasthomas** [algolia/docsearch#1852]
## Description

We recently got DocSearch access to https://docs.hoppscotch.io. We completed the Crawler setup, and the indices got created. I tested with **Crawler Dashboard > Editor > Search UI Preview** which produced accurate expected results, but after front-end implementation, we get empty search results. AppID and Index name are as follows. 
```
appId: "JRX67EVEF2",
indexName: "hoppscotch"
```

## Steps to reproduce

1. Go to https://docs.hoppscotch.io
2. Click on Search or press <kbd>⌘</kbd><kbd>K</kbd>
3. Type in a string like: "Test"
4. See "Empty search results"

**Live reproduction:**

https://docs.hoppscotch.io

## Expected behavior

Front-end implementation should display search results similar to the Search UI Preview in Dashboard > Editor.

## Environment

- OS: macOS 13.3.1
- Browser: Chrome 111.0.5563.146
- DocSearch version: 3.3.3

**Comment by Minato1123** [comment]
I have a similar problem too, and I found this. Maybe you can take a look to see if it helps.
https://github.com/vuejs/vitepress/issues/1935#issuecomment-1433765099

**Comment by liyasthomas** [comment]
@Minato1123's comment helped me to fix the issue. In my case, the `langAttribute: "lang"` was missing in algolia configuration, this commit fixed it: https://github.com/hoppscotch/docs/commit/a7af76e4fad68d06e3991453348ad70b4e3a5d11

> I have a similar problem too, and I found this. Maybe you can take a look to see if it helps. [vuejs/vitepress#1935 (comment)](https://github.com/vuejs/vitepress/issues/1935#issuecomment-1433765099)
