### ISSUE TITLE
Docs: How to search the contents of the table

### ISSUE THREAD

**Issue by a631807682** [algolia/docsearch#1860]
We are using docsearch to query the document website created based on Markdown, and we found that the query results do not contain the content in the table.
I've looked in the documentation and don't see how to specify that the query contains a table or specify the content of the html element.
I want to know if it is supported, and if so, which attribute in the document is related.

**Comment by shaneafsar** [comment]
Hi there! Have you tried editing the selectors in your crawler configuration? Navigate to the editor in https://crawler.algolia.com, and take a look at https://docsearch.algolia.com/docs/record-extractor to see how to adjust the selectors to target different DOM elements and classes.

**Comment by a631807682** [comment]
Thanks, i will try.
