### ISSUE TITLE
Publish the support email address

### ISSUE THREAD

**Issue by ralfstx** [algolia/docsearch#187]
I was looking for a support email address and couldn't find it anywhere on https://community.algolia.com/docsearch/documentation/. There's only the "Join the program" form which doesn't seem appropriate for projects that participate already. Finally I came across `support@algolia.com` on [this issue](https://github.com/algolia/docsearch/issues/120).

Could you publish this address on the webpage somewhere?

**Comment by s-pace** [comment]
👋  @ralfstx,

This is on purpose, you have the right address when you submit a link.

Cheers
