### ISSUE TITLE
Pop out box with search results doesn't show up right after recovering focus

### ISSUE THREAD

**Issue by crunis** [algolia/docsearch#188]
I think this is a bug:

When the search box, with text already typed in, loses focus and then recovers it, it doesn't show again the pop up dialog. 

Steps to reproduce:
1. Go to any of these doc pages that are using docsearch:
  - [docs.rightscale.com](http://docs.rightscale.com)
  - [www.artik.io](https://www.artik.io/)
  - [docs.akeneo.com](https://docs.akeneo.com/latest/index.html)
2. Type "api" in the search box, note that a pop out window appears with some results
3. Click somewhere else in the window, the pop out window disappears
4. Click back in the search box, the pop out window is not shown again until you type or delete some text

I think the ideal behaviour would be that, as soon as the search box recovers focus, the pop out results box is shown again.

**Comment by s-pace** [comment]
Hi Crunis, 

Thank you for you feedback, we will consider it for our further development.

At least the search experience isn't blocked or stop.

Best,
