### ISSUE TITLE
Duplicated lvl0

### ISSUE THREAD

**Issue by oliviertassinari** [algolia/docsearch#190]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The lvl0 wording is picked two times:
![capture d ecran 2017-09-01 a 22 34 22](https://user-images.githubusercontent.com/3165635/29986896-bc41fb78-8f65-11e7-8abb-544e56163289.png)

You can see the issue on the https://material-ui-1dab0.firebaseapp.com/api/app-bar/ website, looking for a component name. Basically, [the configuration is looking](https://github.com/algolia/docsearch-configs/blob/bbc71a81f7e5c23da5b0e87cb1d3001a393a0115/configs/material-ui.json#L20
) for a class that we inject twice into the page

**What is the expected behavior?**

I wasn't expecting docsearch to find all the occurrence of the lvl0 selector (lvl2 and below are different) and to concatenate the wordings.
If it's the expected behavior, then I will submit a PR to update the lvl0 selector.

**Comment by s-pace** [comment]
Hi Olivier,

This comes from the fact that we create an record for each level 1.
By changing you min_indexed_level to 2, We will not create record for level 0 and 1.

I tried it locally and it works well. Do you want me to deploy it?

Best

**Comment by oliviertassinari** [comment]
Hi, I have been submitting a PR to address the issue on Material-UI configuration side.

No, I don't want to change the min indexed level.

**Comment by s-pace** [comment]
Hi Olivier,

Your PR has been merged.

Is your issue resolved? By changing this min indexed level, it will definitely resolve it.

**Comment by oliviertassinari** [comment]
Material-ui issue is solved. This is a more broader issue I was raising. But if you feel otherwise, you can close. Thank.
