### ISSUE TITLE
DocSearch broken after update to React 16 & Gatsby 1.9.37

### ISSUE THREAD

**Issue by s-pace** [algolia/docsearch#193]
Hi guys,

One of our customer of DocSearch has an issue after updating React to the v16

Website: https://reactfaq.site/
Repo: https://github.com/timarney/react-faq

You can go on its website, the search bar isn't working at all. He would like to know how to debug it. 

This has happened afterward updating his React version, could it be possible?

I have run it into my playground and everything go well. On our algolia dashboard, I have seen that we receive no request from its web site. It isn't only an issue of rendering the result since nothing is fetched.

Could you help me on this front end issue, I only start to go into the details on this part. I am 100% sure that the crawler/scraper is working well.

Thanks in advance

**Comment by s-pace** [comment]
additional: If he pastes the snippet code we've provided him into the console, then the search starts working.
May be an issue regarding the time he injects the code which is before the input element is created.
The scripts injection is done using Netlify.
He will have a look on Friday

**Comment by Haroenv** [comment]
The React website uses those versions, docsearch doesn't use react 🤔

**Comment by s-pace** [comment]
I thought it may be an issue regarding shadowing or overriding. 
I do know we don't use React. It is definitely an issue regarding the time he injects our snippet, it depends of his lifecycle management I guess.
Let see after his further investigation.

**Comment by s-pace** [comment]
Issue solved by injecting DocSearch at the step "ComponentDidMount"
