### ISSUE TITLE
Bug: Updating DocSearch community homepage (live)

### ISSUE THREAD

**Issue by s-pace** [algolia/docsearch#195]
On https://community.algolia.com/docsearch/, we should clean the websites shown as example:

https://babeljs.algolia.com/ is off => http://babeljs.io/

Please Remove scala and replace it by https://docs.fastlane.tools/

https://batch.com/=> https://batch.com/doc

I can do it on the index.haml

Thanks in advance,

Best

**Comment by phrawzty** [comment]
To clarify, @s-pace noticed that the implementations that we choose to highlight on https://community.algolia.com/docsearch/ might not all be great choices; for example, Scala _doesn't use DocSearch_. 😄 

In a broader context, we should define some criteria for determining which implementations to highlight, then modify that list accordingly. Example criteria (in no order):
* is active _&_ has proper attribution
* is attractive
* located on a popular web property
* gets lots of search requests
* gets lots of click-throughs

**Comment by s-pace** [comment]
We could also add counters into the web page (from our analytics)

**Comment by s-pace** [comment]
Solved #259 #260

**Comment by s-pace** [comment]
Solved #259 #260
