### ISSUE TITLE
Remember input in pop-up

### ISSUE THREAD

**Issue by zonky2** [algolia/docsearch#1979]
Is it possible that an input in a popup is remembered? If you click on a search result and the pop-up closes, when you open the pop-up again the search term is gone and you have to enter it again.

**Comment by randombeeper** [comment]
Hi @zonky2, my apologies for the very late reply, but as I'm going through issues now I am able to reply. While not exactly what you're looking for, something similar can be done with https://www.algolia.com/doc/ui-libraries/autocomplete/guides/adding-recent-searches/. If you have more questions along these lines feel free to join our Discord server at https://alg.li/discord.
