### ISSUE TITLE
enhancedSearchInput: true by default?

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#199]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

enhancedSearchInput, an option to have a good search input behaviour is false by default.

**What is the expected behavior?**

enhancedSearchInput could be true by default

WDYT?

**Comment by Haroenv** [comment]
It's not even documented in the readme; from quickly reading the code it seems to add a reset button?

**Comment by pixelastic** [comment]
@Shipow I think we should make this the default in the next version. We need to lead the way search inputs can be enhanced.

**Comment by Shipow** [comment]
some know bugs to fix before but I agree.

**Comment by s-pace** [comment]
We didn't expose it too much since it was breaking some layout. Definitely a good idea for the next v3

**Comment by s-pace** [comment]
Will be done thanks to the v3
