### ISSUE TITLE
I accidentally deleted the appId and apiKey. The search is currently unable to update the latest data. How can I handle this

### ISSUE THREAD

**Issue by fkc-alt** [algolia/docsearch#1995]
## Steps to reproduce

1. Go to `...`
2. Click on `...`
3. Scroll down to `...`

**Live reproduction:**

- JavaScript: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/js-demo
- React: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/demo

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- DocSearch version: [e.g. 3.0.0]

**Comment by shortcuts** [comment]
Hey, please reach out to the support https://algolia.com/support for this kind of issues
