### ISSUE TITLE
Domain Verification is disabled on application "2A78XFG5OO". Contact support to have one added manually.

### ISSUE THREAD

**Issue by baiwumm** [algolia/docsearch#1996]
## Steps to reproduce

![image](https://github.com/algolia/docsearch/assets/40554571/28d27e3a-2302-46af-9703-3f0147ffe935)
![image](https://github.com/algolia/docsearch/assets/40554571/a8657a96-2ae0-4d7f-9e05-3bd6a2dd1016)

**Live reproduction:**

- JavaScript: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/js-demo
- React: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/demo

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- DocSearch version: [e.g. 3.0.0]

**Comment by nicholaskillin** [comment]
@baiwumm We are running into the same issue. Did you ever figure out how to get a new domain verified?

**Comment by shortcuts** [comment]
Hey, please refer to https://support.algolia.com/hc/en-us/articles/16557939635985 in order to submit a request to support new domains
