### ISSUE TITLE
Crawler Only Catches skeleton

### ISSUE THREAD

**Issue by 18888628835** [algolia/docsearch#2005]
## Description

Hi, Guys. I have a website and before the content has been rendered, It showed a skeleton,like this.
<img width="596" alt="image" src="https://github.com/algolia/docsearch/assets/53749772/bbfe75dc-7089-4fda-a4c6-8abab193de1e">

But I found that, the crawler always catches the skeleton instead of the real content.

I tried to find the related option to solve this problem, but it  doesn't seem support.

so I have no idea.

could you help me?

## Steps to reproduce

1. Go to `[my website](https://www.qiuyanxi.com)`
2. Click on `collaborate`
3. See skeleton

## behavior in configuration editor
<img width="622" alt="image" src="https://github.com/algolia/docsearch/assets/53749772/8badc31f-f866-4a4f-af72-770971f652cb">

you can see it only catches the skeleton so `content` will be null
<img width="595" alt="image" src="https://github.com/algolia/docsearch/assets/53749772/566b1701-febe-4b77-b8b0-2bdce319ac22">

**Comment by randombeeper** [comment]
Hello @18888628835 , maybe this is resolved now? It appears search on your site is working. Closing but reopen if needed.
