### ISSUE TITLE
@docsearch/css: Provide Sass files too

### ISSUE THREAD

**Issue by XhmikosR** [algolia/docsearch#2006]
## Describe the problem

We are building our docs with Hugo, which by default is using libsass. I'm having trouble including **styles.css** in our docs Sass from node_modules, probably because of a libsass issue.

## Describe the solution

Include the source files too with a `scss` extension.

---

It would greatly help us build and include docsearch CSS instead of using a CDN or instead of trying to switch to Dart Sass in Hugo.

Thanks in advance!

**Comment by XhmikosR** [comment]
Is there any chance someone looks at this? It would greatly help us.

I understand you are using postcss, but there's no other way to include the CSS with Hugo unless it's a .scss file.

**Comment by levimichael** [comment]
@XhmikosR let me know if the addition in this PR would be sufficient! https://github.com/algolia/docsearch/pull/2201

**Comment by XhmikosR** [comment]
@levimichael thank you, yes! I just tested it locally by copying the style.css to style.scss.

> Though unless I'm mistaken, its possible to import a plain `.css` file in your own `.scss` file, no?
> https://sass-lang.com/documentation/at-rules/import/#importing-css

Unfortunately, that works only with Dart Sass. By default, Hugo bundles the (deprecated) libsass. But libsass requires no extra installation steps and is included with the hugo extended version. So, this issue is the only one blocking us in https://github.com/twbs/bootstrap/pull/38993 and this way we don't need to switch to Dart Sass for our docs yet.

**Comment by levimichael** [comment]
Ah okay, got it! I'm having a little trouble getting the release going (my first time triggering it on our side). It might be next week by the time I can get it sorted, FYI.

**Comment by levimichael** [comment]
@XhmikosR we just realeased `v3.6.0` which includes `style.scss`. 

Feel free to check out the rest of the release in the notes: https://github.com/algolia/docsearch/releases/tag/v3.6.0
