### ISSUE TITLE
Keyboard focus is lost on invoking esc key in search dialog.

### ISSUE THREAD

**Issue by msftedad** [algolia/docsearch#2027]
## Description
Keyboard focus is lost on invoking esc key in search dialog.
User with motor impairment who rely on keyboard will face if keyboard focus resets.

## Steps to reproduce

1. Open https://docusaurus.io/docs URL.
2. Navigate to 'Search' button and invoke it.
3. Now press Esc key to close the ‘Search’ dialog and observe the keyboard focus order.

**Live reproduction:**
https://docusaurus.io/docs

## Expected behavior

After hitting Esc key, keyboard focus should land on the last interacted element i.e., on ‘Search’ button.

## Environment

-OS: Windows 11 Enterprise Versiom25324.1011
-Edge Ver: 112.0.1722.23 (Official build) dev (64-bit)
-DocSearch version: 2.4.1

**
https://github.com/algolia/docsearch/assets/93735775/c2b555bb-b151-44cc-a57b-da63216fc904
**
https://github.com/algolia/docsearch/assets/93735775/5ece6625-366d-4175-a5d3-633d21d1c398

**Comment by msftedad** [comment]
Hi Team, Any update on this?

**Comment by randombeeper** [comment]
This appears to be fixed now! Thanks for the issue.
