### ISSUE TITLE
+350 live implementations is cut off at some zoom levels

### ISSUE THREAD

**Issue by Haroenv** [algolia/docsearch#203]
It should take up two lines instead of having ellipsis IMO

<img width="361" alt="screen shot 2017-10-17 at 13 50 47" src="https://user-images.githubusercontent.com/6270048/31688820-6430b1c6-b342-11e7-8a20-fea0b5824f50.png">

@LukyVj

**Comment by LukyVj** [comment]
Hehe good call, I assume your screen size is super small?

**Comment by Haroenv** [comment]
Nope, that was at 15” 100% zoom. Became normal once I zoomed out one tick

**Comment by LukyVj** [comment]
If you wan to do it, just go on the main `index.haml` file, and add `<span class="cf"></span>` after "live" :)

**Comment by Haroenv** [comment]
@LukyVj that's already the case 😄 

https://github.com/algolia/docsearch/blob/b17ac1ea6ba0bae94ce765c3bae5b0c30b968104/docs/index.haml#L59

**Comment by s-pace** [comment]
Fixed in #260
