### ISSUE TITLE
Managing pageRank and fallback patterns

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch#2042]
## Description

I have the following config where I specify a pageRank for specific patterns, and then later have a "catch-all" pattern for the whole of the website. Since I've done this, I'm getting a reduction in my record number, but I don't understand why.

How are identical paths in a config considered, for example, this following config, where I have 2 identical actions, only specific to 2 paths: a few specific pages to set their rank to 10, and then a catch-all rule for all the other pages, setting a page rank to 1.

```jsx
 actions: [
    {
      indexName: "website",
      pathsToMatch: [
        "https://docs.website.com/docs/dev/concepts/attributes",
        "https://docs.website.com/docs/dev/integration-api/api-effects",
        "https://docs.website.com/docs/**/overview",
      ],
      recordExtractor: ({ $, helpers, url }) => {
        // priority order: deepest active sub list header -> navbar active item -> 'Documentation'
        const lvl0 =
          $(
            ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
          )
            .last()
            .text() || "Documentation";

        return helpers.docsearch({
          recordProps: {
            lvl0: {
              selectors: "",
              defaultValue: lvl0,
            },
            lvl1: "header h1",
            lvl2: "article h2",
            lvl3: "article h3",
            content: "article p, article li, article td:last-child",
            pageRank: "10",
            category: {
              defaultValue: url.pathname.split("/")[2],
            },
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "website",
      pathsToMatch: ["https://docs.website.com/docs/**"],
      recordExtractor: ({ $, helpers, url }) => {
        // priority order: deepest active sub list header -> navbar active item -> 'Documentation'
        const lvl0 =
          $(
            ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
          )
            .last()
            .text() || "Documentation";

        return helpers.docsearch({
          recordProps: {
            lvl0: {
              selectors: "",
              defaultValue: lvl0,
            },
            lvl1: "header h1",
            lvl2: "article h2",
            lvl3: "article h3",
            content: "article p, article li, article td:last-child",
            pageRank: "1",
            category: {
              defaultValue: url.pathname.split("/")[2],
            },
          },
          indexHeadings: true,
        });
      },
    },
  ],
```

This gives me a reindexation blocker and my number of records falls by 12%, how is this possible? Which order are actions executed in? Should I start with my catch all and then use my specific paths?

Thanks!

**Comment by shortcuts** [comment]
Hey!

> This gives me a reindexation blocker and my number of records falls by 12%, how is this possible? Which order are actions executed in? Should I start with my catch all and then use my specific paths?

An action doesn't know about the other ones, I believe the error your errors are related to `duplicated records`, since they are based on URLs and the two action fetches similar pages. 

I'd suggest to leverage negative patterns in the 2nd action's `pathsToMatch`, which would end up in something like:

```js
pathsToMatch: [
  "https://docs.website.com/docs/**",
  "!https://docs.website.com/docs/dev/concepts/attributes",
  "!https://docs.website.com/docs/dev/integration-api/api-effects",
  "!https://docs.website.com/docs/**/overview",
],
```

(notice the `!` at the beginning), you can hover `pathsToMatch` in the config edit for more infos

**Comment by ArthurFlageul** [comment]
Thank you, everything's working now 👍
