### ISSUE TITLE
Results have incorrect spacing

### ISSUE THREAD

**Issue by mzbu** [algolia/docsearch#2053]
## Description

When searching using Algolia on our docs site, the results returned sometimes are missing spacing, i.e: "Skills ReferenceWrangle Skills" should read as "Skills Reference Wrangle Skills"

![image](https://github.com/DataChatAI/datachat/assets/95442268/e75ab1e0-b518-4f0a-8511-ce0eebb42588)

## Steps to reproduce

1. Go to docs.datachat.ai
2. Click on Algolia Searcg
3. Enter "Extend"

## Expected behavior

Spacing to be clear and correct as to not confuse users.

## Environment

Any web browser

**Comment by 8bittitan** [comment]
Hi @mzbu I took a look at this on your site you provided and can reproduce. It looks as though the data is coming back already incorrect which leads me to think either the Crawler is causing it or the source content. Could you confirm that where that content comes from is actually correct as well? Thanks!

![Screen Shot 2023-10-03 at 3 29 47 PM](https://github.com/algolia/docsearch/assets/33367713/0dcf82bb-8b3f-461a-85ce-0950503394c4)
