### ISSUE TITLE
Point JavaScript and css links to new jsDelivr infrastructure

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#207]
We must provide links to CSS and JS this way:

https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js
https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css

Instead of

https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css
https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js

That's the new way (/npm/) of having uptodate code on jsDelivr. Change must be propagated to the snippet we send to people and the website.

cc @s-pace can you handle that?

**Comment by s-pace** [comment]
Done

**Comment by s-pace** [comment]
is the backward compatibility guaranteed ?

**Comment by vvo** [comment]
> is the backward compatibility guaranteed ?

Yes if the file loads, that's the same content

**Comment by s-pace** [comment]
Fixed
