### ISSUE TITLE
Documentation website assest must be md5/versionned

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#208]
See how the html generated of https://community.algolia.com/places/ is different from the one from docsearch: we add md5 hashes to assets so when we deploy a new version, it's automatically updated.

Once we move to jekyll 3 we might be able to do the same.

cc @DirtyF

**Comment by DirtyF** [comment]
@vvo there's a gem for that: https://github.com/pathawks/liquid-md5

**Comment by redox** [comment]
> See how the html generated of https://community.algolia.com/places/ is different from the one from docsearch: we add md5 hashes to assets so when we deploy a new version, it's automatically updated.
> 
> Once we move to jekyll 3 we might be able to do the same.

I would recommend the `jekyll-assets` gem and the `digest: true` option. https://jekyll.github.io/jekyll-assets/

**Comment by pixelastic** [comment]
Oops, seems like the new website version does not rev assets either. I'm re-using this issue to keep track of that.

**Comment by vankirkprince1** [comment]
Pixel is my name oh.

**Comment by Shipow** [comment]
Hey, this will be fixed with the new website :)
