### ISSUE TITLE
once the form is sent, nothing shows

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#209]
I tried to fill in the form on the website, once sent there's no confirmation or success message, it just disappears. cc @LukyVj maybe?

**Comment by redox** [comment]
Just tested the same thing; we lost form validation (it was highlighting erroneous fields in red before) and the success message. Was previously implemented in https://github.com/algolia/docsearch/blob/master/docs/js/home.js#L10-L58

**Comment by s-pace** [comment]
![image](https://user-images.githubusercontent.com/32097720/35829030-d8547f98-0ac1-11e8-8bc1-988ec9c279c4.png)
Solved #197
