### ISSUE TITLE
Loading experience of homepage not good

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#211]
The home page loads this way:

![2017-10-18 10 21 18](https://user-images.githubusercontent.com/123822/31708002-1f630df8-b3ee-11e7-911f-0291d03de990.gif)

This is because the loading of the homepage image is done in JavaScript, while the GIF movies are inside the HTML code directly. Thus the browser first downloads the full html + images and then executes JS, then load a random screen then the page is loaded.

I felt the experience was not so good in most cases because of that.

What we can do is select a random GIF inside the html template directly (not with JavaScript) and show it. So that the html page loads with already the right image.

WDYT?

**Comment by pixelastic** [comment]
Thanks for the feedback @vvo, and sorry we didn't acknowledge it earlier...

The new version of the website does not have such large images and should not have this issue.
