### ISSUE TITLE
Similar to #1395, apply has been blocked by CORS

### ISSUE THREAD

**Issue by tcy1999** [algolia/docsearch#2118]
## Description

Could not submit the docsearch program application form due to cors error.

## Steps to reproduce

1. Go to https://docsearch.algolia.com/apply/
2. Click on `Join the program`
3. See error

## Environment

- OS: [macOS]
- Browser: [Chrome]

**Comment by avious00** [comment]
Seeing the same error, cannot apply to docsearch

**Comment by randombeeper** [comment]
This has been fixed for a long time, closing.
