### ISSUE TITLE
Apply Service is unavailable, ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by xunhui** [algolia/docsearch#2129]
## Description
Apply Service is unavailable, ERR_CONNECTION_TIMED_OUT

## Steps to reproduce
Click *join the program* in the Apply form.
![image](https://github.com/algolia/docsearch/assets/12594325/adb1a951-8a8b-45bc-9d9d-b8733d9caa44)

**Comment by randombeeper** [comment]
Hello @xunhui , sorry for the delay, I'm sure this has been fixed for some time now!
