### ISSUE TITLE
[Bug] Validation not updated to allow docusaurus v3 template in crawler

### ISSUE THREAD

**Issue by DominicGBauer** [algolia/docsearch#2133]
## Description
Not allowed to create a crawler that uses the docusaurus v3 template
![image](https://github.com/algolia/docsearch/assets/46312751/4c34eb0e-5329-47cc-ba1a-87096656e389)

## Steps to reproduce

1. Go to https://crawler.algolia.com/admin/crawlers/create and try create a crawler using docusaurus 3 template

## Expected behavior

I should be able to create a crawler that uses docusaurus template v3

**Comment by shortcuts** [comment]
Hey, thanks for reporting the bug, we've added it to our backlog and will come back to it ASAP. You can still use the `Docusaurus v2` template for `Docusaurus v3`, there was no breaking changes between the two versions!

**Comment by fhacloid** [comment]
Up for this issue, got the same here.

**Comment by randombeeper** [comment]
This issue has been resolved awhile back. Not sure exactly but it is working now. Closing out.
