### ISSUE TITLE
Korean text disappears from the input box. 

### ISSUE THREAD

**Issue by kijung-iM** [algolia/docsearch#2147]
## Description

Hello, I'm using algolia search module on docusaurus. 
Korean text disappears from the input box in chrome on android. Please refer to the video at the following link.

http://naver.me/5JVXlUmK

example)
'설정' -> 'ㅅ ㅓ ㅈ ㅓ'
'문서' -> 'ㅁ ㅜ ㄴ ㅅ ㅓ'

## Reproduction

My docusaurus site is [following](https://docs.whatap.io).

**Steps**

1. Go to https://docs.whatap.io in mobile environment(android chrome).
2. Click search icon on right upper.
3. Input the text '설정' or '문서'... Other letters with Korean consonants

## Expected behavior

I hope Korean consonants do not disappear and are entered correctly.

## Environment

- OS: Android
- Browser: Chrome
- Autocomplete version: 1.11.0

**Comment by randombeeper** [comment]
Hello @kijung-iM , I'm sorry you ran into that problem and for the delayed response. It seems you moved to another search provider, so for now I'm going to close this out. If you need help in the future, you can catch us on our Discord! Thanks!
