### ISSUE TITLE
All search results are empty.

### ISSUE THREAD

**Issue by bluefire1999** [algolia/docsearch#2170]
My site normal search is find, but view all search results are empty, how should I solve? Thank you.

URL: [https://g1879.gitee.io/drissionpagedocs](https://g1879.gitee.io/drissionpagedocs)

**Comment by bluefire1999** [comment]
help me, plz...

**Comment by randombeeper** [comment]
Site does not look to exist anymore. If you need help in the future, please see our Discord!
