### ISSUE TITLE
I accidentally deleted the application, so I can't access the console, and the crawler configuration data is gone. What should I do

### ISSUE THREAD

**Issue by baiwumm** [algolia/docsearch#2171]
## Description

I accidentally deleted the application, so I can't access the console, and the crawler configuration data is gone. What should I do

## Steps to reproduce
![微信截图_20240131112413](https://github.com/algolia/docsearch/assets/40554571/a79a25fc-a053-47ed-88f8-1e8a97cdb0d9)
![微信截图_20240131112423](https://github.com/algolia/docsearch/assets/40554571/3037b786-3cef-467c-8ff2-f4ccb8e954ec)

**Live reproduction:**

- JavaScript: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/js-demo
- React: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/demo

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- DocSearch version: [e.g. 3.0.0]

**Comment by randombeeper** [comment]
@baiwumm I know this is quite some time after you asked but leaving this comment for you and others to see.

If you accidentally delete your application, it may be recoverable if you reach out to our support team immediately. However, after some period of time the data will be deleted. In that case, re-applying for DocSearch is your best bet.
