### ISSUE TITLE
Allow custom placeholder

### ISSUE THREAD

**Issue by arno-fukuda** [algolia/docsearch#2232]
Currently placeholder prop allows to customize the search placeholder of the **modal** only.

We want to customize the placeholder of the search input component on our navbar.

It's currently hardcoded to "Search". 

https://github.com/algolia/docsearch/blob/6462d11826eea334e2fad1738d396571ea158035/packages/docsearch-react/src/DocSearchButton.tsx#L26

For my Japanese site, I would like to conditionally use "検索" as an example.

**Comment by arno-fukuda** [comment]
My apologies, I got it to work using it the following way:

```
import { useRouter } from "next/router"

const AlgoliaSearch = () => {
  const { locale } = useRouter()

  const translations = {
    button: {
      buttonText: locale === "ja-JP" ? "検索" : "Search",
      buttonAriaLabel: "Search",
    },
  }

  return (
      <DocSearch
        appId=<APPID>
        indexName=<NAME>
        apiKey=<APIKEY>
        placeholder={locale === "ja-JP" ? "検索" : "Search"}
        searchParameters={{
          facetFilters: [`language:${locale === "ja-JP" ? "ja" : "en"}`],
        }}
        maxResultsPerGroup={10}
        translations={translations}
      />
  )
}
```

**Comment by randombeeper** [comment]
Great, thank you!
