### ISSUE TITLE
Synonym configuration in current DocSearch

### ISSUE THREAD

**Issue by DominikaK** [algolia/docsearch#2268]
An issue from a few years back: https://github.com/algolia/docsearch/issues/640 explains how to set up synonyms in DocSearch via the `custom_settings` key. The key does not seem to exist in the current configuration.

Is there any way to set up synonyms in the current DocSearch UI or crawler?

**Comment by randombeeper** [comment]
Hello @DominikaK, sorry for the delayed response. Synonyms are now packaged a little differently and not accessible via the DocSearch plan. However, all other plans allow for synonyms. Please check out the Build or Grow plans, which both have free tiers to them if desired. https://www.algolia.com/pricing/ Thanks!
