### ISSUE TITLE
Search doesn't return anything

### ISSUE THREAD

**Issue by pitosalas** [algolia/docsearch#2286]
## Description

Not sure it's a bug but when I click on the search widget and get the search box and type anything in, it says no matches. This 

Here is my site: http://cosi102r.s3-website-us-east-1.amazonaws.com
And here is the source code: https://github.com/pitosalas/cosi102r

The "dashboard" from docsearch does show all the pages were indexed.

**Comment by randombeeper** [comment]
Hello @pitosalas and sorry for the delay. The URL you mentioned seems to have working search now? I responded to you via our support ticket, let's continue the support there. I'm going to close this GH issue.
