### ISSUE TITLE
`_highlightResult` and `_snippetResult` is missing in API result

### ISSUE THREAD

**Issue by fabian-hiller** [algolia/docsearch#2292]
Recently, without any changes to our crawler or website, the Algolia API stopped returning `_highlightResult` and `_snippetResult`, which broke the search of the Valibot documentation. Has something changed and I need to explicitly state that I need these keys? Or could it be that the crawler is not working properly anymore and is not capturing the values?

This is the fetch API call we make to retrieve the search result:

```js
fetch(
  `https://${import.meta.env.PUBLIC_ALGOLIA_APP_ID}-dsn.algolia.net/1/indexes/${
    import.meta.env.PUBLIC_ALGOLIA_INDEX_NAME
  }/query`,
  {
    method: "POST",
    headers: {
      "X-Algolia-Application-Id": import.meta.env.PUBLIC_ALGOLIA_APP_ID,
      "X-Algolia-API-Key": import.meta.env.PUBLIC_ALGOLIA_PUBLIC_API_KEY,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: currentInput,
      filters: "NOT type:lvl1",
    }),
  }
);
```

Algolia App ID: B90T8F2PFG
Algolia Index Name: valibot

Related issue at our repository: https://github.com/fabian-hiller/valibot/issues/774

**Comment by randombeeper** [comment]
@fabian-hiller thanks for bringing this to my attention. I'm not sure whats happening at the moment. I'd think if this was wide spread we'd have a very urgent issue needing resolved but I haven't seen anything blowing up yet. Having said that, I'm not saying there is no problem either. We're looking into it...

**Comment by fabian-hiller** [comment]
I customized the Algolia crawler to fit our needs. I have also customized the Algolia index settings and use a custom implementation to fetch and display the search results. Therefore, it is possible that others do not encounter the problem. I encountered the problem not only for Valibot, but also for a other project with similar settings and implementation. Thanks for looking into this!

Search UI implementation: https://github.com/fabian-hiller/valibot/blob/main/website/src/components/DocSearch.tsx#L182-L203

**Comment by fabian-hiller** [comment]
According to our web analysis, it stopped working on August 7.

**Comment by levimichael** [comment]
@fabian-hiller we're looking into the underlying cause of exclusion, but you can manually add `attributesToHighlight` and `attributesToSnippet` to your request.

For example, based on your implementation, add `attributesToHighlight: ["hierarchy.lvl0", "hierarchy.lvl1", "hierarchy.lvl2", "hierarchy.lvl3", "hierarchy.lvl4", "hierarchy.lvl5"]` to the body of your request in order to return the `_highlightResult` property for each `hit`.

**Comment by fabian-hiller** [comment]
Thank you very much! How does this work for `_snippetResult`?

**Comment by levimichael** [comment]
I'm inferring the value from your `AlgoliaResult` type, so based on that, you'd need to update your request with `"attributesToSnippet":["content"]}`

**Comment by fabian-hiller** [comment]
I think the problem is that previously it was enough to list `hierarchy` in the "Attributes to highlight" configuration. After changing it to the following, it worked again.

![sdfhasfsdfqwe](https://github.com/user-attachments/assets/cd22ddae-ef6c-48c5-a037-fa697b2bde37)

**Comment by levimichael** [comment]
ah interesting, that helps me diagnosing on our side. I would assume that adding `hierarchy` would return nested properties. Maybe this is what changed.

**Comment by fabian-hiller** [comment]
Thanks again! Since my problem is solved, please feel free to close this issue.

**Comment by levimichael** [comment]
Will do, glad this is resolved for you @fabian-hiller !
