### ISSUE TITLE
lvl0 `Results.title` category header is empty

### ISSUE THREAD

**Issue by Zhengqbbb** [algolia/docsearch#2294]
## Description

https://github.com/algolia/docsearch/discussions/2293

Recently, I have noticed that docsearch does not display the lvl0 title. 
I would like to know the reason or what configuration needs to be changed or API response have updated ?
As far as I know, all the documentation for VitePress has been affected :

https://vuejs.org/
https://vitejs.dev/
https://vueuse.org/
https://pinia.vuejs.org/

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6b607fc2-706c-4ed3-981a-0aa006ccc202">

## Live reproduction
[https://codesandbox.io/p/sandbox/great-surf-xzx9nm?workspaceId=120223f7-8927-4918-87ea-e72992f554b5](https://codesandbox.io/p/sandbox/great-surf-xzx9nm?workspaceId=120223f7-8927-4918-87ea-e72992f554b5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzvcm76j00063b6m700dygme%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzvcm76j00023b6mpu6qtzrb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzvcm76j00033b6miyxv8xiu%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzvcm76j00053b6mcosxhsjf%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzvcm76j00023b6mpu6qtzrb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzvcm76i00013b6my0xngqxg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzvcny06001d3b6mneougy6o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzvcm76j00023b6mpu6qtzrb%2522%252C%2522activeTabId%2522%253A%2522clzvcny06001d3b6mneougy6o%2522%257D%252C%2522clzvcm76j00053b6mcosxhsjf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzvcm76j00043b6mhljdh8en%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clzvcm76j00053b6mcosxhsjf%2522%252C%2522activeTabId%2522%253A%2522clzvcm76j00043b6mhljdh8en%2522%257D%252C%2522clzvcm76j00033b6miyxv8xiu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzvcm76j00033b6miyxv8xiu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/73e4140f-ed26-4f2b-aedb-10fb44731a74">

## Expected behavior

**show `lvl0` title**

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/25439296-d705-4780-b4d6-9f0ef2a37c48">

## Environment

- OS: macOS
- Browser: Chrome
- DocSearch version: 3.6.0

**Comment by randombeeper** [comment]
@Zhengqbbb thank you for reporting this. We are aware of an issue and are investigating!

**Comment by levimichael** [comment]
@Zhengqbbb for now, you can explicitly add `attributesToHighlight: ['hierarchy.lvl0']` to the `searchParameters`

Here's a reproduction based on your CodeSandbox: https://codesandbox.io/p/sandbox/vitepress-repo-fix-4kqsfn

**Comment by Zhengqbbb** [comment]
> @Zhengqbbb for now, you can explicitly add `attributesToHighlight: ['hierarchy.lvl0']` to the `searchParameters`

Thanks, the configure can be displayed normally ~

I have viewed through many documents and found that they also have issues. It seems that there is a problem with the API results and the component's judgment.
Hoping the investigation can be completed soon. 🧐

<table>
<tr>
  <td>
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/926a7bed-effd-49af-bf1d-7ca248b13ca0">
  </td>
  <td>
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/122993be-7849-4cbd-8f2a-b6b5ce83ce3d">
  </td>
  <td>
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/8e6d07e5-fe18-4d06-b71f-7967c8910bd2">
  </td>
</tr>
<tr>
<td>
https://tailwindcss.com/
</td>
<td>
https://remix.run/docs
</td>
<td>
https://laravel.com/docs/master
</td>
</tr>
</table>

**Comment by brc-dd** [comment]
Fixed by #2309

**Comment by randombeeper** [comment]
This has also been properly resolved by the engineering team and should no longer require any workarounds! Thanks for the original issue and getting this on our radar.
