### ISSUE TITLE
I've submitted the application several times. Didn't receive the code that needs to be integrated into the page and I don't know why. 

### ISSUE THREAD

**Issue by xihuanxiaorang** [algolia/docsearch#2316]
My website is https://docs.xiaorang.fun/. my email is [ll15019474951@gmail.com](mailto:ll15019474951@gmail.com)

**Comment by randombeeper** [comment]
Hello @xihuanxiaorang. I'm the one that reviews applications. You can only submit an application for a URL once and if it already exists, the resulting page should tell you that you've submitted a duplicate URL. 

In your case, I see that we approved your URL in February and you should have received the credentials then via email. The email address associated with that URL application is 1501947951@163.com. Sign in with that email address into dashboard.algolia.com and you should see an application already provisioned for you with the ID ADECD474SX.

**Comment by randombeeper** [comment]
@xihuanxiaorang I'm going to close this out as I don't think there is an issue here. If you continue to face a problem let me know.
