### ISSUE TITLE
Programmatically close DocSearch modal

### ISSUE THREAD

**Issue by brillout** [algolia/docsearch#2321]
## Describe the problem

I'm implementing a modal which is triggered by a shortcut. The issue is that, if the DocSearch modal is open, then the shortcut will open my modal on top of the DocSearch modal. How can I programmatically close DocSearch's modal?

## Describe the solution

DocSearch could expose a function `import { closeModal } from '@docsearch/react'`.

## Additional context

It's for the documentation website builder that powers [vike.dev](https://vike.dev/) and [telefunc.com](https://telefunc.com/).

**Comment by randombeeper** [comment]
Hello @brillout , thanks for reach out. We prefer to use Discord for general help and you'll get more visibility there https://alg.li/discord. Feel free to leverage the "Help" channel and post a question if this is still unresolved. Thanks!
