### ISSUE TITLE
v3.8.1 breaks Sass build

### ISSUE THREAD

**Issue by XhmikosR** [algolia/docsearch#2414]
## Steps to reproduce

1. Go to `...`
2. Click on `...`
3. Scroll down to `...`

**Live reproduction:**
[
- JavaScript: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/js-demo
- React: https://codesandbox.io/s/github/algolia/docsearch/tree/main/examples/demo](https://github.com/twbs/bootstrap/actions/runs/12375551822/job/34540617657?pr=41108)

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- DocSearch version: [e.g. 3.0.0]

---

I believe it's https://github.com/algolia/docsearch/commit/f3dc6462569719c36fbd40394f25f64f9d29c160 to blame since it's using the newer `@media` syntax. I'd revert the change to keep compatibility with older but still actively used Sass implementations.

**Comment by XhmikosR** [comment]
Refs https://github.com/twbs/bootstrap/pull/41108

**Comment by shortcuts** [comment]
Hey @XhmikosR thanks for reporting, indeed it's in their doc, seems like a miss from our side, https://github.com/algolia/docsearch/pull/2415 should revert it

**Comment by shortcuts** [comment]
Just released 3.8.2, let me know if it has fixed your issue!

**Comment by XhmikosR** [comment]
Thanks for the quick fix! I'll wait for the next patch version.

BTW you could totally check these things with Stylelint. We do have a
configuration we are using, in case it helps you guys.
