### ISSUE TITLE
Allow having non-complete domains (only the path)

### ISSUE THREAD

**Issue by Haroenv** [algolia/docsearch#244]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

if you're using docsearch on a deploy preview or on a localhost, each time you select an item, it goes to the production site.

**What is the expected behavior?**

 It would be nice if you could either pass an option to stay on the same origin or to do that by default

**Comment by maxiloc** [comment]
We voluntarily did not implement this, because sometimes it does not make sense especially if you index from several domains.

That being said this is doable by modifying the url via javascript:
https://jsfiddle.net/maxiloc/drwvzk54/

**Comment by Haroenv** [comment]
Okay, makes sense I guess 😄
