### ISSUE TITLE
source mapping URL is wrong

### ISSUE THREAD

**Issue by Haroenv** [algolia/docsearch#245]
https://unpkg.com/docsearch.js@2.4.1/dist/cdn/docsearch.min.js

//# sourceMappingURL=dist/cdn/docsearch.min.js.map

should be `//# sourceMappingURL=./docsearch.min.js.map` or something else relative

**Comment by s-pace** [comment]
Closing since I couldn't find the wrong code from the codebase. Feel free to reopen if needed
