### ISSUE TITLE
Add opengraph & twitter metas

### ISSUE THREAD

**Issue by redox** [algolia/docsearch#25]

**Comment by pixelastic** [comment]
PR in progress:

- [ ] Add relevant code to markup
- [ ] Set a nice tagline and description
- [ ] Add an image for sharing

**Comment by pixelastic** [comment]
I don't think we did it in instantsearch.js website

**Comment by redox** [comment]
> I don't think we did it in instantsearch.js website

Arg, not merged yet: https://github.com/algolia/instantsearch.js/blob/develop/docs/_layouts/default.html#L11-L25
