### ISSUE TITLE
Add SCSS files to the NPM Package

### ISSUE THREAD

**Issue by jackiboy** [algolia/docsearch#251]
Hi.
Can we please get the scss source files added to the npm package? they don't seem to be in their currently.

Cheers,
Jack

**Comment by vvo** [comment]
Hi @jackiboy, what's your usecase for having those files added to the npm package dist? Thanks!

**Comment by jackiboy** [comment]
Hi @vvo I want to import and compile the scss source and variable overrides into my main stylesheet.

**Comment by vvo** [comment]
Done @jackiboy

**Comment by jackiboy** [comment]
@vvo thanks mate!
