### ISSUE TITLE
docs(add analytics) add KPI value about the use of docSearch

### ISSUE THREAD

**Issue by s-pace** [algolia/docsearch#261]
Next neat content for the docSearch main webpage:

**Comment by s-pace** [comment]
#26

**Comment by pixelastic** [comment]
@s-pace Can you clarify what you had in mind here?

**Comment by s-pace** [comment]
I meant adding some analytics from usage in order to promote how we 🚀 doc. We could promote the global number of search for example

**Comment by pixelastic** [comment]
@Shipow Any feedback here? We could add a "Powering XXXX searches every day on 900+ documentations" maybe.

**Comment by Shipow** [comment]
From my POV those big numbers like API calls don't mean anything, it's vanity metric that shows at most that we got a good infra.
I'd prefer something like 'serving 10% of ALL documentation searches' but... yeah not that easy to compute right :p
