### ISSUE TITLE
How to implement before send or on request response ?

### ISSUE THREAD

**Issue by safeimuslim** [algolia/docsearch#271]
How to implement before send or on request response ?

**Comment by s-pace** [comment]
👋 @safeimuslim ,

Could you give more details like:
- which configuration (index `name`)
- which `API_Key`
- use case?
- Current behavior?
- Expected one?

If you can provide screenshot if it is visual. That will be perfect.

We could help your more easily and be the most likely to solve it.

Thanks in advance.

Cheers

**Comment by s-pace** [comment]
@safeimuslim Could you follow up pls, otherwise I will close this issue.

Thx

**Comment by safeimuslim** [comment]
@s-pace forget it, my problem in redux.
