### ISSUE TITLE
[FF] link in Documentation goes to 404

### ISSUE THREAD

**Issue by diomed** [algolia/docsearch#272]
On page https://community.algolia.com/docsearch/
link to Documentation looks like this:
https://community.algolia.com/docsearch/documentation/documentation/docsearch/introduction/

and goes to 404 page

**Comment by s-pace** [comment]
👋 @diomed,

Thank you for your feedback!

Could you check if you still have the issue. You have probably try to connect during the deployment.

The correct URL is `https://community.algolia.com/docsearch/documentation/docsearch/introduction/`

We may/will redesign it later on

**Comment by diomed** [comment]
it looks like it redirects me.

**Comment by s-pace** [comment]
To the right link?

**Comment by diomed** [comment]
no. to the wrong one

**Comment by s-pace** [comment]
**EDIT** This link is working fine for me:

[https://community.algolia.com/docsearch/documentation/docsearch/introduction/](https://community.algolia.com/docsearch/documentation/docsearch/introduction/)

**Comment by s-pace** [comment]
👋 @diomed,
Are you a firefox 🦊 user?

**Comment by diomed** [comment]
indeed, I am.
