### ISSUE TITLE
Deprecated Sass form in _searchbox.scss throws warnings

### ISSUE THREAD

**Issue by nkuehn** [algolia/docsearch#273]
**Do you want to request a *feature* or report a *bug*?**
Preventing a future Bug

**What is the current behavior?**
Building the current SCSS under Sass 3.5.5 yields the following warning:
```
DEPRECATION WARNING on line 14 of  /node_modules/docsearch.js/dist/npm/styles/_searchbox.scss:
The result of `0px != 0` will be `true` in future releases of Sass.
Unitless numbers will no longer be equal to the same numbers with units.
```
**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**
This is the expeced behavior but in future Sass versions it will be a bug. Better migrate now

**Comment by s-pace** [comment]
👋 @nkuehn ,

Thank you for the meaningful feedback,

We will had in the requirements for the next iteration. Feel free to PR.

Cheers

**Comment by pixelastic** [comment]
As part of our move to v3 (no ETA yet), we might want to fix this. My suggestion would be to drop SCSS dependency altogether in favor of postcss only. This will make all those calculation easier to read and lint.

**Comment by s-pace** [comment]
Will remove using this thanks to the v3 (beta so far)

**Comment by shortcuts** [comment]
Closing v2 issue
