### ISSUE TITLE
New website feedback

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#417]
- [x] Symfony does not use us anymore, we should remove the logo cc @0livier 
- [x] Hero is very heavy with the lines. It makes it difficult to read the subtitle. cc @Kosai106 
- [ ] Lines in the middle of the page aren't full-width. cc @Kosai106 
- [ ] `+` sign in the header seem broken (missing parts)
- [x] Footer isn't full-width either. cc @Kosai106
- [x] Three columns layout shouldn't use justified text.
- [x] Wrong OG Image
- [x] Input placeholder is misaligned ![image](https://user-images.githubusercontent.com/283419/44350148-f068fb00-a49e-11e8-99b0-6f8668ff54ea.png) cc @Haroenv 
- [x] Replace Stripe with MomentJS (Stripe is running their own Docker image)

**Comment by pixelastic** [comment]
> Hero is very heavy with the lines. It makes it difficult to read the subtitle

Also, the `+` signs seem broken:
![image](https://user-images.githubusercontent.com/283419/44348544-01b00880-a49b-11e8-8c2f-4f2f2872497e.png)

> Lines in the middle of the page aren't full-width
I did not manage to make them full width without having them taking too much space either, will need some help there.

cc @Shipow

**Comment by s-pace** [comment]
Did the design team update the algolia community logo? If so, you can discrad this comment
![image](https://user-images.githubusercontent.com/32097720/44348735-96b30180-a49b-11e8-9106-28a0bb4df9df.png)

**Comment by pixelastic** [comment]
@Shipow made this logo because the other one was drawing too much attention to itself with all its colors compared to the blue/grey style of the new website. This is an initiative on our side, we don't really want to replace the actual logo (used on all websites and shirts), but instead adapt it to this branding.

Maybe @sebnvzt has some insights/ideas on how we could use the Community logo along the new branding without having it looking too much like a christmas tree :christmas_tree:?

**Comment by pixelastic** [comment]
@Shipow We still have two small design issues here:

![image](https://user-images.githubusercontent.com/283419/46469152-decf7e80-c7d2-11e8-90df-0b16ef716fb7.png)
Plus sign in the header background seem off

![image](https://user-images.githubusercontent.com/283419/46469177-f1e24e80-c7d2-11e8-8b38-6882cc3b0212.png)
Curvy lines in the background don't go to each screen side when on a large screen

As it's minor, I'm enclined to just close the issue, but let me know if you want to take care of it.

**Comment by s-pace** [comment]
Majors issues solved.

Thanks @pixelastic
