### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by oliviertassinari** [algolia/docsearch#418]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The following lighthouse test is failing:

![capture d ecran 2018-08-21 a 00 26 43](https://user-images.githubusercontent.com/3165635/44370065-f085ec80-a4d8-11e8-9b9f-7e117ade6308.png)

You can reproduce it on [Bootstrap](http://getbootstrap.com/docs/4.1/getting-started/introduction/) or [Material-UI](https://material-ui.com/) with Chrome 68.

**What is the expected behavior?**

💯 % score

**Comment by s-pace** [comment]
Thank you for sharing. Do you need a fix asap or can it wait for the v3?

**Comment by oliviertassinari** [comment]
@s-pace as you see fit.

**Comment by Lausselloic** [comment]
Hello,

Looks like aria-label is not saved on destroy. On bootstrap there's an "aria-label" attribute on the search input, but when checking on docserach.js v2.6.2

```
// store the original values of the attrs that get modified
  // so modifications can be reverted on destroy
  $input.data(attrsKey, {
    'aria-autocomplete': $input.attr('aria-autocomplete'),
    'aria-expanded': $input.attr('aria-expanded'),
    'aria-owns': $input.attr('aria-owns'),
    autocomplete: $input.attr('autocomplete'),
    dir: $input.attr('dir'),
    role: $input.attr('role'),
    spellcheck: $input.attr('spellcheck'),
    style: $input.attr('style'),
    type: $input.attr('type')
  });
```
quick-fix will be to add `aria-label` to the saved attributes?

**Comment by endiliey** [comment]
It will be great to have this so that we can improve accessibility 😉

**Comment by oliviertassinari** [comment]
I have patched the problem with: https://github.com/mui-org/material-ui/blob/e4ef5bf1adc6df6888a947919124302ed29d3343/docs/src/modules/components/AppSearch.js#L50-L67.

**Comment by endiliey** [comment]
Thanks @oliviertassinari. I've sent a PR for it but I guess I'll use your solution for now.

cc @s-pace

**Comment by endiliey** [comment]
We can close this out. I've resolved it after upgrading to 2.6.3

**Comment by s-pace** [comment]
Thanks again @endiliey, version released 🚀

**Comment by oliviertassinari** [comment]
Do we have to wait a week to see the CDN cache expire?

**Comment by s-pace** [comment]
![image](https://user-images.githubusercontent.com/32097720/57683003-2a80bb00-7633-11e9-9740-b8e4233de1cf.png)
Should be updated :)

**Comment by Lausselloic** [comment]
thanks for the fix. Works well
