### ISSUE TITLE
Document the language/version metatags

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#420]
When crawling a Docusaurus website, we read the language and version from the `<meta name="docsearch:language" content="en" />` and `<meta name="docsearch:version" content="1.4.2" />` meta tags.

Those tags are actually read on all crawls, and might provide an easier mechanism for language/version faceting than parsing the url. In the future we might want to deprecate complex url parsing and instead ask website maintainers to add those tags to their pages.

In the meantime, we should add a new documentation page to the current website giving tips on how to best write the markup of the pages (it could also include adding a class on the active element in the sidebar, and a way to mark the wrapper of the main text content)

**Comment by pixelastic** [comment]
What I suggest is not to add CSS classes but HTML attributes instead as it won't have any impact on the styling.

For the main content, we could suggest adding a `data-docsearch="main"` to the wrapping div. We could suggest also adding a `data-docsearch="toc"` to the element wrapping the sidebar/table of content, and `data-docsearch="current"` on the sidebar link to the current page. 

I actually wonder if we shouldn't actually allow for attributes that are mirrorring the selectors, like `data-docsearch="lvl0"`, `data-docsearch="lvl1"`. But that might be opening too many questions and issues for now.

**Comment by s-pace** [comment]
solves by #512

Let's start with promoting the className cc https://github.com/algolia/docsearch/blob/master/docs/src/required-configuration.md
