### ISSUE TITLE
Adding an "Edit this page" link on documentation pages

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#421]
**Do you want to request a *feature* or report a *bug*?**

We should add an "Edit this page" link on all doc pages, to help everyone contribute to the docs.

**Comment by s-pace** [comment]
+1

**Comment by Shipow** [comment]
https://github.com/algolia/docsearch/commit/c0076f996255b58716927340e41ab01eae7b3823

**Comment by s-pace** [comment]
👏
