### ISSUE TITLE
Adding a way to browse more results

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#424]
A user is frustrated about the fact that it's not possible to see more than 5 results. He would have preferred a way to browse through all results, for cases when either he does not yet know what to search for, or too many pages have the matching word.

![image](https://user-images.githubusercontent.com/283419/44617243-99c53d80-a85f-11e8-97f3-b99fa6a492ee.png)
![image](https://user-images.githubusercontent.com/283419/44617250-a47fd280-a85f-11e8-9caa-bdc6e9d8953b.png)
https://twitter.com/LiamHammett/status/1033055417427996673

I'm unsure how we could fix that in a generic format. A "Show more" on the dropdown is something we could add for sure, but where would the additional results be loaded? In the dropdown it might not be practical to scroll through them, so it might require its own page on the website, which is doable but a larger project.

Maybe that's a way to try out a full page search feature of DocSearch?

**Comment by s-pace** [comment]
👋 

What about [using `hitsPerPage`?](https://community.algolia.com/docsearch/behavior.html#algoliaoptions)

**Comment by s-pace** [comment]
Closing it after inactivity. Feel free to re open it if needed

**Comment by telamonian** [comment]
I'll add a vote for adding some way to page through all of the actual results. There are plenty of cases where 5 results is not sufficient to find what you're actually looking for.

For example:

This is a current pain point in the [Helm docs](https://helm.sh/docs/). I remember there's instruction somewhere for how to use `kubectl` to do the equivalent of various `helm` commands, but all 5 of the results that show up for `kubectl` are non-relevant
