### ISSUE TITLE
[Documentation] Run your own without docker 

### ISSUE THREAD

**Issue by PierreR** [algolia/docsearch#449]
The [installation section](https://community.algolia.com/docsearch/run-your-own.html#installation) of the 'Run Your Own" implies that it is possible to run `docsearch` without using docker. 

There is nothing that seems to describe how to do so. The only way seems to look at the source of the docker files and write  a script to mimic parts of it.

Is that correct ? Could the documentation be improved to make it more explicit ? 

Thanks.

**Comment by lubos** [comment]
I'm running docsearch without Docker. I have a script which runs once a day and updates data in the exact format Docker instance would.

There are only 3 attributes each object needs to be compatible with docsearch

```
"content": "string",
"hierarchy": {
    "lvl0": "string",
    "lvl1": "string",
    "lvl2": "string"
},
"url": "string"
```

**Comment by PierreR** [comment]
@s-pace That is what I ended up doing. My biggest confusion has been that you can't run the `docker:run` command unless you have python installed with the following requirement:

- future
- python-dotenv
- requests

In retrospect, this is rather obvious but it is a source of confusion when you are using a system such as nixos where you learn to be quite explicit about your dependencies.

**Comment by PierreR** [comment]
@pixelastic Thanks for the info. As you said,, python dependencies can be quite tricky. Particularly in this case because the requirement.txt file involves a lot of circular dependencies when you try to convert it into a `requirement.nix` file. I had to use the docker and I am quite happy about it.

**Comment by pixelastic** [comment]
> My biggest confusion has been that you can't run the docker:run command unless you have python installed.

Yes, this is an issue we didn't realized until recently. We will try to make the Docker usage completely stand-alone in the future.

> when you are using a system such as nixos where you learn to be quite explicit about your dependencies.

For the record, we are also getting quite frustrated with the setup and are in the process of moving the dependency handling to pipenv. No ETA for that though, but we'll keep you updated and make sure the documentation is updated as well.

**Comment by s-pace** [comment]
https://github.com/algolia/docsearch/pull/546
