### ISSUE TITLE
Problems with Dropdown when position: sticky

### ISSUE THREAD

**Issue by jankoenig** [algolia/docsearch#473]
Hi there, thanks a lot for this great service! Really love what Algolia is doing.

At Jovo, we're using a sticky left sidebar, which causes problems with the Docsearch dropdown.

Here is how it looks like in our docs: https://www.jovo.tech/docs/
![Docsearch dropdown](https://media.giphy.com/media/57Y4nNzm2aC6F6iA3V/giphy.gif)

I've tried a lot of different things but couldn't get it to work. Have you seen a similar issue and now the problem?

Thanks a lot!
Jan

**Comment by s-pace** [comment]
👋 @jankoenig 

Could you add the following css-rules:
```css
. docs .sidebar-left-wrapper{
overflow: visible
}
```
You need to change the [overflow settings](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) from the container of your search input.

**Comment by jankoenig** [comment]
Thank you @s-pace.

I tried it but it didn't work. Just updated the code as well: https://www.jovo.tech/docs/

When I remove "position: sticky", it works. However, then the whole sidebar isn't working as expected anymore.

We just played with it, and @aswetlow came up with the idea to use Javascript to move the dropdown out of the surrounding sidebar:

```js
$('body').append($('.ds-dropdown-menu'));

$('.ds-input').on('input', function() {
   $('.ds-dropdown-menu').css('top', $('.algolia-autocomplete').offset().top + 'px');
   $('.ds-dropdown-menu').css('left', $('.algolia-autocomplete').offset().left + 'px');
});
```

However, then the problem is that the dropdown isn't rendered correctly.

**Comment by s-pace** [comment]
I would recommend you to create a row for the search input and another for the rest of the sidebar.
The first row will only have the dropdown with an `overflow` property set to visible while the second row will have the same behaviour as today.
Is it conceivable to do so?
