### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by alisonjoseph** [algolia/docsearch#498]
On https://www.carbondesignsystem.com/ a lot of our results seem duplicated 3x. The original generated config file was from our old website so I attempted to modify the config to work for this html structure but it seems I've messed it up somehow.

<img width="510" alt="screen shot 2018-10-10 at 8 23 57 am" src="https://user-images.githubusercontent.com/2753488/46739410-1c665880-cc66-11e8-86af-22fc013be622.png">

Also is there a way to prevent it from crawling svgs? see below
<img width="505" alt="screen shot 2018-10-10 at 8 24 06 am" src="https://user-images.githubusercontent.com/2753488/46739425-22f4d000-cc66-11e8-9de3-560a37cd3f2f.png">

**Comment by s-pace** [comment]
👋  @alisonjoseph ,

Thank you for sharing.

It looks like we have some errors when crawling your website from time to time. See below:
![image](https://user-images.githubusercontent.com/32097720/46787386-b8ac6000-cd37-11e8-86fe-25402ebf073e.png)

It will not raised an error but your crawl might be incomplete. Please try to fix it.

Your previous issue is solved by the previous commit. Happy to explain the changes if you need comment them :)

**Comment by s-pace** [comment]
Changes are live and deploy, please only care about the last reference

**Comment by alisonjoseph** [comment]
Thanks, we were struggling with some issues with our hosting provider yesterday causing the site to go up and down. 😞

**Comment by s-pace** [comment]
No problem

**Comment by s-pace** [comment]
Looks like this issue is still here
