### ISSUE TITLE
Links to non-existent pages in search results

### ISSUE THREAD

**Issue by koheiw** [algolia/docsearch#499]
**Do you want to request a *feature* or report a *bug*?**
Potentially a bug or misconfiguration

**What is the current behavior?**
Docsearch results are linked to non-existent pages. For example,
https://quanteda.io/undefined?q=tokens#select-tokens
https://quanteda.io/reference/undefined?q=dfm#section-text-statistics
To reporduce, go to https://quanteda.io/ and search for 'tokens' or 'dfm', and click one of the results.

I suspect that this issue is related to the recent change in the root URL of the website.
https://github.com/algolia/docsearch-configs/pull/588

**What is the expected behavior?**
Do not show links to pages that do not exist.

**Comment by s-pace** [comment]
👋 @koheiw,

Thanks for the details. Changes are deploy and already live.

Happy to have your feedback.

Have a great day,

Cheers

**Comment by koheiw** [comment]
Thanks for fixing and optimizing the setting. Working excellent.
