### ISSUE TITLE
Remove the url+anchor concatenation

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#53]
There is something confusing with the way we store the `url` and `anchor`.

The scraper index both a `anchor` field and a `url` one, but the `url` already contains the anchor. We do that because we're doing a `distinct` on the `url`. But the JS client also concatenate the `url` and `anchor`, which results in weird things.

I think we should:
- Remove the `anchor` field from the scraper
- Remove the concatenation from the JS client

**Comment by bobylito** [comment]
On it!
