### ISSUE TITLE
Automated release changelog broken

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#530]
I just did the 2.6 release and realized that the generated changelog is partly broken:

- It picks up the commit messages of the format `type(foo): blah blah` to order features, bugfixes, etc. The thing is that we rarely follow this pattern, thus the changelog is mostly empty even if we added interesting features.
- Renovates does follow this pattern, though, so our changelog is now filled with renovate telling us all about all the dependencies it upgraded (which is not very helpful)
- It also picks up commits that modify the documentation, including renovate updating dependencies in the documentation (which is even less useful).

In order to make sure we always follow the right format, we need some tooling to do that job for us. I think other teams (IS maybe) are using git hooks to format the commit names automatically, or at least warn when they will not be picked by the changelog. Also, because we add most features through PR, we could add a PR check that would only validate PRs that follow the pattern. I know it can be a pain to have your commit rejected because you didn't follow a specific pattern, so we need to make this clever enough so it speeds us up instead of slowing us down.

As for picking up the commits in the `./docs` folder, I don't know how to avoid that. To be honest I already had to come up with some complex logic in the `./docs` folder so it could have its own set of git hooks and tooling without interfering with the host. And the more I think of it, the more I feel that having both the `DocSearch.js` code and the overall documentation in the main repo is the main issue. For TalkSearch, I have a `talksearch.js` repo, a `talksearch-scraper` repo and a generic `talksearch` repo with the doc. I think it would be the best split.

**Comment by s-pace** [comment]
Will be solved using docusaurus
