### ISSUE TITLE
postinstall script is broken

### ISSUE THREAD

**Issue by Meesayen** [algolia/docsearch#531]
Hi,

the `postinstall` script of v2.6.0 seems to be broken.

```
> docsearch.js@2.6.0 postinstall /mmmmmmmm/node_modules/docsearch.js
> cd ./docs && yarn install

sh: line 0: cd: ./docs: No such file or directory
```

**Comment by Haroenv** [comment]
You're right, this seems to be something that @pixelastic added for internal things for the library, not while installing the library. Instead that should probably have been `prepublishOnly` :)

**Comment by pixelastic** [comment]
Erf, I **hate** that `postinstall` triggers both when installing a package as a dependency, and when calling `yarn install` from a repo you're developing. This was of course meant for the latter case and shouldn't have been release.

I'm going to release 2.6.1 with it removed.
