### ISSUE TITLE
Ctrl+Click on suggestion should open result in new tab, even if using custom `handleSelected`

### ISSUE THREAD

**Issue by dima74** [algolia/docsearch#588]
**Do you want to request a _feature_ or report a _bug_?**
bug

**Steps to reproduce**
Assume the following code (copied from [documentation](https://community.algolia.com/docsearch/behavior.html#handleselected)):
<pre><code>docsearch({
  […],
  handleSelected: function(input, event, suggestion, datasetNumber, context) {
    // Do nothing if click on the suggestion, as it's already a &lt;a href&gt;, the
    // browser will take care of it. <b>This allow Ctrl-Clicking on results and not
    // having the main window being redirected as well</b>
    if (context.selectionMethod === 'click') {
      return;
    }

    ...
  }
});
</code></pre>
Then search for anything and Ctrl+Click on suggestion.

**What is the current behavior?**
Link is opened in current tab.

**What is the expected behavior?**
Link is opened in new tab.

**Proposed solution**
The problem is that if custom `handleSelected` is used, then [algolia prevents all clicks on `.algolia-autocomplete`](https://github.com/algolia/docsearch/blob/6e933604fb86ac22e6d71309fa29f600ab022fae/src/lib/DocSearch.js#L108-L113). I propose to prevent click only when it is normal click (not Ctrl+Click), or even ignore custom `handleSelected` when it is Ctrl+Click (or add option for one of those behaviours)

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle][3] example or a repository on GitHub that we can `npm install`
and `npm start`.**
Sorry, I can't create minimal reproduction, because I can't find any instructions for creating it (maybe you will add such instructions, for example premade codepen template (with entered APPLICATION_ID), so that someone who wants to report a bug will just fork this codepen...)

[1]: https://github.com/algolia/docsearch-configs
[2]: https://community.algolia.com/docsearch/config-file.html
[3]: (https://jsfiddle.net/)

Thank you.

**Comment by s-pace** [comment]
thank you for reporting it @dima74 

 Do the changes introduces by the PR #590 sounds appropriate to you?

**Comment by dima74** [comment]
Thank you for answer @s-pace

Though that PR makes documentation correct, now it is unclear to developers how to implement "Opening autocomplete result in new browser tab, when using custom handleSelected", and I think that such functionality is very common.

Why not, for example, ignore `handleSelect` and open link in new tab when ctrl+click on it? (Or, probably, add option for such behavior).

Thank you.

**Comment by dima74** [comment]
Modified issue in order to better illustrate the problem.
