### ISSUE TITLE
申请之后，大概多久可以得到回复？

### ISSUE THREAD

**Issue by liushaozhen** [algolia/docsearch#598]
您好，我申请之后已经过去两周，没有收到消息？ 
申请的网址如下  http://bee.tinper.org/   
请问是网址有什么问题嘛？ 多谢

**Comment by Haroenv** [comment]
It might take a bit longer now, since some of the team members have been on holiday. Another option is that the messages were not understood because it wasn’t sent in English and our team doesn’t include anyone speaking mandarin.

**Comment by s-pace** [comment]
Hi @liushaozhen ,

Sorry for the delay. We have followed up to your request by sending you an email to your @yonyou.com email address.

This repo is not intended to handle individual requests. It is intended to help with any front end UI issues or improvement of our documentation.

I close this conversation and let you contact us by email instead.

**Comment by liushaozhen** [comment]
I got the message. Thank you.
