### ISSUE TITLE
JSDeliver serves a truncated script

### ISSUE THREAD

**Issue by szepeviktor** [algolia/docsearch#607]
https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js

On my end it ends `;var draining;v`

Could be a CDN or a minification error.
Please advise.

**Comment by szepeviktor** [comment]
@nunomaduro ?

**Comment by MartinKolarik** [comment]
@szepeviktor please try again now

**Comment by szepeviktor** [comment]
@MartinKolarik **Thank you**

end with `exports.default=utils}])});` :)

What _was_ the problem?
