### ISSUE TITLE
Quickest way to get a search bar on a website

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch#619]
- _What is the dropdown version you are using?_ What is this?
- _What is the scraper version you are using?_ Latest
- _Could you share us the configuration file you are using?_ 
```
{
  "index_name": "my-index",
  "start_urls": [
    {
      "url": "http://127.0.0.1/docs/"
    }
  ],
  "selectors": {
    "default": {
      "lvl0": "h1",
      "lvl1": "h2",
      "lvl2": "h3",
      "lvl3": "h4",
      "lvl4": "h5",
      "text": "p, li"
    }
  }
}
```

I'm trying to add a standard text search input to my private website.

I'm using the scraper to index my website which is not public. That works ✅ 
I'm now encountering problems to add a search field. 😞 

I have a search field on a separate page, that displays a lot of results by default, e-com style, and that has no styling even though i've imported the aloglia css. 

I just need a seach box just like all the websites of the Docsearch project with the dropdown. Is there a way to quickly do that?

Can you provide templates that I can copy paste?
I've been trying to customize the styling but I feel like I'm reinventing the wheel and wasting a lot of time. There has to be something simpler.

Thank you in advance

**Comment by Haroenv** [comment]
Does this page answer your question? https://community.algolia.com/docsearch/dropdown.html

**Comment by ArthurFlageul** [comment]
Hi @Haroenv,

I was noodling with instantsearch.js but it seems dropdown is what i needed. There's a bunch of libraries, it's not easy to understand which are the best for this or that situation. 

Anyway, I got my search running in 5 minutes with this tool... That's awesome! Thanks a lot 👍
