### ISSUE TITLE
Does docSearch support Sphinx Documenation?

### ISSUE THREAD

**Issue by EfstathiadisDimitris** [algolia/docsearch#620]
This may not be, the right place for asking this, but I was not able to get an answer anywhere else. I have a question. Can DocSearch be implemented in a Spinx Website for Docs.

We use Sphinx, and thinking of adding docSearch to ur docs website. My thinking is that if JS, is supported somehow, which it does for Sphinx, it would be easy to integrate DocSearch to it. But can you please confirm it? Thanks!! If not, a timetable for support?

**Comment by Haroenv** [comment]
This should work, as long as you're able to add JS to the page it should be fine.

**Comment by s-pace** [comment]
You can try to see how you can quickly integrate within your website by using [this demo snippet](https://community.algolia.com/docsearch/dropdown.html).

We have feature some Sphinx website in the past so I do not think it should be an issue.

**Comment by EfstathiadisDimitris** [comment]
Thank you guys. This was my impression as well. Just wanted to be sure, before we invest time into it. Will close this for now, and probably make a guide for it if more people wondering the same.

**Comment by s-pace** [comment]
Thanks, for the record, you can find an example of DocSearch integrated within a website using Sphinx [here](https://github.com/coala/documentation/pull/464).
