### ISSUE TITLE
Edit the HREF of each search result

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch#621]
## Feature: Ability to edit the url/href of each search result.

Each link is built based on the index config file. In my case, the urls i'm indexing are all `http://127.0.0.1...` (I crawl my docs locally). Then when I want to use my index in production, the links are obviously broken in UI. 

I've tried modifying the url in Jquery to replace my urls by my production host but it does not seem to work. 

Is there a way to do this properly?

**Comment by s-pace** [comment]
Did you try to use [the transformdata method](https://community.algolia.com/docsearch/behavior.html#transformdata)?

You can find a [bootstrap example here](https://jsfiddle.net/s_pace/oqL5xch6/2/).

**Comment by ArthurFlageul** [comment]
Perfect! Thanks a lot 👍
