### ISSUE TITLE
DocSearch doesn't work on Sphinx Integration on localhost and deployed dev environment

### ISSUE THREAD

**Issue by EfstathiadisD** [algolia/docsearch#636]
Hey guys. I am having a little bit of trouble integrating your service with our Sphinx Docs. But first I have a question. If I target the right `css-selector`, and the `docSearch` playground works correctly, it means that I should be able to see the Algolia Dropodown:

- On Development, on localhost? (Not currently showing up)
- On our deployed development playground, not the official one. (Not showing up)
- On our official website (Haven't tried it yet.

Now to what I did up until now:

In my Layout.html, my main import for css-files and js snippets I did:
```
{% set css_files = css_files + ["https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css", "_static/custom.css"] %}
<link src="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
    apiKey: '<MyApiKey>',
    indexName: '<MyIndexName>',
    inputSelector: '<MyCssInputSelector>,
    algoliaOptions: { 'facetFilters': ["version:v2.2"] },
    debug: false // Set debug to true if you want to inspect the dropdown 
  }); 
</script>
```
I am thinking that I need to deactivate my sphinx-search first. Maybe the issue lies there...

As I said, I am using Sphinx currently, and this is the steps I took to integrate. Do you see any problem with this? I am looking at a similar documentation website with Sphinx, and I see an Algolia Tag, surrounding, the input element, which I do not see in my implementation.

I would appreciate if you answered my question regarding usage and deployments, and how to fix it. Thank yo!!

**Comment by s-pace** [comment]
👋 @EfstathiadisD,

Could you share with us the following informations:
- Which index are you using? Is it an hosted one (if so, please provide a link [to its related configuration](https://github.com/algolia/docsearch-configs))
- Are you sure the JS DocSearch script is run after the targeted element by `<MyCssInputSelector>` is rendered? Please share an example of the selector you are using along with an example of the targeted element.
- Can you inject the CSS library at the end of your `<head/>` element instead? Same for both `<script/>` tags, you should integrate them at the end of your `<body/>` tag.
- Do you have any issue/warning displayed within your console?

The Algolia tag is created once the JS function `docsearch()` is run. It should not be an issue.

**Comment by s-pace** [comment]
Closing it since it is a personal issue and it didn't had any activity for more than 3 weeks

Feel free to reopen it if needed.
