### ISSUE TITLE
[Documentation] How to add synonyms to docsearch

### ISSUE THREAD

**Issue by jschuler** [algolia/docsearch#640]
I couldn't find accurate information on how to add synonyms to DocSearch. Can this info be added to the documentation?

**Comment by s-pace** [comment]
👋 @jschuler,

With DocSearch, you can define regular one word synonyms from your configuration thanks to the [`custom_settings` parameter](https://community.algolia.com/docsearch/config-file.html#custom_settings-optional). It needs to include a `synonyms` key that is an array of synonyms (up to 20 elements). Each element is an array of multiple unique word having the same meaning.

For example:
```json
"custom_settings": {
    "synonyms": [
      [
        "caching",
        "revisioning",
        "versioning",
        "hashing",
        "renaming",
        "revving"
      ]
    ]
  },
```

Please note that you can leverage a more advanced usage of [synonym thanks to Algolia](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/). You will need to use your own tool to push data into your owned index.

**Comment by akotlar** [comment]
> You will need to use your own tool to push data into your owned index.

Could you expand on this? I don't see an index config in my dashboard, and I don't seem to be able to use the index.saveSynoyms client function (get 403 forbidden, cannot use this method with this API key)

**Comment by s-pace** [comment]
I mean that you will need to use Algolia on your own with your own plan and [by following these instructions](https://docsearch.algolia.com/docs/run-your-own/)

You do not need to use the client but you should use the configuration via the `custom_settings` setting as described above.

The key you get is a searchOnly key. You will not be able to edit the index.

**Comment by akotlar** [comment]
> You will not be able to edit the index.

It looks to be more restrictive than that. I cannot even query index settings (getSettings 403's)

**Comment by s-pace** [comment]
Yes it is searchOnly.

Why do you want to have the settings?

**Comment by akotlar** [comment]
To understand how the documents are indexed to help us identify settings that may be suboptimal.

**Comment by s-pace** [comment]
Here are your settings:
```json
advancedSyntax: true
allowTyposOnNumericTokens: false
alternativesAsExact: (2) ["ignorePlurals", "singleWordSynonym"]
attributeCriteriaComputedByMinProximity: true
attributeForDistinct: "url"
attributesForFaceting: (3) ["tags", "no_variables", "extra_attributes"]
attributesToHighlight: (3) ["hierarchy", "hierarchy_camel", "content"]
attributesToIndex: (25) ["unordered(hierarchy_radio_camel.lvl0)", "unordered(hierarchy_radio.lvl0)", "unordered(hierarchy_radio_camel.lvl1)", "unordered(hierarchy_radio.lvl1)", "unordered(hierarchy_radio_camel.lvl2)", "unordered(hierarchy_radio.lvl2)", "unordered(hierarchy_radio_camel.lvl3)", "unordered(hierarchy_radio.lvl3)", "unordered(hierarchy_radio_camel.lvl4)", "unordered(hierarchy_radio.lvl4)", "unordered(hierarchy_radio_camel.lvl5)", "unordered(hierarchy_radio.lvl5)", "unordered(hierarchy_camel.lvl0)", "unordered(hierarchy.lvl0)", "unordered(hierarchy_camel.lvl1)", "unordered(hierarchy.lvl1)", "unordered(hierarchy_camel.lvl2)", "unordered(hierarchy.lvl2)", "unordered(hierarchy_camel.lvl3)", "unordered(hierarchy.lvl3)", "unordered(hierarchy_camel.lvl4)", "unordered(hierarchy.lvl4)", "unordered(hierarchy_camel.lvl5)", "unordered(hierarchy.lvl5)", "content"]
attributesToRetrieve: (4) ["hierarchy", "content", "anchor", "url"]
attributesToSnippet: ["content:10"]
camelCaseAttributes: (3) ["hierarchy", "hierarchy_radio", "content"]
customRanking: (3) ["desc(weight.page_rank)", "desc(weight.level)", "asc(weight.position)"]
distinct: true
exactOnSingleWordQuery: "attribute"
highlightPostTag: "</span>"
highlightPreTag: "<span class="algolia-docsearch-suggestion--highlight">"
hitsPerPage: 20
ignorePlurals: true
maxValuesPerFacet: 100
minProximity: 1
minWordSizefor1Typo: 3
minWordSizefor2Typos: 7
numericAttributesToIndex: null
optionalWords: null
paginationLimitedTo: 1000
queryType: "prefixLast"
ranking: (7) ["words", "filters", "typo", "attribute", "proximity", "exact", "custom"]
removeWordsIfNoResults: "allOptional"
separatorsToIndex: ""
snippetEllipsisText: ""
unretrievableAttributes: null
}
```
