### ISSUE TITLE
Cannot use links in the generated documentation

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch#65]
The documentation page displayed on the website is created from the `README`, by splitting it on specific patterns.

Unfortunatly, when defining links with a syntax of `[my link][42]`, the reference to `[42]` is defined at the end of the file, and stripped from the extraction.

@Jerskouille do you have an idea on how to hack the `build-docs` script to do that?

**Comment by aseure** [comment]
What's our Markdown preprocessor?

**Comment by Shipow** [comment]
I think it's MaRuKu
