### ISSUE TITLE
https://cdn.jsdelivr.net  Certificate expired。 Maybe you need to update the document？

### ISSUE THREAD

**Issue by liushaozhen** [algolia/docsearch#659]
9:00 pm ( SGT)。 https://cdn.jsdelivr.net  Certificate expired。  
Maybe you need to update the document？

**Comment by s-pace** [comment]
Could you provide an example please?

**Comment by liushaozhen** [comment]
https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js
，https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css

The two addresses had problems on April 20, 2019, Beijing time, but they have now been repaired.
