### ISSUE TITLE
Cmd+F / Ctrl+F keybinding

### ISSUE THREAD

**Issue by debopamsengupta** [algolia/docsearch#69]
Would be great to jump directly to DocSearch using the default search key combinations.

**Comment by pixelastic** [comment]
Hello,

This kind of keybinding would overwrite the default browser keybindings and I'm not keen on overwriting something the user is very familiar with.

I'm not saying it's a bad idea, feel free to add the required JavaScript to your page to do it if you want, but  I don't think I'll add it to the library.

**Comment by vvo** [comment]
One common keybinding for a searchbox on multiple websites/interfaces for "hackers" is "/". Just "/" when the searchbox is not focused should trigger the searchbox.

That's the default behavior on gmail for example. Github is using "s", we could support it also.

**Comment by acorncom** [comment]
This issue apparently got resolved by a commit above but wasn't properly closed ...

**Comment by maxiloc** [comment]
Indeed we can close this one
