### ISSUE TITLE
Configure the base URL for search results on a per-environment basis

### ISSUE THREAD

**Issue by lavelle** [algolia/docsearch#732]
Hi there,

We're using DocSearch for our docs at https://thumbprint.design/, and we were wondering if it was possible to change the search results to work locally to. When running a copy of our docs on localhost, the links in the search results still redirect to the production docs. If there were a way to tell it to use https://localhost:8090 instead of https://thumbprint.design/, we could use search to jump to pages in development too. Obviously it wouldn't work for new pages since they haven't been crawled, but jumping to existing pages would still be useful.

Thanks!

**Comment by s-pace** [comment]
Just change the URL thanks to [transformdata](https://community.algolia.com/docsearch/behavior.html#transformdata)
