### ISSUE TITLE
Does nothing if inputSelector finds 2 or more tags

### ISSUE THREAD

**Issue by ElPicador** [algolia/docsearch#74]
If there is in the page 2 or more selectors that matches `inputSelector` it does nothing.

**Comment by pixelastic** [comment]
What would be the best behavior for you?

Code-wise, the easiest would be to enable docsearch only on the first one. The library does not react really well to multiple inputs.

**Comment by vvo** [comment]
We should throw so that we are explicit and the user can see he made a mistake.

**Comment by vvo** [comment]
If it's already failing then it's the easiest to throw explicit error?

**Comment by ElPicador** [comment]
I would throw and error, but enable on the first one

**Comment by pixelastic** [comment]
Ok, I'll have a look at that

**Comment by vvo** [comment]
I would really throw and explain to the user he made something bad. Fixing bugs for him will bite you :D

**Comment by pixelastic** [comment]
@vvo @ElPicador I've submitted the PR here: https://github.com/algolia/docsearch/pull/80

It will know throw an error if there is not exactly one input matching

**Comment by redox** [comment]
For the record, that was a bug of autocomplete.js's standalone version (Zepto based): it has been fixed - not yet release - and you can now setup your dropdown menu on several search bars.

**Comment by pixelastic** [comment]
So we can close this issue?

**Comment by redox** [comment]
Once we've upgraded to `autocomplete.js=0.17.2` only.
