### ISSUE TITLE
Road to self-serve

### ISSUE THREAD

**Issue by AntoinePlu** [algolia/docsearch#75]
With the team we decided to improve the design of DocSearch and how can let you customize the UI in an easy way. This redesign will include:
- New design of the dropdown
- Dropdown configurator

**Idea**

This configurator will give you the ability for to customize the design of the dropdown on top of your website without having a developed sense of design or doing some CSS. We know, only a very small pourcentage of our users are going beyond what we provide by default ([Exception example: Apiary](https://help.apiary.io)). We'll let advanced users editing their code by using Jsfiddle and/or opening files export.

**Where are we in this process and what will be next steps?**
- [x] Define current issues
- [x] Understand and analyze the needs
- [x] Explore different layouts **[WIP]**
- [x] Build Generator UI **[WIP]**
- [x] Define dropdown layouts **[WIP]**
- [ ] Create category icons
- [ ] Create breadcrumb icons
- [ ] Collect feedback
- [ ] Define generator rules
- more coming...

---

**[WIP] Generator UI**

![DocSearch Editor Theme](http://f.cl.ly/items/231v1n1h1K3x1w1z2L2g/Generator-1.png)

![DocSearch Editor Layout](http://f.cl.ly/items/3b1L2M423O0V1x1q0t06/Generator-2.png)

![DocSearch Editor Content](http://f.cl.ly/items/0P0K0d3W2r2W2o3j2l1O/Generator-3.png)

**Comment by Shipow** [comment]
:+1:

**Comment by maxiloc** [comment]
:+1:

**Comment by pixelastic** [comment]
Really nice. Keep it up!

**Comment by proudlygeek** [comment]
Cool stuff :+1:

**Comment by ElPicador** [comment]
Isn't it done?
