### ISSUE TITLE
Chrome version must be between 70 and 73

### ISSUE THREAD

**Issue by csi-lk** [algolia/docsearch#768]
"Running my own" DocSearch using the provided dockerfile

```bash
docker run -it --env-file=.env -e "CONFIG=$(cat angolia-config.json | jq -r tostring)" algolia/docsearch-scraper
```

with config (aside from all the required stuff)

```js
  "js_render": true,
  "use_anchors": true
```

produces error
```bash
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.9.125-linuxkit x86_64)
```

Looks like `73.0.3683.68` > `73`

Should be as simple as updating the dockerfile unless i'm missing something obvious

**Comment by s-pace** [comment]
👋 @csi-lk 

The latest image was out of sync with the latest version. I [have updated it and pushed it](https://hub.docker.com/r/algolia/docsearch-scraper). Should be fixed.

Feel free to reopen if needed.

**Comment by lesliecdubs** [comment]
This response wasn't super clear, so thought I'd share what worked for me. 

To fix the Chrome version error, I needed to pull the v1.3.1 tagged version by running the following: ```docker pull algolia/docsearch-scraper:v1.3.1```

**Comment by s-pace** [comment]
Thanks for sharing @lesliecdubs 

The latest tag should have been the `v1.3.1`. I have updated it accordingly. For now `latest`=`v1.3.1`
