### ISSUE TITLE
Pressing enter in search box only refreshes current page

### ISSUE THREAD

**Issue by chrisvfritz** [algolia/docsearch#81]
### What's happening

When typing something in the search (for example at [vuejs.org/guide/](http://vuejs.org/guide/)), a dropdown of results appear. I can click on items listed in the dropdown, but if I press _Enter_, the dropdown disappears and the page is refreshed.

### What I expect to happen

When pressing _Enter_, it would make sense to me if the top result in the search were navigated to, instead of refreshing the current page. If there's no top result, nothing should happen.

**Comment by maxiloc** [comment]
Indeed this is not expected. Thanks for reporting it
