### ISSUE TITLE
index.setSettings and index.getSettings are not functions

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch#849]
The algolia packages I used are:

`https://cdn.jsdelivr.net/algoliasearch/3/algoliasearchLite.min.js`,
`https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js`,

My indexName is `pingcap`, I follow the instruction [here](https://www.algolia.com/doc/api-reference/api-methods/search/#search) to init the `index` and `client`, I can use the `search` function, but cannot use `setSettings` and `getSettings`, it always returns the error `TypeError: n.getSettings is not a function`. 

 ```
let urlParams = new URLSearchParams(window.location.search)
  if (urlParams.has('q')) {
    const client = algoliasearch('appId', 'apiKeys');
    const index = client.initIndex('index_name');
    console.log('index, client', client, index)

    index.getSettings((err, content) => {
      console.log(content);
    })

    index.search(
      {
        query: urlParams.get('q'),
        hitsPerPage: 10,
        facetFilters: ['tags: cn'],
      },

      (err, {hits} = {}) => {
        if(err) throw err;

        console.log('hits are:', hits)
       
      }
    )
```

Could you please let me know why I get this error? Thanks!

@s-pace

**Comment by Haroenv** [comment]
getSettings & setSettings are methods which require an elevated API key, not just a search API key. This means that it's suited better for scripts, than websites (where people can steal your API key). 

If regardless of that the settings still should be changed, use `algoliasearch`, not `algoliasearchLite`

**Comment by YiniXu9506** [comment]
@Haroenv Thanks, but how can I get the elevated API key?

**Comment by s-pace** [comment]
@YiniXu9506 you can get an elevated API key by using the Algolia dashboard. You can check [this section of the Algolia documentation.](https://www.algolia.com/doc/guides/security/api-keys/).

**Comment by YiniXu9506** [comment]
@s-pace Got it! Thanks!
