### ISSUE TITLE
Search is working on my site but the search results are not coming.

### ISSUE THREAD

**Issue by chandraguntamukkala** [algolia/docsearch#856]
Search is working on my site http://docs.sumopayroll.com but the search results are not coming. Please help me and do the needful.
![Screenshot from 2019-09-12 18-39-15](https://user-images.githubusercontent.com/15013592/65888985-165d1080-e3be-11e9-8061-84a78dfb1d8d.png)

**Comment by s-pace** [comment]
Please comply with the ISSUE_TEMPLATE defined in this repo. Share/explain the steps you have undertaken to fix this issue.

I have checked you crawl and your DocSearch index is correctly built. 

Closing until this issue complies with the guidelines defined.
