### ISSUE TITLE
yarn run test failure: "Plugin/Preset files are not allowed to export objects"

### ISSUE THREAD

**Issue by trauts2** [algolia/docsearch#875]
Latest codebase from git.  

`% yarn run test
yarn run v1.19.1
$ ./scripts/test
 FAIL  src/lib/__tests__/DocSearch-test.js
  ● Test suite failed to run

    Plugin/Preset files are not allowed to export objects, only functions. In /Users/stu/projects/foundry/sitegen/docsearchGit/node_modules/babel-preset-stage-3/lib/index.js

      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
      at node_modules/@babel/core/lib/config/config-descriptors.js:109:50
          at Array.map (<anonymous>)`

Thanks,

Stu

**Comment by Haroenv** [comment]
Is this while running the tests in this repository?

**Comment by trauts2** [comment]
Yes.  I see this when I run "yarn run test"

**Comment by Haroenv** [comment]
I’m just wondering what you are running the tests for. If it’s for contributing a pull request, you will be able to rely on continuous integration instead of testing locally

**Comment by s-pace** [comment]
Hi @trauts2 

Thanks for sharing your situation.

Could you provide more details and context so that we can better assist you? Why are you doing that? Can you share an environment to help us reproduce your issue?

We ultimately ask user to fill out [one of these templates](https://github.com/algolia/docsearch/tree/master/.github/ISSUE_TEMPLATE) to help them in the best way. Could you fill out one of these templates please?

Thank you

**Comment by trauts2** [comment]
> I’m just wondering what you are running the tests for. If it’s for contributing a pull request, you will be able to rely on continuous integration instead of testing locally

My use case is making a modification to docsearch UI's display of results.  I see this error when I run

yarn run build:js

**Comment by trauts2** [comment]
Hi Sylvain,

Is there a docker container I could use to perform the build rather than
setup my environment?  No doubt this is an environment issue on my end.  Or
pipenv maybe?  It probably isn't worth troubleshooting my build environment
if there's an option like this ready.

I'd like to make some changes to docsearch for my use case.

Thanks for the help!

Stu

**Comment by s-pace** [comment]
👋 @trauts2 

There is no docker container available to perform the build. Please note that pipenv is only needed when you want to [run the DocSearch crawler](https://github.com/algolia/docsearch-scraper). This is completely out of the scope of your use-case if I get it correctly. You should not use python in such regards. You only need to focus on this repo algolia/docsearch

Closing this issue as it is an issue related to an individual setup. Feel free to reach out docsearch@algolia.com if you have any questions.
