### ISSUE TITLE
Second input doesn't work

### ISSUE THREAD

**Issue by inwardmovement** [algolia/docsearch#925]
A similar issue (#74) has been closed 4 years ago, but I can't manage to make the dropdown work on the second input. The first input is in the header (only displayed on desktop) and the second one is in the navbar (only displayed on mobile).

You may have a look at the [repo](https://github.com/algosphere/algo-website/tree/develop)* and at the [website](https://preview-algo-website.netlify.com/).

*have a look at `/layouts/partials/`: `search-form.html` is imported in `header.html` and `nav.html`.

Am I doing something wrong? 😄

**Comment by Haroenv** [comment]
is it possible you are using the same id twice?

**Comment by inwardmovement** [comment]
Indeed, as I am calling the search form as a partial.
Should I make too different search forms with different IDs, and they will both be able to query the same index?

**Comment by Haroenv** [comment]
Yes, you need to pass both input selectors individually to docsearch, but a selector can only match a single id

**Comment by inwardmovement** [comment]
Ok, thanks!

**Comment by s-pace** [comment]
That's correct. Using the snippet two times will work. The next version of the search UI will fixed this limit. Cheers
