### ISSUE TITLE
Showcasing DocSearch on Docusaurus 2 website

### ISSUE THREAD

**Issue by yangshun** [algolia/docsearch#935]
Hi Algolia folks! We would like to add the [DocSearch website](https://docsearch.algolia.com/) to our [Docusaurus 2 showcase](https://v2.docusaurus.io/showcase). 

We're seeking approval before we do that, hopefully you will agree to that!

**Comment by francoischalifour** [comment]
For sure, go for it! 🙂

**Comment by s-pace** [comment]
Sure please do so. Thanks for the idea @yangshun. Hope to see you soon in flesh!

**Comment by yangshun** [comment]
> The source of the website is at algolia/docsearch-website.

Thanks for pointing me there. I should have created an issue there instead.

> Sure please do so. Thanks for the idea @yangshun. Hope to see you soon in flesh!

Yes I hope so too!

Thanks for the approval guys!
