### ISSUE TITLE
After setting facetFilter, still getting two duplicates and some versions do not work for search

### ISSUE THREAD

**Issue by Tulean** [algolia/docsearch#945]
**Is your issue related to your own DocSearch implementation?**

yes

On https://sdk.gooddata.com/gooddata-ui/ we are facing the same issue as https://github.com/algolia/docsearch/issues/498. I just created a PR in docsearch-configs and added `"custom_settings": {
    "attributesForFaceting": ["version"]
  }`. After that I configured my siteConfig.js file with `algoliaOptions: {
      facetFilters: ["version:VERSION"],
    },`. The search still returns 2x duplicate instead of 3x. In addition to that, search stopped working for all versions except the latest one and a version a couple generations older.

I read a couple issues related to this and there you suggested this: `"stop_urls": [".*(?<!/)$"]` for the duplicates; however, I am not sure what to do with the issue with the nonworking versions. Thank you for any suggestions.

**Comment by s-pace** [comment]
- Replace $VERSION with the version you want to search on. The list of possible version is extracted from your website. So as of today you have: 6.1.0, 6.2.0, 7.4.0

**Comment by s-pace** [comment]
It should be good. Your website seems to work well

**Comment by Tulean** [comment]
Hello thank you for your response. The list of possible versions should be definitely longer than that. Could you please tell me where did you get the list of possible versions?

**Comment by s-pace** [comment]
Just after the crawl. What are the missing versions?

**Comment by Tulean** [comment]
Hello, the missing versions are: "7.3.0", "7.2.0", "7.1.0", "7.0.0", "6.3.0", "6.0.0", "5.3.0", "5.2.0", "5.1.0", "5.0.0", "4.1.1". Search is working for the versions that you mentioned above; however, for the versions that I have listed, it is not working.

**Comment by s-pace** [comment]
Are they part if your sitemap?

**Comment by Tulean** [comment]
We don't have sitemap. What we use is docusaurus

**Comment by s-pace** [comment]
Docusaurus does have a sitemap

**Comment by Tulean** [comment]
Hello, so I finally found the sitemap and it does not seem that it is dependant on it. The versions are part of my sitemap.

**Comment by Tulean** [comment]
Do you have any idea where else I could configure it? It a bit weird that of all the versions, only three are detected.

**Comment by s-pace** [comment]
Make sure the sitemap is correctly built. I am not sure it is compliant. It should be to the way you link version together. New versions are not referring to old ones

**Comment by Tulean** [comment]
Could you please take a look at it to see if it is compliant? https://github.com/gooddata/gooddata-ui/tree/gh-pages. Thank you

**Comment by Tulean** [comment]
Thank you, I will let you know if this solved the problem.

**Comment by Tulean** [comment]
Hello, so I have tried to fix up the sitemap via https://github.com/gooddata/gooddata-ui/pull/296; however, the change did not help. The issue still persists where crawler does not seem to detect other versions other than 6.1.0, 6.2.0, 7.4.0. Do you have any other suggestions where could the issue be? Thank you in advance.

**Comment by s-pace** [comment]
The sitemap is still not compliant

**Comment by s-pace** [comment]
You haven't merged the sitemap fix

**Comment by Tulean** [comment]
Hello, what I did is that I created a http-server and tested the build with the updated sitemap fix. The issue still persisted.

**Comment by Tulean** [comment]
Just an update: your suggestion fixed the problem. We just had to wait until the crawl finished as you mentioned in DocSearch documentation that crawl goes through every 24h. Thank you

**Comment by Tulean** [comment]
Hello, so I have waited for the crawler to run through our site; however, it did not help. Do you have anything else in mind that might help with this issue?

**Comment by s-pace** [comment]
Yrs please provide a compliant sitemap :)

**Comment by Tulean** [comment]
Hello, sitemap has been already updated: https://github.com/gooddata/gooddata-ui/blob/gh-pages/sitemap.xml. The issue still persists.

**Comment by s-pace** [comment]
The sitemap is still not compliant.

What about https://github.com/gooddata/gooddata-ui/pull/296?

**Comment by Tulean** [comment]
We have changed the sitemap according to your suggestion in https://github.com/gooddata/gooddata-ui/pull/296. Could you please tell me what is still not compliant in the sitemap? Thank you

**Comment by s-pace** [comment]
My bad. Just a typo. Should be good now

**Comment by Tulean** [comment]
No worries. Hopefully this will work now. Should we expect for it to work by tomorrow? I know that the crawl activates once every 24hr, so I am not sure.

**Comment by s-pace** [comment]
I have ran it already. Just let me know

**Comment by Tulean** [comment]
The issue has been resolved. Thank you
