### ISSUE TITLE
DocSearch deletes previous analytics 

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch#946]
I have been indexing my website successfully for a few months, and I've just realized that the *Analytics* section in my Algolia account gets reset everytime I index.

In otherwords, my oldest analytics date is always the date of my latest indexation. 

Is there a way to have DocSearch preserve the analytics?

**Comment by s-pace** [comment]
It has been true but I have deployed a fix a few weeks ago. `ObjectID` is now base on the hash of the record instead of being autogenerated.
