### ISSUE TITLE
How to update objects by crawling recent_sitemap

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch#968]
I have an index stores all the results by crawling the [sitemap](https://docs.pingcap.com/website-docs-sitemap.xml). Later, I will generate a `recent_sitemap.xml` to list the URLs of pages, whose contents are just modified. 

I am wondering if there any API or configuration to set to ask algolia crawler to update the objects on the existed index by crawling the `recent_sitemap`.

@s-pace PTAL

**Comment by s-pace** [comment]
It is not possible to do partial update of a DocSearch index. You will need to go custom with Algolia and use your own Algolia plan.
