### ISSUE TITLE
DocSearch with Filters

### ISSUE THREAD

**Issue by lakshay-browserstack** [algolia/docsearch#970]
I am trying to implement docSearch and looking to provide filters for the users to search in a specific category within that. Since the indexing is majorly managed by Algolia in docSearch, I am not sure if something like this is possible.

I found out that we can alter the search UI experience for this by using instaSearch as in https://github.com/algolia/docsearch/issues/457. But I am not sure if I can create filter indexes.

If anyone can please confirm or deny this, it will be really appreciated.

**Comment by Haroenv** [comment]
Hi @lakshay-browserstack, with the default docsearch scraper, you can use:

- filters based on a URL's shape: https://docsearch.algolia.com/docs/config-file/#using-regular-expressions
- manual tags: https://docsearch.algolia.com/docs/config-file/#using-custom-tags
