### ISSUE TITLE
Cmd + K keyboard shortcut

### ISSUE THREAD

**Issue by sw-yx** [algolia/docsearch#973]
**What is the current behavior?**

i noticed you have this nice Cmd + K keyboard shortcut on your docs site
![image](https://user-images.githubusercontent.com/6764957/90946836-6f64e580-e463-11ea-9cf1-990b6a6738f4.png)

i would really like to have that for mine. however i searched the [site codebase](https://github.com/algolia/docsearch-website) and couldnt find it. could you give any hints on how to do this?

**Comment by kamranayub** [comment]
@francoischalifour Thanks, WIP integration for excalibur.js is in this PR: https://github.com/excaliburjs/excaliburjs.github.io/pull/56

**Comment by francoischalifour** [comment]
That's great @kamranayub! Make sure to upgrade to `@docsearch/react`'s latest alpha tag (as of today, [`1.0.0-alpha.28`](https://github.com/francoischalifour/autocomplete.js/blob/daab82d940536687ea8e4d5bc8e73df5728de4a0/CHANGELOG.md#100-alpha28-2020-08-26)) to get the latest fixes and features.

The docs look really well detailed and exhaustive, that's impressive.

**Comment by kamranayub** [comment]
> That's great @kamranayub! Make sure to upgrade to `@docsearch/react`'s latest alpha tag (as of today, [`1.0.0-alpha.28`](https://github.com/francoischalifour/autocomplete.js/blob/daab82d940536687ea8e4d5bc8e73df5728de4a0/CHANGELOG.md#100-alpha28-2020-08-26)) to get the latest fixes and features.
> 
> The docs look really well detailed and exhaustive, that's impressive.

Thanks! Right now I think I'm just running into an issue with the typing not showing up in the modal? I had to leave it this morning so I haven't debugged it.

**Comment by Shipow** [comment]
Hi @kamranayub, since your are using the V3 we need to adjust the configuration file accordingly. cc @shortcuts

**Comment by shortcuts** [comment]
Hi @kamranayub, I've updated your config with better `selectors` to match the v3 display. It should be effective after the next crawl, feel free to @ me if you want to change something/open a PR.

**Comment by oliviertassinari** [comment]
Is there a motivation for using <kbd>CTRL</kbd> +<kbd>K</kbd> over another shortcut? I thought that <kbd>/</kbd> was a convention for searching, e.g. [docusaurus](https://docusaurus.io/), [ux.stackexchange]( https://ux.stackexchange.com/questions/22606/emerging-conventions-for-keyboard-shortcuts-within-web-applications).

**Comment by francoischalifour** [comment]
@oliviertassinari There's a whole thread about the <kbd>Ctrl+K</kbd> in the [original Docusaurus PR](https://github.com/facebook/docusaurus/pull/2815#issuecomment-652438605). Note that <kbd>/</kbd> is also supported, although not displayed in the search button.

**Comment by oliviertassinari** [comment]
Great, thanks
