### ISSUE TITLE
New version of Search UI

### ISSUE THREAD

**Issue by cangencer** [algolia/docsearch#977]
Is there a way to use the new version of the search UI on a Docusaurus v1 site? 

Our config file is here: https://github.com/hazelcast/hazelcast-jet/blob/master/site/website/siteConfig.js

**Comment by s-pace** [comment]
👋 @cangencer 

We will need to update your configuration to make sure the v3 experience is smooth. We are working on a migration guide. The v3 is still in alpha.

However the v3 is only integrated in docusaurus v2 yet. As far as I know, it is not planned to have it integrated in docuaurus v1.
