### ISSUE TITLE
How do I control the default direction?

### ISSUE THREAD

**Issue by xrkffgg** [algolia/docsearch#979]
Usually the dom is like below

![image](https://user-images.githubusercontent.com/29775873/95829812-5abd1380-0d69-11eb-9729-d7c37e5b3797.png)

Is there a way for me to the remove default value of direction? Or control？

Thx

**Comment by Haroenv** [comment]
If you add the css `direction: rtl` to the input, the span will also get that direction :) 

You can see that in this autocomplete (underlying library to docsearch) sandbox: https://codesandbox.io/s/recursing-hill-7v84e?file=/src/app.js:239-407

**Comment by xrkffgg** [comment]
Oh, i see, thank you~
