### ISSUE TITLE
How often does the crawler run?

### ISSUE THREAD

**Issue by kaelig** [algolia/docsearch#98]
With a new release of our site that (soon) uses DocSearch coming up soon, we're going to introduce information architecture changes. Some pages will inevitably 404 and I was wondering how long it would  take the DocSearch crawler to re-index the new site architecture.

**Comment by ElPicador** [comment]
The crawler runs every 24 hours, so 24h hours to have the updated configuration

**Comment by kaelig** [comment]
Thank you!
