### ISSUE TITLE
webpack 5 build compatibility

### ISSUE THREAD

**Issue by pavelloz** [algolia/docsearch#980]
It looks like webpack 5 (or v4 with ceratin settings) breaks docsearch. I was following https://webpack.js.org/migrate/5/#test-webpack-5-compatibility to verify if we can upgrade and this is the only issue i found so far.

**Do you want to request a _feature_ or report a _bug_?**

Bug report

**What is the current behavior?**

Throws error in the browser
<img width="816" alt="image" src="https://user-images.githubusercontent.com/546845/95983596-2eb19900-0e22-11eb-90ac-ec9db3afc29d.png">

You can reproduce it by using webpack 4 and adding 
```
node: {
     Buffer: false,
     process: false
   }
```

to your config. Or just using webpack 5.

Example reproduction commit: https://github.com/mdyd-dev/platformos-documentation/compare/docsearch-repro?expand=1

**What is the expected behavior?**

It should work as without it 👍

**Comment by Haroenv** [comment]
> Want to use environment variables with process.env.VARIABLE? You need to use the DefinePlugin or EnvironmentPlugin to define these variables in the configuration.
> Consider using VARIABLE instead and make sure to check typeof VARIABLE !== 'undefined' too. process.env is Node.js specific and should be avoided in frontend code.

If you add this, does it work?

**Comment by pavelloz** [comment]
But what variable should i set? And to what value? I have no idea what docsearch internals are trying to use there, i just know the whole `process` object, when it get to the final build, is undefined.

I assume it is checking for something to debug, f.e. `process.DEBUG`, but the whole `process` is not available hence the error.

**Comment by Haroenv** [comment]
this should work: https://github.com/algolia/docsearch/blob/caad961c809e561f39efca8acdb0cfe5f0438ab9/webpack.config.jsdelivr.babel.js#L23-L27

Process just needs to be an object to be able to use algoliasearch@3 IIRC

**Comment by pavelloz** [comment]
@Haroenv thank you :) I will try that very soon :)

**Comment by mkascel** [comment]
See this link for why I went with `process.env.X` over a top-level `process.env` https://stackoverflow.com/questions/66772358/webpack-warning-warning-in-defineplugin-conflicting-values-for-process-env-no
