### ISSUE TITLE
I've submitted the application several times. Didn't receive the code that needs to be integrated into the page and I don't know why.

### ISSUE THREAD

**Issue by DsCodeStudio** [algolia/docsearch#982]
My website https://github.dscode.top. my email dscode.top@gmail.com

**Comment by shortcuts** [comment]
Hi,

Thanks for reaching out! We are receiving a lot of applications and sometimes it can be lost in the flow. 
I will get back to you ASAP by mail with your config file and API key.

Have a nice day.

**Comment by DsCodeStudio** [comment]
Wow, thank you very much.😃
