### ISSUE TITLE
Insufficient height modal dropdown on mobiles

### ISSUE THREAD

**Issue by lex111** [algolia/docsearch#984]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Try searching for something like "doc" on https://v2.docusaurus.io/ and you will see at the bottom of the search modal big empty space that should be taken up by the search results.

Via emulated mobile device in Chome: 

![image](https://user-images.githubusercontent.com/4408379/98925250-d0daa480-24e6-11eb-9fb2-5fd090d96e61.png)

On Google Pixel 3a XL via BrowserStack:

![image](https://user-images.githubusercontent.com/4408379/98925552-3169e180-24e7-11eb-946d-7cc137bbeca2.png)

On iPhone 11 Pro via BrowserStack:

![image](https://user-images.githubusercontent.com/4408379/98925915-ab01cf80-24e7-11eb-9a51-fbfecd7d52cf.png)

GIF:

![ezgif com-gif-maker (11)](https://user-images.githubusercontent.com/4408379/98926366-44c97c80-24e8-11eb-8756-96310496745a.gif)

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/4408379/98925342-ec45af80-24e6-11eb-9286-a87d54fe3eda.png)

cc @francoischalifour

**Comment by francoischalifour** [comment]
Hey @lex111! We fixed this issue in a8fb06305a4a015f102b876a34ae09f93f3718e4 but didn't release it yet. I'll send a PR to Docusaurus to upgrade the version once we release (by next week).

**Comment by lex111** [comment]
Great, but what about another bug in horizontal orientation, is it fixed? Notice the footer panel position, it overlaps the search results.

![ezgif com-gif-maker (12)](https://user-images.githubusercontent.com/4408379/98927728-f917d280-24e9-11eb-8198-7a047a3eeb5b.gif)

**Comment by lex111** [comment]
@francoischalifour any news?

**Comment by Shipow** [comment]
Hello Lex, we don't have a fix yet, but thanks for the reminder; we need to find a solution for this.

**Comment by francoischalifour** [comment]
Sorry—I got caught up on other projects this week.

We've planed some time next week to pack a new release. I'll keep you updating.

**Comment by francoischalifour** [comment]
Fix released in [`v3.0.0-alpha.29`](https://github.com/algolia/docsearch/releases/tag/v3.0.0-alpha.29).

I sent a PR to Docusaurus: facebook/docusaurus#3819.
