### ISSUE TITLE
Analytics / usage metrics?

### ISSUE THREAD

**Issue by kaelig** [algolia/docsearch#99]
What's the best way to know what queries users are looking for the most, and where they landed depending on their search?

**Comment by redox** [comment]
We're actually working on leveraging the analytics feature we already provide for our Algolia users, to DocSearch users. This will show you things like:
 - popular queries
 - popular queries returning no results
 - overview of where (country) they come from

**Comment by kaelig** [comment]
Sweet! In the mean time if you have examples of how we can send usage stats to Google Analytics, let me know.

**Comment by kaelig** [comment]
Thanks, I now have access to the metrics!
