### ISSUE TITLE
Is it possible to increase the Chinese version?

### ISSUE THREAD

**Issue by Xu-zhi-peng** [algolia/docsearch#997]
In China, some workers are using Algolia, but there is no Chinese version. It is somewhat difficult for users to use. So if the official can consider adding other language versions, such as Chinese. If needed, I am happy to help.

**Comment by Haroenv** [comment]
Hey @Xu-zhi-peng, what part would need to be translated? the content of the docsearch itself or something else?

**Comment by meteorlxy** [comment]
For next version, make those fields of #955 available in the Docsearch component would help
